version: 2

project_name: protoc-gen-mcp

builds:
  - id: protoc-gen-mcp
    binary: protoc-gen-mcp
    main: ./cmd/protoc-gen-mcp
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: protoc-gen-mcp
    ids:
      - protoc-gen-mcp
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    wrap_in_directory: true
    name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: easyp-tech
    name: protoc-gen-mcp

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'
