package codegen

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"google.golang.org/protobuf/compiler/protogen"
)

func TestGenerateExampleGolden(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageGo}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	got := generatedFileContent(t, plugin, "internal/testproto/example/v1/example.mcp.go")
	want := readExampleGolden(t, repoRoot(t))
	if !bytes.Equal(got, want) {
		t.Fatalf("fresh Go renderer output differs from golden:\n%s", diffBytes(want, got))
	}
}

func TestGeneratePythonExampleGolden(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	got := generatedFileContent(t, plugin, "internal/testproto/example/v1/example_mcp.py")
	want := readExamplePythonGolden(t, repoRoot(t))
	if !bytes.Equal(got, want) {
		t.Fatalf("fresh Python renderer output differs from golden:\n%s", diffBytes(want, got))
	}
}

func TestGenerateKotlinExampleGolden(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageKotlin}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	got := generatedFileContent(t, plugin, "internal/testproto/example/v1/example_mcp.kt")
	want := readExampleKotlinGolden(t, repoRoot(t))
	if !bytes.Equal(got, want) {
		t.Fatalf("fresh Kotlin renderer output differs from golden:\n%s", diffBytes(want, got))
	}
}

func TestGenerateJavaExampleGolden(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageJava}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	got := generatedFileContent(t, plugin, exampleJavaOutputPath())
	want := readExampleJavaGolden(t, repoRoot(t))
	if !bytes.Equal(got, want) {
		t.Fatalf("fresh Java renderer output differs from golden:\n%s", diffBytes(want, got))
	}
}

func TestGenerateTypeScriptExampleGolden(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageTypeScript}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	got := generatedFileContent(t, plugin, "internal/testproto/example/v1/example_mcp.ts")
	want := readExampleTypeScriptGolden(t, repoRoot(t))
	if !bytes.Equal(got, want) {
		t.Fatalf("fresh TypeScript renderer output differs from golden:\n%s", diffBytes(want, got))
	}
}

func TestGenerate_KotlinTargetEmitsOutput(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageKotlin}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	generated := string(generatedFileContent(t, plugin, "internal/testproto/example/v1/example_mcp.kt"))
	wantSnippets := []string{
		"interface ExampleAPIToolHandler",
		"fun registerExampleAPITools(server: Server, impl: ExampleAPIToolHandler, namespace: String? = null)",
		"installMcpHandlers(server)",
		"private class ServerToolRegistry",
		"private suspend fun dispatchToolCall",
		"ListToolsRequest",
		"CallToolRequest",
	}
	for _, snippet := range wantSnippets {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated Kotlin missing snippet %q\n%s", snippet, generated)
		}
	}
	if strings.Contains(generated, "server."+"addTool(") {
		t.Fatalf("generated Kotlin must not use high-level server tool registration\n%s", generated)
	}
}

func TestGenerate_JavaTargetEmitsOutput(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageJava}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	generated := string(generatedFileContent(t, plugin, exampleJavaOutputPath()))
	wantSnippets := []string{
		"public final class ExampleMcp {",
		"public interface ExampleAPIToolHandler {",
		"public static void registerExampleAPITools(",
		"transportProvider.setSessionFactory(",
		"requestHandlers.put(McpSchema.METHOD_TOOLS_LIST",
		"requestHandlers.put(McpSchema.METHOD_TOOLS_CALL",
		"JsonFormat.parser().usingTypeRegistry(PROTO_TYPE_REGISTRY).merge(",
		"alwaysPrintFieldsWithNoPresence()",
	}
	for _, snippet := range wantSnippets {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated Java missing snippet %q\n%s", snippet, generated)
		}
	}
	for _, snippet := range []string{"addTool(", "Tool.builder("} {
		if strings.Contains(generated, snippet) {
			t.Fatalf("generated Java must not use convenience registration snippet %q\n%s", snippet, generated)
		}
	}
}

func TestGenerate_TypeScriptTargetEmitsOutput(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageTypeScript}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	generated := string(generatedFileContent(t, plugin, "internal/testproto/example/v1/example_mcp.ts"))
	wantSnippets := []string{
		"// Code generated by protoc-gen-mcp. DO NOT EDIT.",
		"// source: internal/testproto/example/v1/example.proto",
		"export const EXAMPLE_API_CREATE_REPORT_INPUT_SCHEMA_JSON",
		"export const EXAMPLE_API_CREATE_REPORT_OUTPUT_SCHEMA_JSON",
		"export const EXAMPLE_API_DESCRIBE_ADVANCED_SHAPES_INPUT_SCHEMA_JSON",
		"export const EXAMPLE_API_DESCRIBE_SCALAR_SHAPES_OUTPUT_SCHEMA_JSON",
	}
	for _, snippet := range wantSnippets {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated TypeScript missing snippet %q\n%s", snippet, generated)
		}
	}
	for _, snippet := range []string{"registerTool", "zod", "lang=javascript"} {
		if strings.Contains(generated, snippet) {
			t.Fatalf("generated TypeScript foundation must not contain snippet %q\n%s", snippet, generated)
		}
	}
}

func TestGenerate_PythonEmitsMCPNamespaceBridge(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	generated := string(generatedFileContent(t, plugin, "mcp/__init__.py"))
	wantSnippets := []string{
		`"""Bridge generated mcp.options.* modules with the official MCP SDK package."""`,
		"from pkgutil import extend_path",
		"__path__ = extend_path(__path__, __name__)",
	}
	for _, snippet := range wantSnippets {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated namespace bridge missing snippet %q\n%s", snippet, generated)
		}
	}
}

func TestGenerate_PythonEmitsPackageInitFiles(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/service.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/service;servicev1";`,
			`message PingRequest {}`,
			`message PingResponse {}`,
			`service PingAPI {`,
			`  rpc Ping(PingRequest) returns (PingResponse);`,
			`}`,
			``,
		}, "\n"),
	}, "test/v1/service.proto")

	if err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	generated := string(generatedFileContent(t, plugin, "test/v1/__init__.py"))
	if !strings.Contains(generated, "# Code generated by protoc-gen-mcp. DO NOT EDIT.") {
		t.Fatalf("package __init__.py missing generated marker\n%s", generated)
	}
}

func TestGenerate_PythonEmitsCrossFilePublicTypeModules(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/shared.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/shared;sharedv1";`,
			`message SharedRequest {}`,
			`message SharedResponse {}`,
			``,
		}, "\n"),
		"test/v1/service.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/service;servicev1";`,
			`import "test/v1/shared.proto";`,
			`service CrossFileAPI {`,
			`  rpc UseShared(SharedRequest) returns (SharedResponse);`,
			`}`,
			``,
		}, "\n"),
	}, "test/v1/shared.proto", "test/v1/service.proto")

	if err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	serviceGenerated := string(generatedFileContent(t, plugin, "test/v1/service_mcp.py"))
	if !strings.Contains(serviceGenerated, "from test.v1 import shared_mcp as test_v1_shared_mcp") {
		t.Fatalf("service module must import generated shared public module\n%s", serviceGenerated)
	}

	sharedGenerated := string(generatedFileContent(t, plugin, "test/v1/shared_mcp.py"))
	for _, snippet := range []string{
		"class SharedRequest:",
		"class SharedResponse:",
	} {
		if !strings.Contains(sharedGenerated, snippet) {
			t.Fatalf("shared module missing public dataclass snippet %q\n%s", snippet, sharedGenerated)
		}
	}
}

func TestGenerate_PythonEmitsPublicTypesForHiddenOnlyServiceImports(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/shared.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/shared;sharedv1";`,
			`import "mcp/options/v1/options.proto";`,
			`message SharedRequest {`,
			`  string label = 1;`,
			`}`,
			`message SharedResponse {`,
			`  string label = 1;`,
			`}`,
			`service SharedAPI {`,
			`  rpc HiddenEcho(SharedRequest) returns (SharedResponse) {`,
			`    option (mcp.options.v1.method) = { hidden: true };`,
			`  }`,
			`}`,
			``,
		}, "\n"),
		"test/v1/service.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/service;servicev1";`,
			`import "test/v1/shared.proto";`,
			`message UseSharedRequest {`,
			`  SharedRequest request = 1;`,
			`}`,
			`message UseSharedResponse {`,
			`  SharedResponse response = 1;`,
			`}`,
			`service VisibleAPI {`,
			`  rpc UseShared(UseSharedRequest) returns (UseSharedResponse);`,
			`}`,
			``,
		}, "\n"),
	}, "test/v1/shared.proto", "test/v1/service.proto")

	if err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	sharedGenerated := string(generatedFileContent(t, plugin, "test/v1/shared_mcp.py"))
	for _, snippet := range []string{
		"class SharedRequest:",
		"class SharedResponse:",
	} {
		if !strings.Contains(sharedGenerated, snippet) {
			t.Fatalf("shared hidden-only module missing snippet %q\n%s", snippet, sharedGenerated)
		}
	}

	serviceGenerated := string(generatedFileContent(t, plugin, "test/v1/service_mcp.py"))
	if !strings.Contains(serviceGenerated, "from test.v1 import shared_mcp as") {
		t.Fatalf("service module must import hidden-only shared public module\n%s", serviceGenerated)
	}
}

func TestGenerate_PythonEmitsCurrentFilePublicTypesUnusedByLocalServices(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/shared.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/shared;sharedv1";`,
			`message SharedRequest {}`,
			`message SharedResponse {}`,
			`message ExportedDetails {`,
			`  string label = 1;`,
			`}`,
			`service SharedAPI {`,
			`  rpc Echo(SharedRequest) returns (SharedResponse);`,
			`}`,
			``,
		}, "\n"),
		"test/v1/service.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/service;servicev1";`,
			`import "test/v1/shared.proto";`,
			`message UseSharedRequest {`,
			`  ExportedDetails details = 1;`,
			`}`,
			`message UseSharedResponse {`,
			`  ExportedDetails details = 1;`,
			`}`,
			`service VisibleAPI {`,
			`  rpc UseShared(UseSharedRequest) returns (UseSharedResponse);`,
			`}`,
			``,
		}, "\n"),
	}, "test/v1/shared.proto", "test/v1/service.proto")

	if err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	sharedGenerated := string(generatedFileContent(t, plugin, "test/v1/shared_mcp.py"))
	if !strings.Contains(sharedGenerated, "class ExportedDetails:") {
		t.Fatalf("shared module missing unrelated exported public type\n%s", sharedGenerated)
	}

	serviceGenerated := string(generatedFileContent(t, plugin, "test/v1/service_mcp.py"))
	for _, snippet := range []string{
		"from test.v1 import shared_mcp as",
		".ExportedDetails",
	} {
		if !strings.Contains(serviceGenerated, snippet) {
			t.Fatalf("service module missing cross-file public type snippet %q\n%s", snippet, serviceGenerated)
		}
	}
}

func TestGoRendererMatchesExistingGolden(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	file := plugin.FilesByPath["internal/testproto/example/v1/example.proto"]
	model, err := CollectFileModel(file, Options{Language: LanguageGo})
	if err != nil {
		t.Fatalf("CollectFileModel: %v", err)
	}
	if err := renderGoFile(plugin, model); err != nil {
		t.Fatalf("renderGoFile: %v", err)
	}

	got := generatedFileContent(t, plugin, "internal/testproto/example/v1/example.mcp.go")
	want := readExampleGolden(t, repoRoot(t))
	if !bytes.Equal(got, want) {
		t.Fatalf("fresh Go renderer output differs from golden:\n%s", diffBytes(want, got))
	}
}

func TestGeneratedSchemasUseInterpretedStringLiterals(t *testing.T) {
	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageGo}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	generated := string(generatedFileContent(t, plugin, "internal/testproto/example/v1/example.mcp.go"))
	if strings.Contains(generated, "InputSchemaJSON = `") || strings.Contains(generated, "OutputSchemaJSON = `") {
		t.Fatalf("generated schema constants must not use raw string literals:\n%s", generated)
	}
	if !strings.Contains(generated, "`StringValue`") {
		t.Fatalf("generated schema descriptions should preserve backticks from proto comments:\n%s", generated)
	}
}

func TestGenerate_GoEmitsReadOnlyHintAnnotation(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/annotations.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`import "mcp/options/v1/options.proto";`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/annotations;annotationsv1";`,
			`message AnnotatedRequest {}`,
			`message AnnotatedResponse {}`,
			`service AnnotatedAPI {`,
			`  rpc ReadThing(AnnotatedRequest) returns (AnnotatedResponse) {`,
			`    option (mcp.options.v1.method) = {`,
			`      annotations: {`,
			`        read_only_hint: true`,
			`        idempotent_hint: true`,
			`        open_world_hint: true`,
			`      }`,
			`    };`,
			`  }`,
			`}`,
			``,
		}, "\n"),
	}, "test/v1/annotations.proto")

	if err := Generate(plugin, Options{Language: LanguageGo}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	generated := string(generatedFileContent(t, plugin, "test/v1/annotations.mcp.go"))
	for _, snippet := range []string{
		"ReadOnlyHint: true,",
		"IdempotentHint: true,",
		"OpenWorldHint: proto.Bool(true)",
	} {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated go missing annotation snippet %q\n%s", snippet, generated)
		}
	}
}

func TestEasypGenerateUnsupportedFails(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/unsupported.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/unsupported;unsupportedv1";`,
			`import "google/protobuf/type.proto";`,
			`message BuildUnsupportedRequest {`,
			`  google.protobuf.Type payload = 1;`,
			`}`,
			`message BuildUnsupportedResponse {}`,
			`service UnsupportedAPI {`,
			`  rpc BuildUnsupported(BuildUnsupportedRequest) returns (BuildUnsupportedResponse);`,
			`}`,
			"",
		}, "\n"),
	}, "test/v1/unsupported.proto")

	err := Generate(plugin, Options{Language: LanguageGo})
	if err == nil {
		t.Fatal("Generate unexpectedly succeeded")
	}

	if !strings.Contains(err.Error(), `well-known type "google.protobuf.Type" is not supported`) {
		t.Fatalf("unexpected generator failure: %v", err)
	}
}

func TestGenerate_PythonUnsupportedDescriptorFails(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/unsupported.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/unsupported;unsupportedv1";`,
			`import "google/protobuf/type.proto";`,
			`message BuildUnsupportedRequest {`,
			`  google.protobuf.Type payload = 1;`,
			`}`,
			`message BuildUnsupportedResponse {}`,
			`service UnsupportedAPI {`,
			`  rpc BuildUnsupported(BuildUnsupportedRequest) returns (BuildUnsupportedResponse);`,
			`}`,
			"",
		}, "\n"),
	}, "test/v1/unsupported.proto")

	err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	})
	if err == nil {
		t.Fatal("Generate unexpectedly succeeded")
	}

	if !strings.Contains(err.Error(), `well-known type "google.protobuf.Type" is not supported`) {
		t.Fatalf("unexpected generator failure: %v", err)
	}
	if len(plugin.Response().GetFile()) != 0 {
		t.Fatalf("python unsupported descriptor emitted %d files, want 0", len(plugin.Response().GetFile()))
	}
}

func TestGenerate_JVMUnsupportedDescriptorFailsBeforeOutput(t *testing.T) {
	tests := []struct {
		name     string
		language Language
	}{
		{
			name:     "kotlin",
			language: LanguageKotlin,
		},
		{
			name:     "java",
			language: LanguageJava,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			plugin := newTempProtogenPlugin(t, map[string]string{
				"test/v1/unsupported.proto": strings.Join([]string{
					`syntax = "proto3";`,
					`package test.v1;`,
					`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/unsupported;unsupportedv1";`,
					`import "google/protobuf/type.proto";`,
					`message BuildUnsupportedRequest {`,
					`  google.protobuf.Type payload = 1;`,
					`}`,
					`message BuildUnsupportedResponse {}`,
					`service UnsupportedAPI {`,
					`  rpc BuildUnsupported(BuildUnsupportedRequest) returns (BuildUnsupportedResponse);`,
					`}`,
					"",
				}, "\n"),
			}, "test/v1/unsupported.proto")

			err := Generate(plugin, Options{Language: tt.language})
			if err == nil {
				t.Fatal("Generate unexpectedly succeeded")
			}
			if !strings.Contains(err.Error(), `well-known type "google.protobuf.Type" is not supported`) {
				t.Fatalf("unexpected generator failure: %v", err)
			}
			if len(plugin.Response().GetFile()) != 0 {
				t.Fatalf("JVM unsupported descriptor emitted %d files, want 0", len(plugin.Response().GetFile()))
			}
		})
	}
}

func TestGenerate_TypeScriptUnsupportedDescriptorFailsBeforeOutput(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/unsupported.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/unsupported;unsupportedv1";`,
			`import "google/protobuf/type.proto";`,
			`message BuildUnsupportedRequest {`,
			`  google.protobuf.Type payload = 1;`,
			`}`,
			`message BuildUnsupportedResponse {}`,
			`service UnsupportedAPI {`,
			`  rpc BuildUnsupported(BuildUnsupportedRequest) returns (BuildUnsupportedResponse);`,
			`}`,
			"",
		}, "\n"),
	}, "test/v1/unsupported.proto")

	err := Generate(plugin, Options{Language: LanguageTypeScript})
	if err == nil {
		t.Fatal("Generate unexpectedly succeeded")
	}
	if !strings.Contains(err.Error(), `well-known type "google.protobuf.Type" is not supported`) {
		t.Fatalf("unexpected generator failure: %v", err)
	}
	if len(plugin.Response().GetFile()) != 0 {
		t.Fatalf("TypeScript unsupported descriptor emitted %d files, want 0", len(plugin.Response().GetFile()))
	}
}

func TestGenerate_PythonUnsupportedRuntimeBetterprotoFails(t *testing.T) {
	root := repoRoot(t)

	output, err := runEasypGenerateExpectFailure(t, root, strings.Join([]string{
		"generate:",
		"  inputs:",
		"    - directory:",
		"        path: internal/testproto",
		"        root: \".\"",
		"  plugins:",
		"    - command: [\"go\", \"run\", \"./cmd/protoc-gen-mcp\"]",
		"      out: .",
		"      opts:",
		"        paths: source_relative",
		"        lang: python",
		"        python_runtime: betterproto",
		"",
	}, "\n"), "internal/testproto")
	if err == nil {
		t.Fatal("easyp generate unexpectedly succeeded")
	}

	if !strings.Contains(output, `unsupported python_runtime "betterproto"`) {
		t.Fatalf("unexpected easyp failure output:\n%s", output)
	}
}

func TestGenerate_PythonUnsupportedRuntimeGrpclibFails(t *testing.T) {
	root := repoRoot(t)

	output, err := runEasypGenerateExpectFailure(t, root, strings.Join([]string{
		"generate:",
		"  inputs:",
		"    - directory:",
		"        path: internal/testproto",
		"        root: \".\"",
		"  plugins:",
		"    - command: [\"go\", \"run\", \"./cmd/protoc-gen-mcp\"]",
		"      out: .",
		"      opts:",
		"        paths: source_relative",
		"        lang: python",
		"        python_runtime: grpclib",
		"",
	}, "\n"), "internal/testproto")
	if err == nil {
		t.Fatal("easyp generate unexpectedly succeeded")
	}

	if !strings.Contains(output, `unsupported python_runtime "grpclib"`) {
		t.Fatalf("unexpected easyp failure output:\n%s", output)
	}
}

func TestGenerate_PythonStreamingRPCFails(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/streaming.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/streaming;streamingv1";`,
			`message StreamingRequest {}`,
			`message StreamingResponse {}`,
			`service StreamingAPI {`,
			`  rpc Watch(StreamingRequest) returns (stream StreamingResponse);`,
			`}`,
			"",
		}, "\n"),
	}, "test/v1/streaming.proto")

	err := Generate(plugin, Options{
		Language:      LanguagePython,
		PythonRuntime: PythonRuntimeGoogleProtobuf,
	})
	if err == nil {
		t.Fatal("Generate unexpectedly succeeded")
	}

	if !strings.Contains(err.Error(), `streaming RPC is not supported`) {
		t.Fatalf("unexpected generator failure: %v", err)
	}
	if len(plugin.Response().GetFile()) != 0 {
		t.Fatalf("python streaming RPC emitted %d files, want 0", len(plugin.Response().GetFile()))
	}
}

func TestGenerate_JVMStreamingRPCFailsBeforeOutput(t *testing.T) {
	tests := []struct {
		name     string
		language Language
	}{
		{
			name:     "kotlin",
			language: LanguageKotlin,
		},
		{
			name:     "java",
			language: LanguageJava,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			plugin := newTempProtogenPlugin(t, map[string]string{
				"test/v1/streaming.proto": strings.Join([]string{
					`syntax = "proto3";`,
					`package test.v1;`,
					`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/streaming;streamingv1";`,
					`message StreamingRequest {}`,
					`message StreamingResponse {}`,
					`service StreamingAPI {`,
					`  rpc Watch(StreamingRequest) returns (stream StreamingResponse);`,
					`}`,
					"",
				}, "\n"),
			}, "test/v1/streaming.proto")

			err := Generate(plugin, Options{Language: tt.language})
			if err == nil {
				t.Fatal("Generate unexpectedly succeeded")
			}
			if !strings.Contains(err.Error(), `streaming RPC is not supported`) {
				t.Fatalf("unexpected generator failure: %v", err)
			}
			if len(plugin.Response().GetFile()) != 0 {
				t.Fatalf("JVM streaming RPC emitted %d files, want 0", len(plugin.Response().GetFile()))
			}
		})
	}
}

func TestGenerate_TypeScriptStreamingRPCFailsBeforeOutput(t *testing.T) {
	plugin := newTempProtogenPlugin(t, map[string]string{
		"test/v1/streaming.proto": strings.Join([]string{
			`syntax = "proto3";`,
			`package test.v1;`,
			`option go_package = "github.com/easyp-tech/protoc-gen-mcp/internal/codegen/testdata/streaming;streamingv1";`,
			`message StreamingRequest {}`,
			`message StreamingResponse {}`,
			`service StreamingAPI {`,
			`  rpc Watch(StreamingRequest) returns (stream StreamingResponse);`,
			`}`,
			"",
		}, "\n"),
	}, "test/v1/streaming.proto")

	err := Generate(plugin, Options{Language: LanguageTypeScript})
	if err == nil {
		t.Fatal("Generate unexpectedly succeeded")
	}
	if !strings.Contains(err.Error(), `streaming RPC is not supported`) {
		t.Fatalf("unexpected generator failure: %v", err)
	}
	if len(plugin.Response().GetFile()) != 0 {
		t.Fatalf("TypeScript streaming RPC emitted %d files, want 0", len(plugin.Response().GetFile()))
	}
}

func TestGenerateJavaExampleHandlerCompileSmoke(t *testing.T) {
	if _, err := exec.LookPath("javac"); err != nil {
		t.Skipf("javac not found in PATH: %v", err)
	}

	plugin := newExampleProtogenPlugin(t)
	if err := Generate(plugin, Options{Language: LanguageJava}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	exampleFile := plugin.FilesByPath["internal/testproto/example/v1/example.proto"]
	if exampleFile == nil {
		t.Fatal("example proto file not found in plugin")
	}
	shared, err := CollectFileModel(exampleFile, Options{Language: LanguageJava})
	if err != nil {
		t.Fatalf("CollectFileModel: %v", err)
	}
	jvm, err := CollectJVMFileModel(exampleFile, shared)
	if err != nil {
		t.Fatalf("CollectJVMFileModel: %v", err)
	}
	info, err := newJavaRenderInfo(plugin, jvm)
	if err != nil {
		t.Fatalf("newJavaRenderInfo: %v", err)
	}
	filePackage, err := resolveJVMFilePackage(exampleFile)
	if err != nil {
		t.Fatalf("resolveJVMFilePackage: %v", err)
	}

	tempDir := t.TempDir()
	writeJavaTestSource(t, tempDir, exampleJavaOutputPath(), generatedFileContent(t, plugin, exampleJavaOutputPath()))
	writeJavaTestSource(t, tempDir, filepath.Join("internal/testproto/example/v1", "ExampleHandler.java"), []byte(generateExampleJavaHandlerSource(t, jvm, info, filePackage.Package)))
	writeJavaProtoStubs(t, tempDir, exampleFile, jvm)
	writeJavaSDKStubs(t, tempDir)

	sources := collectJavaSources(t, tempDir)
	cmd := exec.Command("javac", sources...)
	cmd.Dir = tempDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("javac failed: %v\n%s", err, output)
	}
}

func TestGenerate_RejectsUnknownCustomParamAndAllowsBuiltInParams(t *testing.T) {
	root := repoRoot(t)

	output, err := runEasypGenerateExpectFailure(t, root, strings.Join([]string{
		"generate:",
		"  inputs:",
		"    - directory:",
		"        path: internal/testproto",
		"        root: \".\"",
		"  plugins:",
		"    - command: [\"go\", \"run\", \"./cmd/protoc-gen-mcp\"]",
		"      out: .",
		"      opts:",
		"        paths: source_relative",
		"        Minternal/testproto/example/v1/example.proto: example.com/project/internal/testproto/example/v1;examplev1",
		"        apilevelMinternal/testproto/example/v1/example.proto: API_OPEN",
		"        lang: python",
		"        python_runtme: google.protobuf",
		"",
	}, "\n"), "internal/testproto")
	if err == nil {
		t.Fatal("easyp generate unexpectedly succeeded")
	}

	if !strings.Contains(output, `unknown protoc-gen-mcp option "python_runtme"`) {
		t.Fatalf("unexpected easyp failure output:\n%s", output)
	}
}

func runEasyp(t *testing.T, dir string, config string, args ...string) string {
	t.Helper()

	if _, err := exec.LookPath("easyp"); err != nil {
		t.Fatalf("easyp not found in PATH: %v", err)
	}

	cmdArgs := append([]string{"--cfg", config}, args...)
	cmd := exec.Command("easyp", cmdArgs...)
	cmd.Dir = dir

	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("easyp %v failed: %v\n%s", args, err, output)
	}

	return string(output)
}

func exampleJavaOutputPath() string {
	return javaSidecarOutputPath(jvmGeneratedFilenamePrefixForProtoPath("internal/testproto/example/v1/example.proto"))
}

func runEasypGenerateExpectFailure(t *testing.T, dir string, config string, pkg string) (string, error) {
	t.Helper()

	if _, err := exec.LookPath("easyp"); err != nil {
		t.Fatalf("easyp not found in PATH: %v", err)
	}

	configPath := filepath.Join(t.TempDir(), "easyp.generate.yaml")
	if err := os.WriteFile(configPath, []byte(config), 0o600); err != nil {
		t.Fatalf("write temp config: %v", err)
	}

	cmd := exec.Command("easyp", "--cfg", configPath, "generate", "-p", pkg, "-r", ".")
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	return string(output), err
}

func readExampleGolden(t *testing.T, root string) []byte {
	t.Helper()

	wantPath := filepath.Join(root, "testdata/golden/example.mcp.go.golden")
	want, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("read golden file %q: %v", wantPath, err)
	}
	return want
}

func readExamplePythonGolden(t *testing.T, root string) []byte {
	t.Helper()

	wantPath := filepath.Join(root, "testdata/golden/example_mcp.py.golden")
	want, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("read golden file %q: %v", wantPath, err)
	}
	return want
}

func readExampleKotlinGolden(t *testing.T, root string) []byte {
	t.Helper()

	wantPath := filepath.Join(root, "testdata/golden/example_mcp.kt.golden")
	want, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("read golden file %q: %v", wantPath, err)
	}
	return want
}

func readExampleJavaGolden(t *testing.T, root string) []byte {
	t.Helper()

	wantPath := filepath.Join(root, "testdata/golden/example_mcp.java.golden")
	want, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("read golden file %q: %v", wantPath, err)
	}
	return want
}

func readExampleTypeScriptGolden(t *testing.T, root string) []byte {
	t.Helper()

	wantPath := filepath.Join(root, "testdata/golden/example_mcp.ts.golden")
	want, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("read golden file %q: %v", wantPath, err)
	}
	return want
}

func generatedFileContent(t *testing.T, plugin *protogen.Plugin, path string) []byte {
	t.Helper()

	for _, file := range plugin.Response().GetFile() {
		if file.GetName() == path {
			return []byte(file.GetContent())
		}
	}

	t.Fatalf("generated file %q not found in plugin response", path)
	return nil
}

func writeJavaTestSource(t *testing.T, root string, relativePath string, content []byte) {
	t.Helper()

	target := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatalf("mkdir %q: %v", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, content, 0o600); err != nil {
		t.Fatalf("write %q: %v", target, err)
	}
}

func collectJavaSources(t *testing.T, root string) []string {
	t.Helper()

	var sources []string
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if filepath.Ext(path) == ".java" {
			sources = append(sources, path)
		}
		return nil
	}); err != nil {
		t.Fatalf("walk java sources: %v", err)
	}
	return sources
}

func generateExampleJavaHandlerSource(t *testing.T, model JVMFileModel, info javaRenderInfo, currentPackage string) string {
	t.Helper()

	if len(model.Services) != 1 {
		t.Fatalf("example JVM service count = %d, want 1", len(model.Services))
	}

	service := model.Services[0]
	className := javaSidecarClassName(model.GeneratedFilenamePrefix)
	var body strings.Builder
	body.WriteString("package " + currentPackage + ";\n\n")
	body.WriteString("import io.modelcontextprotocol.server.McpAsyncServerExchange;\n\n")
	body.WriteString("public final class ExampleHandler implements " + className + "." + service.HandlerName + " {\n")
	for _, method := range service.Methods {
		inputType, err := info.javaTypeExpr(method.Input, map[string]bool{}, currentPackage)
		if err != nil {
			t.Fatalf("java input type expr for %s: %v", method.MethodName, err)
		}
		outputType, err := info.javaTypeExpr(method.Output, map[string]bool{}, currentPackage)
		if err != nil {
			t.Fatalf("java output type expr for %s: %v", method.MethodName, err)
		}
		body.WriteString("  @Override\n")
		body.WriteString("  public " + outputType + " " + method.MethodName + "(McpAsyncServerExchange ctx, " + inputType + " request) throws Exception {\n")
		body.WriteString("    return " + outputType + ".newBuilder().build();\n")
		body.WriteString("  }\n")
	}
	body.WriteString("}\n")
	return body.String()
}

func writeJavaProtoStubs(t *testing.T, root string, file *protogen.File, model JVMFileModel) {
	t.Helper()

	filePackage, err := resolveJVMFilePackage(file)
	if err != nil {
		t.Fatalf("resolveJVMFilePackage: %v", err)
	}

	typeNames := map[string]struct{}{}
	for _, service := range model.Services {
		for _, method := range service.Methods {
			if method.Input.Owner.IsCurrentFile {
				typeNames[method.Input.PublicName] = struct{}{}
			}
			if method.Output.Owner.IsCurrentFile {
				typeNames[method.Output.PublicName] = struct{}{}
			}
		}
	}

	names := make([]string, 0, len(typeNames))
	for name := range typeNames {
		names = append(names, name)
	}

	packagePath := filepath.Join(strings.Split(filePackage.Package, ".")...)
	if filePackage.MultipleFiles {
		for _, name := range names {
			writeJavaTestSource(t, root, filepath.Join(packagePath, name+".java"), []byte(javaTopLevelMessageStub(filePackage.Package, name)))
		}
		return
	}

	writeJavaTestSource(t, root, filepath.Join(packagePath, filePackage.OuterClassName+".java"), []byte(javaOuterClassStub(filePackage.Package, filePackage.OuterClassName, names)))
}

func javaTopLevelMessageStub(pkg string, name string) string {
	return strings.Join([]string{
		"package " + pkg + ";",
		"",
		"import com.google.protobuf.Message;",
		"",
		"public final class " + name + " implements Message {",
		"  public static Builder newBuilder() {",
		"    return new Builder();",
		"  }",
		"",
		"  public static final class Builder implements Message.Builder {",
		"    @Override",
		"    public " + name + " build() {",
		"      return new " + name + "();",
		"    }",
		"  }",
		"}",
		"",
	}, "\n")
}

func javaOuterClassStub(pkg string, outerClassName string, names []string) string {
	var body strings.Builder
	body.WriteString("package " + pkg + ";\n\n")
	body.WriteString("import com.google.protobuf.Descriptors;\n")
	body.WriteString("import com.google.protobuf.Message;\n\n")
	body.WriteString("public final class " + outerClassName + " {\n")
	body.WriteString("  private " + outerClassName + "() {\n")
	body.WriteString("  }\n\n")
	body.WriteString("  public static Descriptors.FileDescriptor getDescriptor() {\n")
	body.WriteString("    return new Descriptors.FileDescriptor();\n")
	body.WriteString("  }\n\n")
	for _, name := range names {
		body.WriteString("  public static final class " + name + " implements Message {\n")
		body.WriteString("    public static Builder newBuilder() {\n")
		body.WriteString("      return new Builder();\n")
		body.WriteString("    }\n\n")
		body.WriteString("    public static final class Builder implements Message.Builder {\n")
		body.WriteString("      @Override\n")
		body.WriteString("      public " + name + " build() {\n")
		body.WriteString("        return new " + name + "();\n")
		body.WriteString("      }\n")
		body.WriteString("    }\n")
		body.WriteString("  }\n\n")
	}
	body.WriteString("}\n")
	return body.String()
}

func writeJavaSDKStubs(t *testing.T, root string) {
	t.Helper()

	stubs := map[string]string{
		"com/google/protobuf/Message.java": strings.Join([]string{
			"package com.google.protobuf;",
			"",
			"public interface Message {",
			"  interface Builder {",
			"    Message build();",
			"  }",
			"}",
			"",
		}, "\n"),
		"com/google/protobuf/Descriptors.java": strings.Join([]string{
			"package com.google.protobuf;",
			"",
			"import java.util.List;",
			"",
			"public final class Descriptors {",
			"  private Descriptors() {",
			"  }",
			"",
			"  public static final class FileDescriptor {",
			"    public String getFullName() {",
			"      return \"stub\";",
			"    }",
			"",
			"    public List<Descriptor> getMessageTypes() {",
			"      return List.of();",
			"    }",
			"  }",
			"",
			"  public static final class Descriptor {",
			"    public List<Descriptor> getNestedTypes() {",
			"      return List.of();",
			"    }",
			"  }",
			"}",
			"",
		}, "\n"),
		"com/google/protobuf/util/JsonFormat.java": strings.Join([]string{
			"package com.google.protobuf.util;",
			"",
			"import com.google.protobuf.Descriptors;",
			"import com.google.protobuf.Message;",
			"",
			"public final class JsonFormat {",
			"  private JsonFormat() {",
			"  }",
			"",
			"  public static Parser parser() {",
			"    return new Parser();",
			"  }",
			"",
			"  public static Printer printer() {",
			"    return new Printer();",
			"  }",
			"",
			"  public static final class TypeRegistry {",
			"    public static Builder newBuilder() {",
			"      return new Builder();",
			"    }",
			"",
			"    public static final class Builder {",
			"      public Builder add(Descriptors.Descriptor descriptor) {",
			"        return this;",
			"      }",
			"",
			"      public TypeRegistry build() {",
			"        return new TypeRegistry();",
			"      }",
			"    }",
			"  }",
			"",
			"  public static final class Parser {",
			"    public Parser usingTypeRegistry(TypeRegistry registry) {",
			"      return this;",
			"    }",
			"",
			"    public void merge(String payload, Message.Builder builder) throws Exception {",
			"    }",
			"  }",
			"",
			"  public static final class Printer {",
			"    public Printer usingTypeRegistry(TypeRegistry registry) {",
			"      return this;",
			"    }",
			"",
			"    public Printer alwaysPrintFieldsWithNoPresence() {",
			"      return this;",
			"    }",
			"",
			"    public Printer omittingInsignificantWhitespace() {",
			"      return this;",
			"    }",
			"",
			"    public String print(Message message) throws Exception {",
			"      return \"{}\";",
			"    }",
			"  }",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/json/TypeRef.java": strings.Join([]string{
			"package io.modelcontextprotocol.json;",
			"",
			"public abstract class TypeRef<T> {",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/json/McpJsonMapper.java": strings.Join([]string{
			"package io.modelcontextprotocol.json;",
			"",
			"import java.io.IOException;",
			"",
			"public interface McpJsonMapper {",
			"  <T> T readValue(String content, TypeRef<T> type) throws IOException;",
			"  <T> T convertValue(Object fromValue, Class<T> type);",
			"  String writeValueAsString(Object value) throws IOException;",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/json/McpJsonDefaults.java": strings.Join([]string{
			"package io.modelcontextprotocol.json;",
			"",
			"import io.modelcontextprotocol.json.schema.JsonSchemaValidator;",
			"",
			"public final class McpJsonDefaults {",
			"  private static final McpJsonMapper MAPPER = new McpJsonMapper() {",
			"    @Override",
			"    public <T> T readValue(String content, TypeRef<T> type) {",
			"      return null;",
			"    }",
			"",
			"    @Override",
			"    public <T> T convertValue(Object fromValue, Class<T> type) {",
			"      return null;",
			"    }",
			"",
			"    @Override",
			"    public String writeValueAsString(Object value) {",
			"      return \"{}\";",
			"    }",
			"  };",
			"",
			"  private static final JsonSchemaValidator VALIDATOR = (schema, structuredContent) -> JsonSchemaValidator.ValidationResponse.asValid(\"{}\");",
			"",
			"  private McpJsonDefaults() {",
			"  }",
			"",
			"  public static McpJsonMapper getMapper() {",
			"    return MAPPER;",
			"  }",
			"",
			"  public static JsonSchemaValidator getSchemaValidator() {",
			"    return VALIDATOR;",
			"  }",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/json/schema/JsonSchemaValidator.java": strings.Join([]string{
			"package io.modelcontextprotocol.json.schema;",
			"",
			"import java.util.Map;",
			"",
			"public interface JsonSchemaValidator {",
			"  ValidationResponse validate(Map<String, Object> schema, Object structuredContent);",
			"",
			"  final class ValidationResponse {",
			"    private final boolean valid;",
			"    private final String errorMessage;",
			"",
			"    private ValidationResponse(boolean valid, String errorMessage) {",
			"      this.valid = valid;",
			"      this.errorMessage = errorMessage;",
			"    }",
			"",
			"    public static ValidationResponse asValid(String ignored) {",
			"      return new ValidationResponse(true, null);",
			"    }",
			"",
			"    public static ValidationResponse asInvalid(String errorMessage) {",
			"      return new ValidationResponse(false, errorMessage);",
			"    }",
			"",
			"    public boolean valid() {",
			"      return this.valid;",
			"    }",
			"",
			"    public String errorMessage() {",
			"      return this.errorMessage;",
			"    }",
			"  }",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/server/McpAsyncServerExchange.java": strings.Join([]string{
			"package io.modelcontextprotocol.server;",
			"",
			"public class McpAsyncServerExchange {",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/server/McpInitRequestHandler.java": strings.Join([]string{
			"package io.modelcontextprotocol.server;",
			"",
			"import io.modelcontextprotocol.spec.McpSchema;",
			"import reactor.core.publisher.Mono;",
			"",
			"public interface McpInitRequestHandler {",
			"  Mono<McpSchema.InitializeResult> handle(McpSchema.InitializeRequest request);",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/server/McpNotificationHandler.java": strings.Join([]string{
			"package io.modelcontextprotocol.server;",
			"",
			"import reactor.core.publisher.Mono;",
			"",
			"public interface McpNotificationHandler {",
			"  Mono<Void> handle(McpAsyncServerExchange exchange, Object params);",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/server/McpRequestHandler.java": strings.Join([]string{
			"package io.modelcontextprotocol.server;",
			"",
			"import reactor.core.publisher.Mono;",
			"",
			"public interface McpRequestHandler<T> {",
			"  Mono<T> handle(McpAsyncServerExchange exchange, Object params);",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/spec/McpServerTransport.java": strings.Join([]string{
			"package io.modelcontextprotocol.spec;",
			"",
			"public interface McpServerTransport {",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/spec/McpServerTransportProvider.java": strings.Join([]string{
			"package io.modelcontextprotocol.spec;",
			"",
			"import java.util.List;",
			"",
			"public interface McpServerTransportProvider {",
			"  default List<String> protocolVersions() {",
			"    return List.of(\"2024-11-05\");",
			"  }",
			"",
			"  void setSessionFactory(McpServerSession.Factory sessionFactory);",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/spec/McpServerSession.java": strings.Join([]string{
			"package io.modelcontextprotocol.spec;",
			"",
			"import java.time.Duration;",
			"import java.util.Map;",
			"",
			"import io.modelcontextprotocol.server.McpInitRequestHandler;",
			"import io.modelcontextprotocol.server.McpNotificationHandler;",
			"import io.modelcontextprotocol.server.McpRequestHandler;",
			"",
			"public class McpServerSession {",
			"  public McpServerSession(String id, Duration requestTimeout, McpServerTransport transport, McpInitRequestHandler initHandler, Map<String, McpRequestHandler<?>> requestHandlers, Map<String, McpNotificationHandler> notificationHandlers) {",
			"  }",
			"",
			"  @FunctionalInterface",
			"  public interface Factory {",
			"    McpServerSession create(McpServerTransport sessionTransport);",
			"  }",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/spec/McpError.java": strings.Join([]string{
			"package io.modelcontextprotocol.spec;",
			"",
			"public class McpError extends RuntimeException {",
			"  public McpError(String message) {",
			"    super(message);",
			"  }",
			"",
			"  public static Builder builder(int code) {",
			"    return new Builder(code);",
			"  }",
			"",
			"  public static final class Builder {",
			"    private final int code;",
			"    private String message;",
			"",
			"    private Builder(int code) {",
			"      this.code = code;",
			"    }",
			"",
			"    public Builder message(String message) {",
			"      this.message = message;",
			"      return this;",
			"    }",
			"",
			"    public McpError build() {",
			"      return new McpError(this.message == null ? String.valueOf(this.code) : this.message);",
			"    }",
			"  }",
			"}",
			"",
		}, "\n"),
		"io/modelcontextprotocol/spec/McpSchema.java": strings.Join([]string{
			"package io.modelcontextprotocol.spec;",
			"",
			"import java.util.List;",
			"import java.util.Map;",
			"",
			"public final class McpSchema {",
			"  private McpSchema() {",
			"  }",
			"",
			"  public static final String METHOD_TOOLS_LIST = \"tools/list\";",
			"  public static final String METHOD_TOOLS_CALL = \"tools/call\";",
			"",
			"  public static final class ErrorCodes {",
			"    public static final int INVALID_PARAMS = -32602;",
			"  }",
			"",
			"  public static final class InitializeRequest {",
			"  }",
			"",
			"  public static final class InitializeResult {",
			"    public InitializeResult(String protocolVersion, ServerCapabilities capabilities, Implementation serverInfo, String instructions) {",
			"    }",
			"  }",
			"",
			"  public static final class Implementation {",
			"    public Implementation(String name, String title, String version) {",
			"    }",
			"  }",
			"",
			"  public static final class ServerCapabilities {",
			"    public ServerCapabilities(Object completions, Map<String, Object> experimental, Object logging, Object prompts, Object resources, ToolCapabilities tools) {",
			"    }",
			"",
			"    public static final class ToolCapabilities {",
			"      public ToolCapabilities(Boolean listChanged) {",
			"      }",
			"    }",
			"  }",
			"",
			"  public static final class CallToolRequest {",
			"    private final String name;",
			"    private final Map<String, Object> arguments;",
			"",
			"    public CallToolRequest() {",
			"      this(null, null);",
			"    }",
			"",
			"    public CallToolRequest(String name, Map<String, Object> arguments) {",
			"      this.name = name;",
			"      this.arguments = arguments;",
			"    }",
			"",
			"    public String name() {",
			"      return this.name;",
			"    }",
			"",
			"    public Map<String, Object> arguments() {",
			"      return this.arguments;",
			"    }",
			"  }",
			"",
			"  public static final class CallToolResult {",
			"    public static Builder builder() {",
			"      return new Builder();",
			"    }",
			"",
			"    public static final class Builder {",
			"      public Builder addTextContent(String text) {",
			"        return this;",
			"      }",
			"",
			"      public Builder structuredContent(Object structuredContent) {",
			"        return this;",
			"      }",
			"",
			"      public Builder isError(Boolean isError) {",
			"        return this;",
			"      }",
			"",
			"      public CallToolResult build() {",
			"        return new CallToolResult();",
			"      }",
			"    }",
			"  }",
			"}",
			"",
		}, "\n"),
		"reactor/core/publisher/Mono.java": strings.Join([]string{
			"package reactor.core.publisher;",
			"",
			"public class Mono<T> {",
			"  public static <T> Mono<T> just(T value) {",
			"    return new Mono<>();",
			"  }",
			"",
			"  public static <T> Mono<T> error(Throwable error) {",
			"    return new Mono<>();",
			"  }",
			"}",
			"",
		}, "\n"),
	}

	for relativePath, content := range stubs {
		writeJavaTestSource(t, root, relativePath, []byte(content))
	}
}

func diffBytes(want []byte, got []byte) string {
	return fmt.Sprintf("--- want\n+++ got\n%s", firstDiffLine(string(want), string(got)))
}

func firstDiffLine(want string, got string) string {
	wantLines := strings.Split(want, "\n")
	gotLines := strings.Split(got, "\n")
	limit := len(wantLines)
	if len(gotLines) < limit {
		limit = len(gotLines)
	}
	for i := 0; i < limit; i++ {
		if wantLines[i] != gotLines[i] {
			return fmt.Sprintf("@@ line %d @@\n- %s\n+ %s\n", i+1, wantLines[i], gotLines[i])
		}
	}
	if len(wantLines) != len(gotLines) {
		return fmt.Sprintf("@@ line count @@\n- %d lines\n+ %d lines\n", len(wantLines), len(gotLines))
	}
	return "(contents differ, but no differing line was isolated)"
}
