package codegen

import (
	"encoding/json"
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func renderTypeScriptFile(plugin *protogen.Plugin, model FileModel) error {
	if model.Options.Language != LanguageTypeScript {
		return fmt.Errorf("typescript renderer requires lang=typescript, got %q", model.Options.Language)
	}

	filename := typescriptOutputPathForProtoPath(model.ProtoPath)
	generated := plugin.NewGeneratedFile(filename, "")

	generated.P("// Code generated by protoc-gen-mcp. DO NOT EDIT.")
	generated.P("// source: ", model.ProtoPath)
	generated.P()

	for serviceIndex, service := range model.Services {
		for methodIndex, method := range service.Methods {
			if serviceIndex > 0 || methodIndex > 0 {
				generated.P()
			}
			schemaConst := typescriptSchemaConst(service.ProtoName, method.ProtoName)
			generated.P("export const ", schemaConst, "_INPUT_SCHEMA_JSON = ", typescriptStringLiteral(method.InputSchemaJSON), ";")
			generated.P("export const ", schemaConst, "_OUTPUT_SCHEMA_JSON = ", typescriptStringLiteral(method.OutputSchemaJSON), ";")
		}
	}

	return nil
}

func typescriptOutputPathForProtoPath(protoPath string) string {
	return typescriptGeneratedFilenamePrefixForProtoPath(protoPath) + "_mcp.ts"
}

func typescriptGeneratedFilenamePrefixForProtoPath(protoPath string) string {
	prefix := strings.TrimSuffix(protoPath, path.Ext(protoPath))
	parts := strings.Split(prefix, "/")
	for i, part := range parts {
		parts[i] = strings.ReplaceAll(part, "-", "_")
	}
	return strings.Join(parts, "/")
}

func typescriptSchemaConst(service, method string) string {
	return toUpperSnakeCase(service) + "_" + toUpperSnakeCase(method)
}

func typescriptStringLiteral(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("marshal TypeScript string literal: %v", err))
	}
	return string(encoded)
}
