package codegen

import "google.golang.org/protobuf/compiler/protogen"

func renderPythonRuntime(generated *protogen.GeneratedFile) {
	generated.P("@dataclass(frozen=True)")
	generated.P("class _RegisteredTool:")
	generated.P("    name: str")
	generated.P("    title: str")
	generated.P("    description: str")
	generated.P("    input_schema_json: str")
	generated.P("    output_schema_json: str")
	generated.P("    request_type: type[Any]")
	generated.P("    response_type: type[Any]")
	generated.P("    from_pb: Any")
	generated.P("    to_pb: Any")
	generated.P("    handler: Any")
	generated.P("    annotations: dict[str, Any] | None")
	generated.P("    icons: list[dict[str, Any]] | None")
	generated.P("    execution: dict[str, Any] | None = None")
	generated.P()
	generated.P("class _ServerToolRegistry:")
	generated.P("    def __init__(self, server: mcp.server.lowlevel.Server) -> None:")
	generated.P("        self.server = server")
	generated.P("        self.tools: dict[str, _RegisteredTool] = {}")
	generated.P("        self.reserved_tool_names = _get_reserved_tool_names(server)")
	generated.P("        self.handlers_installed = False")
	generated.P("        self.previous_list_tools: Any | None = None")
	generated.P("        self.previous_call_tool: Any | None = None")
	generated.P()
	generated.P("    def add_tool(self, tool: _RegisteredTool) -> None:")
	generated.P("        if tool.name in self.reserved_tool_names:")
	generated.P("            raise ValueError(f\"duplicate tool registration: {tool.name}\")")
	generated.P("        self.tools[tool.name] = tool")
	generated.P("        self.reserved_tool_names.add(tool.name)")
	generated.P()
	generated.P("    def list_tools(self) -> list[mcp.types.Tool]:")
	generated.P("        return [_build_tool(tool) for tool in self.tools.values()]")
	generated.P()
	generated.P("    async def call_tool(self, name: str, arguments: dict[str, Any] | None, context: ToolRequestContext | None = None) -> mcp.types.CallToolResult:")
	generated.P("        return await _dispatch_call(self, name, arguments or {}, context)")
	generated.P()
	generated.P("_SERVER_REGISTRIES: weakref.WeakKeyDictionary[mcp.server.lowlevel.Server, _ServerToolRegistry] = weakref.WeakKeyDictionary()")
	generated.P()
	generated.P("def _load_schema(schema_json: str) -> dict[str, Any]:")
	generated.P("    return json.loads(schema_json)")
	generated.P()
	generated.P("def _protojson_to_message(arguments: dict[str, Any], message: Any) -> Any:")
	generated.P("    json_format.ParseDict(arguments, message)")
	generated.P("    return message")
	generated.P()
	generated.P("def _normalize_tool_segment(segment: str | None) -> str:")
	generated.P("    if segment is None:")
	generated.P("        return \"\"")
	generated.P("    parts = [part for part in segment.strip().replace(\".\", \"_\").split(\"_\") if part]")
	generated.P("    return \"_\".join(parts)")
	generated.P()
	generated.P("def _normalize_namespace(namespace: str | None, default: str) -> str:")
	generated.P("    if namespace is None:")
	generated.P("        namespace = default")
	generated.P("    return _normalize_tool_segment(namespace)")
	generated.P()
	generated.P("def _tool_name(namespace: str, method_name: str) -> str:")
	generated.P("    namespace = _normalize_tool_segment(namespace)")
	generated.P("    method_name = _normalize_tool_segment(method_name)")
	generated.P("    if namespace == '':")
	generated.P("        return method_name")
	generated.P("    if method_name == '':")
	generated.P("        return namespace")
	generated.P("    return f\"{namespace}_{method_name}\"")
	generated.P()
	generated.P("def _get_registry(server: mcp.server.lowlevel.Server) -> _ServerToolRegistry:")
	generated.P("    registry = _SERVER_REGISTRIES.get(server)")
	generated.P("    if registry is None:")
	generated.P("        registry = _ServerToolRegistry(server)")
	generated.P("        _SERVER_REGISTRIES[server] = registry")
	generated.P("    return registry")
	generated.P()
	generated.P("_RESERVED_TOOL_NAMES_ATTR = \"_protoc_gen_mcp_reserved_tool_names\"")
	generated.P()
	generated.P("def _get_reserved_tool_names(server: mcp.server.lowlevel.Server) -> set[str]:")
	generated.P("    reserved = getattr(server, _RESERVED_TOOL_NAMES_ATTR, None)")
	generated.P("    if reserved is None:")
	generated.P("        reserved = set()")
	generated.P("        setattr(server, _RESERVED_TOOL_NAMES_ATTR, reserved)")
	generated.P("    return reserved")
	generated.P()
	generated.P("def _build_list_tools_request(request: Any) -> mcp.types.ListToolsRequest:")
	generated.P("    if isinstance(request, mcp.types.ListToolsRequest):")
	generated.P("        return request")
	generated.P("    return mcp.types.ListToolsRequest()")
	generated.P()
	generated.P("def _merge_tools(previous: list[mcp.types.Tool], current: list[mcp.types.Tool]) -> list[mcp.types.Tool]:")
	generated.P("    merged: list[mcp.types.Tool] = []")
	generated.P("    names: set[str] = set()")
	generated.P("    for tool in previous:")
	generated.P("        if tool.name in names:")
	generated.P("            raise ValueError(f\"duplicate tool registration: {tool.name}\")")
	generated.P("        names.add(tool.name)")
	generated.P("        merged.append(tool)")
	generated.P("    for tool in current:")
	generated.P("        if tool.name in names:")
	generated.P("            raise ValueError(f\"duplicate tool registration: {tool.name}\")")
	generated.P("        names.add(tool.name)")
	generated.P("        merged.append(tool)")
	generated.P("    return merged")
	generated.P()
	generated.P("def _install_server_handlers(server: mcp.server.lowlevel.Server) -> _ServerToolRegistry:")
	generated.P("    registry = _get_registry(server)")
	generated.P("    if registry.handlers_installed:")
	generated.P("        return registry")
	generated.P("    registry.previous_list_tools = server.request_handlers.get(mcp.types.ListToolsRequest)")
	generated.P("    registry.previous_call_tool = server.request_handlers.get(mcp.types.CallToolRequest)")
	generated.P()
	generated.P("    async def _list_tools(request: Any) -> mcp.types.ServerResult:")
	generated.P("        current = _SERVER_REGISTRIES.get(server)")
	generated.P("        list_request = _build_list_tools_request(request)")
	generated.P("        previous_tools: list[mcp.types.Tool] = []")
	generated.P("        meta: dict[str, Any] | None = None")
	generated.P("        if current is not None:")
	generated.P("            if current.previous_list_tools is not None:")
	generated.P("                previous_result = await current.previous_list_tools(list_request)")
	generated.P("                if not isinstance(previous_result.root, mcp.types.ListToolsResult):")
	generated.P("                    return previous_result")
	generated.P("                if getattr(list_request.params, \"cursor\", None) is not None:")
	generated.P("                    raise ValueError(\"cannot compose protoc-gen-mcp tools with paginated tools/list handlers\")")
	generated.P("                if previous_result.root.nextCursor is not None:")
	generated.P("                    raise ValueError(\"cannot compose protoc-gen-mcp tools with paginated tools/list handlers\")")
	generated.P("                meta = getattr(previous_result.root, \"meta\", None)")
	generated.P("                previous_tools = list(previous_result.root.tools)")
	generated.P("        current_tools = [] if current is None else current.list_tools()")
	generated.P("        tools = _merge_tools(previous_tools, current_tools)")
	generated.P("        server._tool_cache.clear()")
	generated.P("        for tool in tools:")
	generated.P("            server._tool_cache[tool.name] = tool")
	generated.P("        return mcp.types.ServerResult(mcp.types.ListToolsResult(tools=tools, _meta=meta))")
	generated.P()
	generated.P("    async def _call_tool(request: mcp.types.CallToolRequest) -> mcp.types.ServerResult:")
	generated.P("        current = _SERVER_REGISTRIES.get(server)")
	generated.P("        if current is None:")
	generated.P("            return mcp.types.ServerResult(_tool_error_result(\"tool registry is not installed\"))")
	generated.P("        if request.params.name not in current.tools:")
	generated.P("            if current.previous_call_tool is not None:")
	generated.P("                return await current.previous_call_tool(request)")
	generated.P("            _invalid_params_error(request.params.name, \"unknown tool\")")
	generated.P("        if current.previous_call_tool is not None:")
	generated.P("            await server.request_handlers[mcp.types.ListToolsRequest](mcp.types.ListToolsRequest())")
	generated.P("        result = await current.call_tool(request.params.name, request.params.arguments or {}, server.request_context.session)")
	generated.P("        return mcp.types.ServerResult(result)")
	generated.P()
	generated.P("    server.request_handlers[mcp.types.ListToolsRequest] = _list_tools")
	generated.P("    server.request_handlers[mcp.types.CallToolRequest] = _call_tool")
	generated.P()
	generated.P("    registry.handlers_installed = True")
	generated.P("    return registry")
	generated.P()
	generated.P("def _tool_annotations(raw: dict[str, Any] | None) -> mcp.types.ToolAnnotations | None:")
	generated.P("    if raw is None:")
	generated.P("        return None")
	generated.P("    return mcp.types.ToolAnnotations(**raw)")
	generated.P()
	generated.P("def _tool_execution(raw: dict[str, Any] | None) -> mcp.types.ToolExecution | None:")
	generated.P("    if raw is None:")
	generated.P("        return None")
	generated.P("    return mcp.types.ToolExecution(**raw)")
	generated.P()
	generated.P("def _tool_error_result(message: str) -> mcp.types.CallToolResult:")
	generated.P("    return mcp.types.CallToolResult(")
	generated.P("        content=[mcp.types.TextContent(type=\"text\", text=message)],")
	generated.P("        isError=True,")
	generated.P("    )")
	generated.P()
	generated.P("def _invalid_params_error(tool_name: str, error: Any) -> mcp.shared.exceptions.McpError:")
	generated.P("    raise mcp.shared.exceptions.McpError(")
	generated.P("        mcp.types.ErrorData(")
	generated.P("            code=mcp.types.INVALID_PARAMS,")
	generated.P("            message=f\"invalid arguments for tool {tool_name!r}: {error}\",")
	generated.P("        )")
	generated.P("    )")
	generated.P()
	generated.P("def _build_tool(tool: _RegisteredTool) -> Any:")
	generated.P("    return mcp.types.Tool(")
	generated.P("        name=tool.name,")
	generated.P("        title=tool.title,")
	generated.P("        description=tool.description,")
	generated.P("        inputSchema=_load_schema(tool.input_schema_json),")
	generated.P("        outputSchema=_load_schema(tool.output_schema_json),")
	generated.P("        annotations=_tool_annotations(tool.annotations),")
	generated.P("        icons=tool.icons,")
	generated.P("        execution=_tool_execution(tool.execution),")
	generated.P("    )")
	generated.P()
	generated.P("async def _maybe_await(result: Any) -> Any:")
	generated.P("    if inspect.isawaitable(result):")
	generated.P("        return await result")
	generated.P("    return result")
	generated.P()
	generated.P("def _message_to_json(message: Any) -> str:")
	generated.P("    kwargs = {\"preserving_proto_field_name\": False}")
	generated.P("    try:")
	generated.P("        return json_format.MessageToJson(message, always_print_fields_with_no_presence=True, **kwargs)")
	generated.P("    except TypeError:")
	generated.P("        return json_format.MessageToJson(message, including_default_value_fields=True, **kwargs)")
	generated.P()
	generated.P("async def _dispatch_call(registry: _ServerToolRegistry, name: str, arguments: dict[str, Any], context: ToolRequestContext | None) -> mcp.types.CallToolResult:")
	generated.P("    tool = registry.tools.get(name)")
	generated.P("    if tool is None:")
	generated.P("        _invalid_params_error(name, \"unknown tool\")")
	generated.P("    try:")
	generated.P("        jsonschema.validate(arguments, _load_schema(tool.input_schema_json))")
	generated.P("    except jsonschema.ValidationError as error:")
	generated.P("        _invalid_params_error(name, error)")
	generated.P("    try:")
	generated.P("        request_pb = _protojson_to_message(arguments, tool.request_type())")
	generated.P("        request_dc = tool.from_pb(request_pb)")
	generated.P("    except Exception as error:")
	generated.P("        _invalid_params_error(name, error)")
	generated.P("    try:")
	generated.P("        response_dc = await _maybe_await(tool.handler(context, request_dc))")
	generated.P("    except Exception as error:")
	generated.P("        return _tool_error_result(str(error))")
	generated.P("    try:")
	generated.P("        if response_dc is None:")
	generated.P("            response_pb = tool.response_type()")
	generated.P("        else:")
	generated.P("            response_pb = tool.to_pb(response_dc)")
	generated.P("        payload = json.loads(_message_to_json(response_pb))")
	generated.P("    except Exception as error:")
	generated.P("        raise RuntimeError(f\"mcpruntime: marshal output for tool {name!r}: {error}\") from error")
	generated.P("    text = json.dumps(payload, separators=(\",\", \":\"), ensure_ascii=False)")
	generated.P("    content = [mcp.types.TextContent(type=\"text\", text=text)]")
	generated.P("    try:")
	generated.P("        jsonschema.validate(payload, _load_schema(tool.output_schema_json))")
	generated.P("    except jsonschema.ValidationError as error:")
	generated.P("        raise RuntimeError(f\"mcpruntime: validate output for tool {name!r}: {error}\") from error")
	generated.P("    return mcp.types.CallToolResult(content=content, structuredContent=payload)")
	generated.P()
}
