package codegen

import (
	"fmt"
	"sort"
	"strings"

	mcpoptionsv1 "github.com/easyp-tech/protoc-gen-mcp/mcp/options/v1"
	"google.golang.org/protobuf/compiler/protogen"
)

func renderPythonFile(plugin *protogen.Plugin, model FileModel) error {
	info, err := newPythonRenderInfo(plugin, model)
	if err != nil {
		return err
	}
	return renderPythonFileForHandler(plugin, model, model.Options.PythonHandler, pythonOutputPath(info.file))
}

func renderPythonFileForHandler(plugin *protogen.Plugin, model FileModel, handler PythonHandler, filename string) error {
	info, err := newPythonRenderInfo(plugin, model)
	if err != nil {
		return err
	}
	protobufHandlerMode := handler == PythonHandlerProtobuf

	generated := plugin.NewGeneratedFile(filename, "")

	generated.P("# Code generated by protoc-gen-mcp. DO NOT EDIT.")
	generated.P("# source: ", model.ProtoPath)
	generated.P("from __future__ import annotations")
	generated.P()
	generated.P("import enum")
	generated.P("import inspect")
	generated.P("import json")
	generated.P("import weakref")
	generated.P("from dataclasses import dataclass, field")
	generated.P("from typing import Any, Awaitable, Protocol, TypeAlias")
	generated.P()
	generated.P("import jsonschema")
	generated.P("import mcp.server.lowlevel")
	generated.P("import mcp.server.session")
	generated.P("import mcp.shared.exceptions")
	generated.P("import mcp.types")
	generated.P("from google.protobuf import any_pb2, duration_pb2, empty_pb2, field_mask_pb2, json_format, struct_pb2, timestamp_pb2, wrappers_pb2")
	if !protobufHandlerMode {
		for _, moduleRef := range info.publicImportsForModel(model) {
			if moduleRef.Package == "" {
				if moduleRef.Alias == moduleRef.Module {
					generated.P("import ", moduleRef.Module)
				} else {
					generated.P("import ", moduleRef.Module, " as ", moduleRef.Alias)
				}
				continue
			}
			if moduleRef.Alias == moduleRef.Module {
				generated.P("from ", moduleRef.Package, " import ", moduleRef.Module)
			} else {
				generated.P("from ", moduleRef.Package, " import ", moduleRef.Module, " as ", moduleRef.Alias)
			}
		}
	}
	for _, moduleRef := range info.protobufImportsForModel(model) {
		if moduleRef.IsCurrent {
			generated.P("try:")
			generated.P("    from . import ", moduleRef.Module)
			generated.P("except ImportError:")
			if moduleRef.Alias == moduleRef.Module {
				generated.P("    import ", moduleRef.Module)
			} else {
				generated.P("    import ", moduleRef.Module, " as ", moduleRef.Alias)
			}
			continue
		}
		if moduleRef.Package == "" {
			if moduleRef.Alias == moduleRef.Module {
				generated.P("import ", moduleRef.Module)
			} else {
				generated.P("import ", moduleRef.Module, " as ", moduleRef.Alias)
			}
			continue
		}
		if moduleRef.Alias == moduleRef.Module {
			generated.P("from ", moduleRef.Package, " import ", moduleRef.Module)
		} else {
			generated.P("from ", moduleRef.Package, " import ", moduleRef.Module, " as ", moduleRef.Alias)
		}
	}
	generated.P()
	generated.P("ToolRequestContext = mcp.server.session.ServerSession")
	generated.P()
	if !protobufHandlerMode {
		if err := renderPythonPublicTypes(generated, info, model); err != nil {
			return err
		}
	}
	renderPythonRuntime(generated, protobufHandlerMode)
	if !protobufHandlerMode {
		if err := renderPythonMappers(generated, info, model); err != nil {
			return err
		}
	}

	for serviceIdx, service := range model.Services {
		generated.P("class ", pythonProtocolName(service.ProtoName), "(Protocol):")
		for _, method := range service.Methods {
			inputType, outputType, err := info.pythonHandlerMethodTypeRefs(method, protobufHandlerMode)
			if err != nil {
				return err
			}
			generated.P("    def ", pythonMethodName(method.ProtoName), "(self, ctx: ToolRequestContext, req: ", inputType, ") -> ", outputType, " | Awaitable[", outputType, "]:")
			generated.P("        ...")
		}
		generated.P()

		registerName := pythonRegisterName(service.ProtoName)
		protocolName := pythonProtocolName(service.ProtoName)
		generated.P("def ", registerName, "(server: mcp.server.lowlevel.Server, impl: ", protocolName, ", *, namespace: str | None = None) -> None:")
		generated.P("    if impl is None:")
		generated.P("        raise ValueError(\"", registerName, ": impl is nil\")")
		generated.P("    registry = _install_server_handlers(server)")
		generated.P("    resolved_namespace = _normalize_namespace(namespace, ", quote(service.Namespace), ")")
		for _, method := range service.Methods {
			inputType, err := info.pythonProtobufTypeRef(method.Input)
			if err != nil {
				return err
			}
			outputType, err := info.pythonProtobufTypeRef(method.Output)
			if err != nil {
				return err
			}
			inputMapper := "_identity"
			outputMapper := "_identity"
			if !protobufHandlerMode {
				inputMapper, err = info.pythonMapperHelperForMethodType("from_pb", method.Input)
				if err != nil {
					return err
				}
				outputMapper, err = info.pythonMapperHelperForMethodType("to_pb", method.Output)
				if err != nil {
					return err
				}
			}
			schemaName := pythonSchemaConst(service.ProtoName, method.Name)
			generated.P("    registry.add_tool(_RegisteredTool(")
			generated.P("        name=_tool_name(resolved_namespace, ", quote(method.Name), "),")
			generated.P("        title=", quote(method.Title), ",")
			generated.P("        description=", quote(method.Description), ",")
			generated.P("        input_schema_json=", schemaName, "_INPUT_SCHEMA_JSON,")
			generated.P("        output_schema_json=", schemaName, "_OUTPUT_SCHEMA_JSON,")
			generated.P("        request_type=", inputType, ",")
			generated.P("        response_type=", outputType, ",")
			generated.P("        from_pb=", inputMapper, ",")
			generated.P("        to_pb=", outputMapper, ",")
			generated.P("        handler=impl.", pythonMethodName(method.ProtoName), ",")
			generated.P("        annotations=", pythonAnnotations(method.Annotations), ",")
			generated.P("        icons=", pythonIcons(method.Icons), ",")
			generated.P("        execution=", pythonTaskSupport(method.TaskSupport), ",")
			generated.P("    ))")
		}
		generated.P()

		for methodIdx, method := range service.Methods {
			schemaName := pythonSchemaConst(service.ProtoName, method.Name)
			generated.P(schemaName, "_INPUT_SCHEMA_JSON = ", quote(method.InputSchemaJSON))
			generated.P()
			generated.P(schemaName, "_OUTPUT_SCHEMA_JSON = ", quote(method.OutputSchemaJSON))
			if methodIdx < len(service.Methods)-1 || serviceIdx < len(model.Services)-1 {
				generated.P()
			}
		}
	}

	if len(model.Prompts) > 0 {
		renderPythonPrompts(generated, model)
	}

	if len(model.Resources) > 0 {
		renderPythonResources(generated, model)
	}

	return nil
}

func renderPythonResources(generated *protogen.GeneratedFile, model FileModel) {
	fileBase := pythonFileBaseName(model.ProtoPath)
	protocolName := pythonExportedIdentifier(fileBase) + "ResourceHandler"
	registerName := "register_" + toSnakeCase(fileBase) + "_resources"

	generated.P()
	generated.P()
	generated.P("class ", protocolName, "(Protocol):")
	generated.P("    \"\"\"Handler protocol for MCP resources in ", model.ProtoPath, ".\"\"\"")
	for _, resource := range model.Resources {
		methodName := toSnakeCase(resource.ProtoName)
		if resource.IsTemplate {
			generated.P("    async def list_", methodName, "s(self) -> list[mcp.types.Resource]:")
			generated.P("        ...")
			paramList := "self"
			for _, param := range resource.Params {
				paramList += ", " + param.Name + ": str"
			}
			generated.P("    async def read_", methodName, "(", paramList, ") -> Any:")
			generated.P("        ...")
		} else {
			generated.P("    async def read_", methodName, "(self) -> Any:")
			generated.P("        ...")
		}
	}
	generated.P()

	generated.P()
	generated.P("def ", registerName, "(")
	generated.P("    server: mcp.server.lowlevel.Server,")
	generated.P("    impl: ", protocolName, ",")
	generated.P("    *,")
	generated.P("    namespace: str | None = None,")
	generated.P(") -> None:")
	generated.P("    \"\"\"Registers MCP resources for ", fileBase, ".\"\"\"")
	generated.P("    if impl is None:")
	generated.P("        raise ValueError(\"", registerName, ": impl is nil\")")
	generated.P("    # TODO: full Python resource registration using server.read_resource decorator")
	generated.P("    raise NotImplementedError(\"MCP Resources for Python are not yet fully supported\")")
	generated.P()
}

func renderPythonPrompts(generated *protogen.GeneratedFile, model FileModel) {
	// Build a file-level handler name from the proto file name.
	fileBase := pythonFileBaseName(model.ProtoPath)
	protocolName := pythonExportedIdentifier(fileBase) + "PromptHandler"
	registerName := "register_" + toSnakeCase(fileBase) + "_prompts"

	generated.P()
	generated.P("def _prompt_name(namespace: str | None, prompt_name: str) -> str:")
	generated.P("    if namespace is None or _normalize_tool_segment(namespace) == '':")
	generated.P("        return _normalize_tool_segment(prompt_name)")
	generated.P("    return f\"{_normalize_tool_segment(namespace)}_{_normalize_tool_segment(prompt_name)}\"")
	generated.P()
	generated.P("class ", protocolName, "(Protocol):")
	for _, prompt := range model.Prompts {
		generated.P("    async def ", pythonMethodName(prompt.ProtoName), "(self, arguments: dict[str, str]) -> mcp.types.GetPromptResult:")
		generated.P("        ...")
	}
	generated.P()

	generated.P("def ", registerName, "(server: mcp.server.lowlevel.Server, impl: ", protocolName, ", *, namespace: str | None = None) -> None:")
	generated.P("    if impl is None:")
	generated.P("        raise ValueError(\"", registerName, ": impl is nil\")")
	for _, prompt := range model.Prompts {
		generated.P("    @server.add_prompt(")
		generated.P("        name=_prompt_name(namespace, ", quote(prompt.Name), "),")
		if prompt.Title != "" {
			generated.P("        title=", quote(prompt.Title), ",")
		}
		if prompt.Description != "" {
			generated.P("        description=", quote(prompt.Description), ",")
		}
		generated.P("        arguments=[")
		for _, arg := range prompt.Arguments {
			generated.P("            mcp.types.PromptArgument(name=", quote(arg.Name), ", description=", quote(arg.Description), ", required=", pythonBool(arg.Required), "),")
		}
		generated.P("        ],")
		generated.P("    )")
		generated.P("    async def ", pythonPromptHandlerFuncName(prompt.ProtoName), "(arguments: dict[str, str] | None = None) -> mcp.types.GetPromptResult:")
		generated.P("        return await impl.", pythonMethodName(prompt.ProtoName), "(arguments or {})")
	}
	generated.P()
}

func pythonPromptHandlerFuncName(protoName string) string {
	return "_handle_prompt_" + toSnakeCase(protoName)
}

func pythonFileBaseName(protoPath string) string {
	base := strings.TrimSuffix(protoPath, ".proto")
	if idx := strings.LastIndex(base, "/"); idx >= 0 {
		base = base[idx+1:]
	}
	return base
}

func (p pythonRenderInfo) pythonHandlerMethodTypeRefs(method MethodModel, protobufHandlerMode bool) (string, string, error) {
	if protobufHandlerMode {
		inputType, err := p.pythonProtobufTypeRef(method.Input)
		if err != nil {
			return "", "", err
		}
		outputType, err := p.pythonProtobufTypeRef(method.Output)
		if err != nil {
			return "", "", err
		}
		return inputType, outputType, nil
	}

	inputType, err := p.pythonPublicMethodTypeRef(method.Input)
	if err != nil {
		return "", "", err
	}
	outputType, err := p.pythonPublicMethodTypeRef(method.Output)
	if err != nil {
		return "", "", err
	}
	return inputType, outputType, nil
}

type pythonRenderInfo struct {
	file        *protogen.File
	messages    map[string]*protogen.Message
	publicTypes map[string]PythonType
	modules     map[string]pythonModuleRef
}

type pythonModuleRef struct {
	Package   string
	Module    string
	Alias     string
	IsCurrent bool
}

func newPythonRenderInfo(plugin *protogen.Plugin, model FileModel) (pythonRenderInfo, error) {
	file := plugin.FilesByPath[model.ProtoPath]
	if file == nil {
		return pythonRenderInfo{}, fmt.Errorf("generated file %q not found in plugin", model.ProtoPath)
	}

	info := pythonRenderInfo{
		file:        file,
		messages:    map[string]*protogen.Message{},
		publicTypes: map[string]PythonType{},
		modules:     map[string]pythonModuleRef{},
	}
	for _, current := range plugin.Files {
		pkg, module := pythonImportParts(current)
		info.modules[current.Desc.Path()] = pythonModuleRef{
			Package:   pkg,
			Module:    module,
			Alias:     pythonModuleAlias(current, current.Desc.Path() == file.Desc.Path()),
			IsCurrent: current.Desc.Path() == file.Desc.Path(),
		}
		indexPythonMessages(info.messages, current.Messages)
	}
	if model.PythonTypes != nil {
		for _, typ := range model.PythonTypes.Types {
			info.publicTypes[typ.ProtoFullName] = typ
		}
	}

	return info, nil
}

func indexPythonMessages(index map[string]*protogen.Message, messages []*protogen.Message) {
	for _, message := range messages {
		index[string(message.Desc.FullName())] = message
		indexPythonMessages(index, message.Messages)
	}
}

func (p pythonRenderInfo) pythonProtobufTypeRef(ref TypeRef) (string, error) {
	message := p.messages[ref.ProtoFullName]
	if message == nil {
		return "", fmt.Errorf("message %q not found during Python render", ref.ProtoFullName)
	}

	messageFilePath := message.Desc.ParentFile().Path()
	moduleRef, ok := p.modules[messageFilePath]
	if !ok {
		return "", fmt.Errorf("module for message %q not found during Python render", ref.ProtoFullName)
	}
	return moduleRef.Alias + "." + pythonMessageRef(message), nil
}

func (p pythonRenderInfo) pythonPublicMethodTypeRef(ref TypeRef) (string, error) {
	typ, ok := p.publicTypes[ref.ProtoFullName]
	if !ok {
		return "", fmt.Errorf("public python type %q not found during render", ref.ProtoFullName)
	}
	return p.pythonPublicTypeRef(typ.typeRef()), nil
}

func (p pythonRenderInfo) pythonMapperHelperForMethodType(prefix string, ref TypeRef) (string, error) {
	typ, ok := p.publicTypes[ref.ProtoFullName]
	if !ok {
		return "", fmt.Errorf("public python type %q not found during mapper lookup", ref.ProtoFullName)
	}
	return pythonMapperHelperName(prefix, typ), nil
}

func (p pythonRenderInfo) protobufImportsForModel(model FileModel) []pythonModuleRef {
	refs := map[string]pythonModuleRef{}
	if model.PythonTypes != nil {
		for _, typ := range model.PythonTypes.Types {
			if typ.Kind != PythonTypeKindMessage || typ.WellKnownType != PythonWellKnownTypeNone {
				continue
			}
			refs[typ.Owner.ProtoPath] = p.modules[typ.Owner.ProtoPath]
		}
	}
	for _, service := range model.Services {
		for _, method := range service.Methods {
			if message := p.messages[method.Input.ProtoFullName]; message != nil {
				messageFilePath := message.Desc.ParentFile().Path()
				refs[messageFilePath] = p.modules[messageFilePath]
			}
			if message := p.messages[method.Output.ProtoFullName]; message != nil {
				messageFilePath := message.Desc.ParentFile().Path()
				refs[messageFilePath] = p.modules[messageFilePath]
			}
		}
	}

	ordered := make([]pythonModuleRef, 0, len(refs))
	for _, ref := range refs {
		ordered = append(ordered, ref)
	}
	sort.Slice(ordered, func(i, j int) bool {
		left := ordered[i].Package + "." + ordered[i].Module
		right := ordered[j].Package + "." + ordered[j].Module
		return left < right
	})
	return ordered
}

func (p pythonRenderInfo) publicImportsForModel(model FileModel) []pythonModuleRef {
	if model.PythonTypes == nil {
		return nil
	}

	referencedProtoPaths := p.publicImportProtoPaths(*model.PythonTypes)
	ordered := make([]pythonModuleRef, 0, len(model.PythonTypes.Imports))
	for _, ref := range model.PythonTypes.Imports {
		if _, ok := referencedProtoPaths[ref.ProtoPath]; !ok {
			continue
		}
		modulePath := ref.PublicModule.ModulePath
		lastDot := strings.LastIndex(modulePath, ".")
		moduleRef := pythonModuleRef{
			Alias:  ref.PublicModule.ModuleAlias,
			Module: ref.PublicModule.ModuleBasename,
		}
		if lastDot != -1 {
			moduleRef.Package = modulePath[:lastDot]
		}
		ordered = append(ordered, moduleRef)
	}
	sort.Slice(ordered, func(i, j int) bool {
		left := ordered[i].Package + "." + ordered[i].Module
		right := ordered[j].Package + "." + ordered[j].Module
		return left < right
	})
	return ordered
}

func (p pythonRenderInfo) publicImportProtoPaths(graph PythonTypeGraph) map[string]struct{} {
	refs := make(map[string]struct{})
	for _, typ := range graph.Types {
		if typ.Owner.IsCurrentFile || typ.WellKnownType != PythonWellKnownTypeNone {
			continue
		}
		refs[typ.Owner.ProtoPath] = struct{}{}
	}
	return refs
}

func pythonMessageRef(message *protogen.Message) string {
	fullName := string(message.Desc.FullName())
	pkg := string(message.Desc.ParentFile().Package())
	if pkg != "" {
		fullName = strings.TrimPrefix(fullName, pkg+".")
	}
	return fullName
}

func pythonAnnotations(ann *mcpoptionsv1.ToolAnnotations) string {
	if ann == nil {
		return "None"
	}

	fields := make([]string, 0, 4)
	if ann.ReadOnlyHint {
		fields = append(fields, fmt.Sprintf("%q: %s", "readOnlyHint", pythonBool(ann.ReadOnlyHint)))
	}
	if ann.DestructiveHint != nil {
		fields = append(fields, fmt.Sprintf("%q: %s", "destructiveHint", pythonBool(*ann.DestructiveHint)))
	}
	if ann.IdempotentHint {
		fields = append(fields, fmt.Sprintf("%q: %s", "idempotentHint", pythonBool(ann.IdempotentHint)))
	}
	if ann.OpenWorldHint != nil {
		fields = append(fields, fmt.Sprintf("%q: %s", "openWorldHint", pythonBool(*ann.OpenWorldHint)))
	}
	if ann.Title != "" {
		fields = append(fields, fmt.Sprintf("%q: %q", "title", ann.Title))
	}
	if len(fields) == 0 {
		return "{}"
	}
	return "{" + strings.Join(fields, ", ") + "}"
}

func pythonBool(value bool) string {
	if value {
		return "True"
	}
	return "False"
}

func pythonIcons(icons []*mcpoptionsv1.Icon) string {
	if len(icons) == 0 {
		return "None"
	}

	items := make([]string, 0, len(icons))
	for _, icon := range icons {
		sizes := "[]"
		if len(icon.GetSizes()) > 0 {
			quoted := make([]string, 0, len(icon.GetSizes()))
			for _, size := range icon.GetSizes() {
				quoted = append(quoted, fmt.Sprintf("%q", size))
			}
			sizes = "[" + strings.Join(quoted, ", ") + "]"
		}
		items = append(items, fmt.Sprintf("{%q: %q, %q: %q, %q: %s, %q: %q}",
			"src", icon.GetSrc(),
			"mimeType", icon.GetMimeType(),
			"sizes", sizes,
			"theme", icon.GetTheme()))
	}

	return "[" + strings.Join(items, ", ") + "]"
}

func pythonTaskSupport(taskSupport mcpoptionsv1.TaskSupport) string {
	switch taskSupport {
	case mcpoptionsv1.TaskSupport_TASK_SUPPORT_OPTIONAL:
		return `{"taskSupport": "optional"}`
	case mcpoptionsv1.TaskSupport_TASK_SUPPORT_REQUIRED:
		return `{"taskSupport": "required"}`
	default:
		return "None"
	}
}
