package codegen

import (
	"fmt"
	"path"
	"sort"
	"strings"
	"unicode"

	mcpoptionsv1 "github.com/easyp-tech/protoc-gen-mcp/mcp/options/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func renderJavaFile(plugin *protogen.Plugin, model JVMFileModel) error {
	if model.Language != LanguageJava {
		return fmt.Errorf("java renderer requires lang=java, got %q", model.Language)
	}
	if err := validateJavaMetadata(model); err != nil {
		return err
	}

	info, err := newJavaRenderInfo(plugin, model)
	if err != nil {
		return err
	}

	filePackage, err := resolveJVMFilePackage(info.file)
	if err != nil {
		return err
	}

	imports := map[string]bool{}
	for _, service := range model.Services {
		for _, method := range service.Methods {
			if _, err := info.javaTypeExpr(method.Input, imports, filePackage.Package); err != nil {
				return err
			}
			if _, err := info.javaTypeExpr(method.Output, imports, filePackage.Package); err != nil {
				return err
			}
		}
	}
	descriptorAccessors, err := collectJavaDescriptorAccessors(info.file.Desc, filePackage.Package)
	if err != nil {
		return err
	}
	for _, accessor := range descriptorAccessors {
		if accessor.ImportPath != "" {
			imports[accessor.ImportPath] = true
		}
	}

	className := javaSidecarClassName(model.GeneratedFilenamePrefix)
	filename := javaSidecarOutputPath(model.GeneratedFilenamePrefix)
	generated := plugin.NewGeneratedFile(filename, "")

	generated.P("// Code generated by protoc-gen-mcp. DO NOT EDIT.")
	generated.P("// source: ", model.ProtoPath)
	generated.P()
	if filePackage.Package != "" {
		generated.P("package ", filePackage.Package, ";")
		generated.P()
	}

	javaImports := []string{
		"com.google.protobuf.Message",
		"com.google.protobuf.util.JsonFormat",
		"com.google.protobuf.Descriptors",
		"io.modelcontextprotocol.json.McpJsonDefaults",
		"io.modelcontextprotocol.json.McpJsonMapper",
		"io.modelcontextprotocol.json.TypeRef",
		"io.modelcontextprotocol.json.schema.JsonSchemaValidator",
		"io.modelcontextprotocol.server.McpAsyncServerExchange",
		"io.modelcontextprotocol.server.McpInitRequestHandler",
		"io.modelcontextprotocol.server.McpNotificationHandler",
		"io.modelcontextprotocol.server.McpRequestHandler",
		"io.modelcontextprotocol.spec.McpError",
		"io.modelcontextprotocol.spec.McpSchema",
		"io.modelcontextprotocol.spec.McpServerSession",
		"io.modelcontextprotocol.spec.McpServerTransport",
		"io.modelcontextprotocol.spec.McpServerTransportProvider",
		"java.io.IOException",
		"java.time.Duration",
		"java.util.ArrayList",
		"java.util.Collection",
		"java.util.Collections",
		"java.util.HashSet",
		"java.util.LinkedHashMap",
		"java.util.List",
		"java.util.Map",
		"java.util.Set",
		"java.util.UUID",
		"java.util.WeakHashMap",
		"java.util.function.Supplier",
		"reactor.core.publisher.Mono",
	}
	for importPath := range imports {
		javaImports = append(javaImports, importPath)
	}
	sort.Strings(javaImports)
	for _, importPath := range javaImports {
		generated.P("import ", importPath, ";")
	}
	generated.P()

	generated.P("public final class ", className, " {")
	generated.P("  private ", className, "() {")
	generated.P("  }")
	generated.P()

	for serviceIdx, service := range model.Services {
		generated.P("  public interface ", service.HandlerName, " {")
		for _, method := range service.Methods {
			inputType, err := info.javaTypeExpr(method.Input, imports, filePackage.Package)
			if err != nil {
				return err
			}
			outputType, err := info.javaTypeExpr(method.Output, imports, filePackage.Package)
			if err != nil {
				return err
			}
			generated.P("    ", outputType, " ", method.MethodName, "(McpAsyncServerExchange ctx, ", inputType, " request) throws Exception;")
		}
		generated.P("  }")
		generated.P()

		generated.P("  public static void ", service.RegisterName, "(")
		generated.P("      McpServerTransportProvider transportProvider,")
		generated.P("      ", service.HandlerName, " impl,")
		generated.P("      String namespace) {")
		generated.P("    if (transportProvider == null) {")
		generated.P("      throw new IllegalArgumentException(\"transportProvider must not be null\");")
		generated.P("    }")
		generated.P("    if (impl == null) {")
		generated.P("      throw new IllegalArgumentException(\"impl must not be null\");")
		generated.P("    }")
		generated.P("    ServerToolRegistry registry = registryFor(transportProvider);")
		generated.P("    String resolvedNamespace = normalizeNamespace(namespace, ", quote(service.Namespace), ");")
		for _, method := range service.Methods {
			inputType, err := info.javaTypeExpr(method.Input, imports, filePackage.Package)
			if err != nil {
				return err
			}
			outputType, err := info.javaTypeExpr(method.Output, imports, filePackage.Package)
			if err != nil {
				return err
			}
			icons, err := javaIcons(method.Icons)
			if err != nil {
				return err
			}
			generated.P("    registry.registerTool(")
			generated.P("        new RegisteredTool(")
			generated.P("            toolName(resolvedNamespace, ", quote(method.ToolName), "),")
			generated.P("            ", javaNullableString(method.Title), ",")
			generated.P("            ", javaNullableString(method.Description), ",")
			generated.P("            ", method.SchemaConst, "_INPUT_SCHEMA_JSON,")
			generated.P("            ", method.SchemaConst, "_OUTPUT_SCHEMA_JSON,")
			generated.P("            () -> ", inputType, ".newBuilder(),")
			generated.P("            () -> ", outputType, ".newBuilder(),")
			generated.P("            (ctx, request) -> impl.", method.MethodName, "(ctx, (", inputType, ") request),")
			generated.P("            ", javaAnnotations(method.Annotations), ",")
			generated.P("            ", icons, ",")
			generated.P("            ", javaTaskSupport(method.TaskSupport), ")")
			generated.P("    );")
		}
		generated.P("    installSessionFactory(transportProvider, registry);")
		generated.P("  }")
		generated.P()

		for methodIdx, method := range service.Methods {
			generated.P("  private static final String ", method.SchemaConst, "_INPUT_SCHEMA_JSON = ", quote(method.InputSchemaJSON), ";")
			generated.P()
			generated.P("  private static final String ", method.SchemaConst, "_OUTPUT_SCHEMA_JSON = ", quote(method.OutputSchemaJSON), ";")
			if methodIdx < len(service.Methods)-1 || serviceIdx < len(model.Services)-1 {
				generated.P()
			}
		}
	}

	if len(model.Prompts) > 0 {
		renderJavaPrompts(generated, model)
	}

	if len(model.Resources) > 0 {
		renderJavaResources(generated, model)
	}

	if len(model.Services) > 0 || len(model.Prompts) > 0 || len(model.Resources) > 0 {
		generated.P()
	}
	renderJavaRuntime(generated, descriptorAccessors)
	generated.P("}")

	return nil
}

func renderJavaResources(generated *protogen.GeneratedFile, model JVMFileModel) {
	fileBase := jvmFileBaseName(model.ProtoPath)
	interfaceName := jvmExportedIdentifier(fileBase) + "ResourceHandler"
	registerName := "register" + jvmExportedIdentifier(fileBase) + "Resources"

	generated.P()
	generated.P("    public interface ", interfaceName, " {")
	for _, resource := range model.Resources {
		methodName := jvmMethodName(resource.ProtoName)
		if resource.IsTemplate {
			generated.P("        java.util.List<Object> list", resource.ProtoName, "s();")
			paramList := ""
			for i, param := range resource.Params {
				if i > 0 {
					paramList += ", "
				}
				paramList += "String " + param.Name
			}
			generated.P("        Object read", resource.ProtoName, "(", paramList, ");")
		} else {
			generated.P("        Object ", methodName, "();")
		}
	}
	generated.P("    }")
	generated.P()

	generated.P("    public static void ", registerName, "(")
	generated.P("            io.modelcontextprotocol.sdk.server.McpServerTransportProvider transportProvider,")
	generated.P("            ", interfaceName, " impl,")
	generated.P("            String namespace) {")
	generated.P("        // TODO: full Java resource registration")
	generated.P("        throw new UnsupportedOperationException(\"MCP Resources for Java are not yet fully supported\");")
	generated.P("    }")
}

func renderJavaPrompts(generated *protogen.GeneratedFile, model JVMFileModel) {
	fileBase := jvmFileBaseName(model.ProtoPath)
	interfaceName := jvmExportedIdentifier(fileBase) + "PromptHandler"
	registerName := "register" + jvmExportedIdentifier(fileBase) + "Prompts"

	generated.P()
	generated.P("  public interface ", interfaceName, " {")
	for _, prompt := range model.Prompts {
		generated.P("    List<Map<String, Object>> ", jvmMethodName(prompt.ProtoName), "(Map<String, String> arguments) throws Exception;")
	}
	generated.P("  }")
	generated.P()

	generated.P("  public static void ", registerName, "(")
	generated.P("      McpServerTransportProvider transportProvider,")
	generated.P("      ", interfaceName, " impl,")
	generated.P("      String namespace) {")
	generated.P("    if (transportProvider == null) {")
	generated.P("      throw new IllegalArgumentException(\"transportProvider must not be null\");")
	generated.P("    }")
	generated.P("    if (impl == null) {")
	generated.P("      throw new IllegalArgumentException(\"impl must not be null\");")
	generated.P("    }")
	for _, prompt := range model.Prompts {
		generated.P("    // Register prompt: ", prompt.Name)
		generated.P("    {")
		generated.P("      String resolvedName = promptName(namespace, ", quote(prompt.Name), ");")
		generated.P("      Map<String, Object> promptMap = new LinkedHashMap<>();")
		generated.P("      promptMap.put(\"name\", resolvedName);")
		if prompt.Title != "" {
			generated.P("      promptMap.put(\"title\", ", quote(prompt.Title), ");")
		}
		if prompt.Description != "" {
			generated.P("      promptMap.put(\"description\", ", quote(prompt.Description), ");")
		}
		generated.P("      List<Map<String, Object>> argsSpec = new ArrayList<>();")
		// Build required arg names list for validation.
		var requiredArgNames []string
		for _, arg := range prompt.Arguments {
			generated.P("      {")
			generated.P("        Map<String, Object> argMap = new LinkedHashMap<>();")
			generated.P("        argMap.put(\"name\", ", quote(arg.Name), ");")
			generated.P("        argMap.put(\"description\", ", quote(arg.Description), ");")
			generated.P("        argMap.put(\"required\", ", javaBoolLiteral(arg.Required), ");")
			generated.P("        argsSpec.add(argMap);")
			generated.P("      }")
			if arg.Required {
				requiredArgNames = append(requiredArgNames, arg.Name)
			}
		}
		generated.P("      promptMap.put(\"arguments\", argsSpec);")
		// Build required-names array literal.
		reqArrayLiteral := "new String[0]"
		if len(requiredArgNames) > 0 {
			items := make([]string, 0, len(requiredArgNames))
			for _, name := range requiredArgNames {
				items = append(items, quote(name))
			}
			reqArrayLiteral = "new String[]{" + strings.Join(items, ", ") + "}"
		}
		generated.P("      String[] requiredArgs = ", reqArrayLiteral, ";")
		generated.P("      registerPrompt(transportProvider, resolvedName, promptMap, requiredArgs, (args) -> impl.", jvmMethodName(prompt.ProtoName), "(args));")
		generated.P("    }")
	}
	generated.P("  }")
	generated.P()
	generated.P("  private static String promptName(String namespace, String promptName) {")
	generated.P("    String normalizedNamespace = normalizeToolSegment(namespace != null ? namespace : \"\");")
	generated.P("    String normalizedPromptName = normalizeToolSegment(promptName);")
	generated.P("    if (normalizedNamespace.isEmpty()) {")
	generated.P("      return normalizedPromptName;")
	generated.P("    }")
	generated.P("    if (normalizedPromptName.isEmpty()) {")
	generated.P("      return normalizedNamespace;")
	generated.P("    }")
	generated.P("    return normalizedNamespace + \"_\" + normalizedPromptName;")
	generated.P("  }")
	generated.P()
	generated.P("  @FunctionalInterface")
	generated.P("  private interface PromptInvoker {")
	generated.P("    List<Map<String, Object>> handle(Map<String, String> arguments) throws Exception;")
	generated.P("  }")
	generated.P()
	generated.P("  private static final class RegisteredPrompt {")
	generated.P("    private final String name;")
	generated.P("    private final Map<String, Object> metadata;")
	generated.P("    private final String[] requiredArgs;")
	generated.P("    private final PromptInvoker handler;")
	generated.P()
	generated.P("    private RegisteredPrompt(String name, Map<String, Object> metadata, String[] requiredArgs, PromptInvoker handler) {")
	generated.P("      this.name = name;")
	generated.P("      this.metadata = metadata;")
	generated.P("      this.requiredArgs = requiredArgs;")
	generated.P("      this.handler = handler;")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static final Map<McpServerTransportProvider, List<RegisteredPrompt>> PROMPT_REGISTRIES =")
	generated.P("      Collections.synchronizedMap(new WeakHashMap<>());")
	generated.P()
	generated.P("  private static void registerPrompt(")
	generated.P("      McpServerTransportProvider transportProvider,")
	generated.P("      String name,")
	generated.P("      Map<String, Object> metadata,")
	generated.P("      String[] requiredArgs,")
	generated.P("      PromptInvoker handler) {")
	generated.P("    synchronized (PROMPT_REGISTRIES) {")
	generated.P("      List<RegisteredPrompt> prompts = PROMPT_REGISTRIES.computeIfAbsent(transportProvider, (k) -> new ArrayList<>());")
	generated.P("      prompts.add(new RegisteredPrompt(name, metadata, requiredArgs, handler));")
	generated.P("    }")
	generated.P("  }")
}

func javaBoolLiteral(value bool) string {
	if value {
		return "Boolean.TRUE"
	}
	return "Boolean.FALSE"
}

type javaDescriptorAccessor struct {
	ImportPath string
	Expr       string
}

type javaRenderInfo struct {
	file     *protogen.File
	messages map[string]*protogen.Message
	enums    map[string]*protogen.Enum
}

func newJavaRenderInfo(plugin *protogen.Plugin, model JVMFileModel) (javaRenderInfo, error) {
	file := plugin.FilesByPath[model.ProtoPath]
	if file == nil {
		return javaRenderInfo{}, fmt.Errorf("generated file %q not found in plugin", model.ProtoPath)
	}

	info := javaRenderInfo{
		file:     file,
		messages: map[string]*protogen.Message{},
		enums:    map[string]*protogen.Enum{},
	}
	for _, current := range plugin.Files {
		indexJavaMessages(info.messages, current.Messages)
		indexJavaEnums(info.enums, current.Enums)
		indexJavaEnumsInMessages(info.enums, current.Messages)
	}

	return info, nil
}

func indexJavaMessages(index map[string]*protogen.Message, messages []*protogen.Message) {
	for _, message := range messages {
		index[string(message.Desc.FullName())] = message
		indexJavaMessages(index, message.Messages)
	}
}

func indexJavaEnums(index map[string]*protogen.Enum, enums []*protogen.Enum) {
	for _, enum := range enums {
		index[string(enum.Desc.FullName())] = enum
	}
}

func indexJavaEnumsInMessages(index map[string]*protogen.Enum, messages []*protogen.Message) {
	for _, message := range messages {
		indexJavaEnums(index, message.Enums)
		indexJavaEnumsInMessages(index, message.Messages)
	}
}

func (j javaRenderInfo) javaTypeExpr(ref JVMTypeRef, imports map[string]bool, currentPackage string) (string, error) {
	var (
		resolved jvmResolvedTypeRef
		err      error
	)

	if ref.IsEnum {
		enum := j.enums[ref.ProtoFullName]
		if enum == nil {
			return "", fmt.Errorf("enum %q not found during Java render", ref.ProtoFullName)
		}
		resolved, err = resolveJVMEnumTypeRef(enum, j.file.Desc.Path())
		if err != nil {
			return "", err
		}
	} else {
		message := j.messages[ref.ProtoFullName]
		if message == nil {
			return "", fmt.Errorf("message %q not found during Java render", ref.ProtoFullName)
		}
		resolved, err = resolveJVMMessageTypeRef(message, j.file.Desc.Path())
		if err != nil {
			return "", err
		}
	}

	if resolved.ImportPath != "" && javaImportPackage(resolved.ImportPath) != currentPackage {
		imports[resolved.ImportPath] = true
	}
	return resolved.Expr, nil
}

func renderJavaRuntime(generated *protogen.GeneratedFile, descriptorAccessors []javaDescriptorAccessor) {
	generated.P("  private static final Duration DEFAULT_REQUEST_TIMEOUT = Duration.ofMinutes(5);")
	generated.P("  private static final TypeRef<Map<String, Object>> MAP_TYPE_REF = new TypeRef<>() {")
	generated.P("  };")
	generated.P("  private static final McpJsonMapper JSON_MAPPER = McpJsonDefaults.getMapper();")
	generated.P("  private static final JsonSchemaValidator JSON_SCHEMA_VALIDATOR = McpJsonDefaults.getSchemaValidator();")
	generated.P("  private static final JsonFormat.TypeRegistry PROTO_TYPE_REGISTRY = buildTypeRegistry();")
	generated.P("  private static final Map<McpServerTransportProvider, ServerToolRegistry> SERVER_REGISTRIES = Collections.synchronizedMap(new WeakHashMap<>());")
	generated.P()
	generated.P("  private static JsonFormat.TypeRegistry buildTypeRegistry() {")
	generated.P("    JsonFormat.TypeRegistry.Builder builder = JsonFormat.TypeRegistry.newBuilder();")
	generated.P("    Set<String> seenFiles = new HashSet<>();")
	for _, accessor := range descriptorAccessors {
		generated.P("    registerFileTypes(builder, seenFiles, ", accessor.Expr, ");")
	}
	generated.P("    return builder.build();")
	generated.P("  }")
	generated.P()
	generated.P("  private static void registerFileTypes(")
	generated.P("      JsonFormat.TypeRegistry.Builder builder,")
	generated.P("      Set<String> seenFiles,")
	generated.P("      Descriptors.FileDescriptor file) {")
	generated.P("    if (!seenFiles.add(file.getFullName())) {")
	generated.P("      return;")
	generated.P("    }")
	generated.P("    for (Descriptors.Descriptor descriptor : file.getMessageTypes()) {")
	generated.P("      registerMessageType(builder, descriptor);")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static void registerMessageType(")
	generated.P("      JsonFormat.TypeRegistry.Builder builder,")
	generated.P("      Descriptors.Descriptor descriptor) {")
	generated.P("    builder.add(descriptor);")
	generated.P("    for (Descriptors.Descriptor nested : descriptor.getNestedTypes()) {")
	generated.P("      registerMessageType(builder, nested);")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  @FunctionalInterface")
	generated.P("  private interface ToolInvoker {")
	generated.P("    Message handle(McpAsyncServerExchange exchange, Message request) throws Exception;")
	generated.P("  }")
	generated.P()
	generated.P("  private static final class RegisteredTool {")
	generated.P("    private final String name;")
	generated.P("    private final String title;")
	generated.P("    private final String description;")
	generated.P("    private final Map<String, Object> inputSchema;")
	generated.P("    private final Map<String, Object> outputSchema;")
	generated.P("    private final Supplier<Message.Builder> requestBuilder;")
	generated.P("    private final Supplier<Message.Builder> responseBuilder;")
	generated.P("    private final ToolInvoker handler;")
	generated.P("    private final Map<String, Object> annotations;")
	generated.P("    private final List<Map<String, Object>> icons;")
	generated.P("    private final Map<String, Object> execution;")
	generated.P()
	generated.P("    private RegisteredTool(")
	generated.P("        String name,")
	generated.P("        String title,")
	generated.P("        String description,")
	generated.P("        String inputSchemaJson,")
	generated.P("        String outputSchemaJson,")
	generated.P("        Supplier<Message.Builder> requestBuilder,")
	generated.P("        Supplier<Message.Builder> responseBuilder,")
	generated.P("        ToolInvoker handler,")
	generated.P("        Map<String, Object> annotations,")
	generated.P("        List<Map<String, Object>> icons,")
	generated.P("        Map<String, Object> execution) {")
	generated.P("      this.name = name;")
	generated.P("      this.title = title;")
	generated.P("      this.description = description;")
	generated.P("      this.inputSchema = loadSchema(inputSchemaJson);")
	generated.P("      this.outputSchema = loadSchema(outputSchemaJson);")
	generated.P("      this.requestBuilder = requestBuilder;")
	generated.P("      this.responseBuilder = responseBuilder;")
	generated.P("      this.handler = handler;")
	generated.P("      this.annotations = annotations;")
	generated.P("      this.icons = icons;")
	generated.P("      this.execution = execution;")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static final class ServerToolRegistry {")
	generated.P("    private final LinkedHashMap<String, RegisteredTool> toolsByName = new LinkedHashMap<>();")
	generated.P("    private boolean sessionFactoryInstalled;")
	generated.P()
	generated.P("    private synchronized void registerTool(RegisteredTool tool) {")
	generated.P("      if (this.toolsByName.containsKey(tool.name)) {")
	generated.P("        throw new IllegalStateException(\"duplicate tool registration: \" + tool.name);")
	generated.P("      }")
	generated.P("      this.toolsByName.put(tool.name, tool);")
	generated.P("    }")
	generated.P()
	generated.P("    private synchronized RegisteredTool tool(String name) {")
	generated.P("      return this.toolsByName.get(name);")
	generated.P("    }")
	generated.P()
	generated.P("    private synchronized Collection<RegisteredTool> allTools() {")
	generated.P("      return new ArrayList<>(this.toolsByName.values());")
	generated.P("    }")
	generated.P()
	generated.P("    private synchronized boolean markSessionFactoryInstalled() {")
	generated.P("      if (this.sessionFactoryInstalled) {")
	generated.P("        return false;")
	generated.P("      }")
	generated.P("      this.sessionFactoryInstalled = true;")
	generated.P("      return true;")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static ServerToolRegistry registryFor(McpServerTransportProvider transportProvider) {")
	generated.P("    synchronized (SERVER_REGISTRIES) {")
	generated.P("      ServerToolRegistry registry = SERVER_REGISTRIES.get(transportProvider);")
	generated.P("      if (registry == null) {")
	generated.P("        registry = new ServerToolRegistry();")
	generated.P("        SERVER_REGISTRIES.put(transportProvider, registry);")
	generated.P("      }")
	generated.P("      return registry;")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static void installSessionFactory(McpServerTransportProvider transportProvider, ServerToolRegistry registry) {")
	generated.P("    if (!registry.markSessionFactoryInstalled()) {")
	generated.P("      return;")
	generated.P("    }")
	generated.P("    transportProvider.setSessionFactory(")
	generated.P("        sessionTransport -> new McpServerSession(")
	generated.P("            UUID.randomUUID().toString(),")
	generated.P("            DEFAULT_REQUEST_TIMEOUT,")
	generated.P("            sessionTransport,")
	generated.P("            initializeHandler(transportProvider),")
	generated.P("            requestHandlers(registry),")
	generated.P("            notificationHandlers()));")
	generated.P("  }")
	generated.P()
	generated.P("  private static McpInitRequestHandler initializeHandler(McpServerTransportProvider transportProvider) {")
	generated.P("    return request -> Mono.just(")
	generated.P("        new McpSchema.InitializeResult(")
	generated.P("            resolveProtocolVersion(transportProvider),")
	generated.P("            new McpSchema.ServerCapabilities(")
	generated.P("                null,")
	generated.P("                null,")
	generated.P("                null,")
	generated.P("                null,")
	generated.P("                null,")
	generated.P("                new McpSchema.ServerCapabilities.ToolCapabilities(false)),")
	generated.P("            new McpSchema.Implementation(\"protoc-gen-mcp\", \"protoc-gen-mcp\", \"dev\"),")
	generated.P("            null));")
	generated.P("  }")
	generated.P()
	generated.P("  private static String resolveProtocolVersion(McpServerTransportProvider transportProvider) {")
	generated.P("    List<String> protocolVersions = transportProvider.protocolVersions();")
	generated.P("    if (protocolVersions == null || protocolVersions.isEmpty()) {")
	generated.P("      return \"2024-11-05\";")
	generated.P("    }")
	generated.P("    return protocolVersions.get(0);")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, McpRequestHandler<?>> requestHandlers(ServerToolRegistry registry) {")
	generated.P("    Map<String, McpRequestHandler<?>> requestHandlers = new LinkedHashMap<>();")
	generated.P("    requestHandlers.put(McpSchema.METHOD_TOOLS_LIST, (exchange, params) -> Mono.just(listRegisteredTools(registry)));")
	generated.P("    requestHandlers.put(McpSchema.METHOD_TOOLS_CALL, (exchange, params) -> dispatchToolCall(registry, exchange, params));")
	generated.P("    return requestHandlers;")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, McpNotificationHandler> notificationHandlers() {")
	generated.P("    return new LinkedHashMap<>();")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, Object> listRegisteredTools(ServerToolRegistry registry) {")
	generated.P("    Map<String, Object> result = new LinkedHashMap<>();")
	generated.P("    List<Map<String, Object>> tools = new ArrayList<>();")
	generated.P("    for (RegisteredTool tool : registry.allTools()) {")
	generated.P("      tools.add(toolAsProtocolMap(tool));")
	generated.P("    }")
	generated.P("    result.put(\"tools\", tools);")
	generated.P("    return result;")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, Object> toolAsProtocolMap(RegisteredTool tool) {")
	generated.P("    Map<String, Object> protocol = new LinkedHashMap<>();")
	generated.P("    protocol.put(\"name\", tool.name);")
	generated.P("    putIfNotNull(protocol, \"title\", tool.title);")
	generated.P("    putIfNotNull(protocol, \"description\", tool.description);")
	generated.P("    protocol.put(\"inputSchema\", tool.inputSchema);")
	generated.P("    protocol.put(\"outputSchema\", tool.outputSchema);")
	generated.P("    putIfNotNull(protocol, \"annotations\", tool.annotations);")
	generated.P("    if (!tool.icons.isEmpty()) {")
	generated.P("      protocol.put(\"icons\", tool.icons);")
	generated.P("    }")
	generated.P("    putIfNotNull(protocol, \"execution\", tool.execution);")
	generated.P("    return protocol;")
	generated.P("  }")
	generated.P()
	generated.P("  private static void putIfNotNull(Map<String, Object> target, String key, Object value) {")
	generated.P("    if (value != null) {")
	generated.P("      target.put(key, value);")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, Object> toolAnnotationsMapOrNull(")
	generated.P("      String title,")
	generated.P("      Boolean readOnlyHint,")
	generated.P("      Boolean destructiveHint,")
	generated.P("      Boolean idempotentHint,")
	generated.P("      Boolean openWorldHint) {")
	generated.P("    if (title == null && readOnlyHint == null && destructiveHint == null && idempotentHint == null && openWorldHint == null) {")
	generated.P("      return null;")
	generated.P("    }")
	generated.P("    Map<String, Object> annotations = new LinkedHashMap<>();")
	generated.P("    putIfNotNull(annotations, \"title\", title);")
	generated.P("    putIfNotNull(annotations, \"readOnlyHint\", readOnlyHint);")
	generated.P("    putIfNotNull(annotations, \"destructiveHint\", destructiveHint);")
	generated.P("    putIfNotNull(annotations, \"idempotentHint\", idempotentHint);")
	generated.P("    putIfNotNull(annotations, \"openWorldHint\", openWorldHint);")
	generated.P("    return annotations.isEmpty() ? null : annotations;")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, Object> toolExecutionMapOrNull(String taskSupport) {")
	generated.P("    if (taskSupport == null || taskSupport.isBlank()) {")
	generated.P("      return null;")
	generated.P("    }")
	generated.P("    Map<String, Object> execution = new LinkedHashMap<>();")
	generated.P("    execution.put(\"taskSupport\", taskSupport);")
	generated.P("    return execution;")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, Object> iconMap(String src, String mimeType, List<String> sizes, String theme) {")
	generated.P("    Map<String, Object> icon = new LinkedHashMap<>();")
	generated.P("    icon.put(\"src\", src);")
	generated.P("    putIfNotNull(icon, \"mimeType\", mimeType);")
	generated.P("    if (sizes != null && !sizes.isEmpty()) {")
	generated.P("      icon.put(\"sizes\", sizes);")
	generated.P("    }")
	generated.P("    putIfNotNull(icon, \"theme\", iconThemeOrError(theme));")
	generated.P("    return icon;")
	generated.P("  }")
	generated.P()
	generated.P("  private static String iconThemeOrError(String rawTheme) {")
	generated.P("    if (rawTheme == null || rawTheme.isBlank()) {")
	generated.P("      return null;")
	generated.P("    }")
	generated.P("    if (\"light\".equals(rawTheme) || \"dark\".equals(rawTheme)) {")
	generated.P("      return rawTheme;")
	generated.P("    }")
	generated.P("    throw new IllegalArgumentException(\"unsupported Java icon theme \\\"\" + rawTheme + \"\\\"\");")
	generated.P("  }")
	generated.P()
	generated.P("  private static Map<String, Object> loadSchema(String rawSchemaJson) {")
	generated.P("    try {")
	generated.P("      return JSON_MAPPER.readValue(rawSchemaJson, MAP_TYPE_REF);")
	generated.P("    }")
	generated.P("    catch (IOException error) {")
	generated.P("      throw new IllegalArgumentException(\"Invalid schema: \" + rawSchemaJson, error);")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static void validateJson(Map<String, Object> schema, Object payload) {")
	generated.P("    JsonSchemaValidator.ValidationResponse validation = JSON_SCHEMA_VALIDATOR.validate(schema, payload);")
	generated.P("    if (!validation.valid()) {")
	generated.P("      throw new IllegalArgumentException(validation.errorMessage());")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static Message parseProtoJson(String argumentsJson, Message.Builder builder) {")
	generated.P("    try {")
	generated.P("      JsonFormat.parser().usingTypeRegistry(PROTO_TYPE_REGISTRY).merge(argumentsJson, builder);")
	generated.P("      return builder.build();")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      throw new IllegalArgumentException(error.getMessage(), error);")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static String marshalProtoJson(Message responseMessage) {")
	generated.P("    try {")
	generated.P("      return JsonFormat.printer()")
	generated.P("          .usingTypeRegistry(PROTO_TYPE_REGISTRY)")
	generated.P("          .alwaysPrintFieldsWithNoPresence()")
	generated.P("          .omittingInsignificantWhitespace()")
	generated.P("          .print(responseMessage);")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      throw new IllegalStateException(error.getMessage(), error);")
	generated.P("    }")
	generated.P("  }")
	generated.P()
	generated.P("  private static Mono<Object> dispatchToolCall(")
	generated.P("      ServerToolRegistry registry,")
	generated.P("      McpAsyncServerExchange exchange,")
	generated.P("      Object params) {")
	generated.P("    final McpSchema.CallToolRequest request;")
	generated.P("    try {")
	generated.P("      request = JSON_MAPPER.convertValue(params, McpSchema.CallToolRequest.class);")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      return Mono.error(invalidParams(\"<unknown>\", error));")
	generated.P("    }")
	generated.P()
	generated.P("    String requestedToolName = request.name() == null ? \"\" : request.name();")
	generated.P("    RegisteredTool tool = registry.tool(requestedToolName);")
	generated.P("    if (tool == null) {")
	generated.P("      return Mono.error(invalidParams(requestedToolName, \"unknown tool\"));")
	generated.P("    }")
	generated.P()
	generated.P("    Map<String, Object> arguments = request.arguments() == null ? new LinkedHashMap<>() : request.arguments();")
	generated.P("    try {")
	generated.P("      validateJson(tool.inputSchema, arguments);")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      return Mono.error(invalidParams(requestedToolName, error));")
	generated.P("    }")
	generated.P()
	generated.P("    final Message requestMessage;")
	generated.P("    try {")
	generated.P("      requestMessage = parseProtoJson(JSON_MAPPER.writeValueAsString(arguments), tool.requestBuilder.get());")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      return Mono.error(invalidParams(requestedToolName, error));")
	generated.P("    }")
	generated.P()
	generated.P("    final Message responseMessage;")
	generated.P("    try {")
	generated.P("      Message handled = tool.handler.handle(exchange, requestMessage);")
	generated.P("      responseMessage = handled == null ? tool.responseBuilder.get().build() : handled;")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      String message = error.getMessage() == null ? error.toString() : error.getMessage();")
	generated.P("      return Mono.just(toolErrorResult(message));")
	generated.P("    }")
	generated.P()
	generated.P("    final String payload;")
	generated.P("    try {")
	generated.P("      payload = marshalProtoJson(responseMessage);")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      throw new IllegalStateException(\"mcpruntime: marshal output for tool '\" + requestedToolName + \"': \" + error.getMessage(), error);")
	generated.P("    }")
	generated.P()
	generated.P("    final Map<String, Object> structuredContent;")
	generated.P("    try {")
	generated.P("      structuredContent = JSON_MAPPER.readValue(payload, MAP_TYPE_REF);")
	generated.P("    }")
	generated.P("    catch (IOException error) {")
	generated.P("      throw new IllegalStateException(\"mcpruntime: parse output for tool '\" + requestedToolName + \"': \" + error.getMessage(), error);")
	generated.P("    }")
	generated.P()
	generated.P("    try {")
	generated.P("      validateJson(tool.outputSchema, structuredContent);")
	generated.P("    }")
	generated.P("    catch (Exception error) {")
	generated.P("      throw new IllegalStateException(\"mcpruntime: validate output for tool '\" + requestedToolName + \"': \" + error.getMessage(), error);")
	generated.P("    }")
	generated.P()
	generated.P("    return Mono.just(")
	generated.P("        McpSchema.CallToolResult.builder()")
	generated.P("            .addTextContent(payload)")
	generated.P("            .structuredContent(structuredContent)")
	generated.P("            .build());")
	generated.P("  }")
	generated.P()
	generated.P("  private static McpSchema.CallToolResult toolErrorResult(String message) {")
	generated.P("    return McpSchema.CallToolResult.builder()")
	generated.P("        .addTextContent(message)")
	generated.P("        .isError(true)")
	generated.P("        .build();")
	generated.P("  }")
	generated.P()
	generated.P("  private static McpError invalidParams(String toolName, Object error) {")
	generated.P("    return McpError.builder(McpSchema.ErrorCodes.INVALID_PARAMS)")
	generated.P("        .message(\"invalid arguments for tool '\" + toolName + \"': \" + String.valueOf(error))")
	generated.P("        .build();")
	generated.P("  }")
	generated.P()
	generated.P("  private static String normalizeNamespace(String namespace, String defaultNamespace) {")
	generated.P("    return normalizeToolSegment(namespace == null ? defaultNamespace : namespace);")
	generated.P("  }")
	generated.P()
	generated.P("  private static String normalizeToolSegment(String segment) {")
	generated.P("    if (segment == null) {")
	generated.P("      return \"\";")
	generated.P("    }")
	generated.P("    String trimmed = segment.trim().replace('.', '_');")
	generated.P("    if (trimmed.isEmpty()) {")
	generated.P("      return \"\";")
	generated.P("    }")
	generated.P("    String[] parts = trimmed.split(\"_\");")
	generated.P("    StringBuilder normalized = new StringBuilder();")
	generated.P("    for (String part : parts) {")
	generated.P("      if (part == null || part.isBlank()) {")
	generated.P("        continue;")
	generated.P("      }")
	generated.P("      if (normalized.length() > 0) {")
	generated.P("        normalized.append('_');")
	generated.P("      }")
	generated.P("      normalized.append(part);")
	generated.P("    }")
	generated.P("    return normalized.toString();")
	generated.P("  }")
	generated.P()
	generated.P("  private static String toolName(String namespace, String methodName) {")
	generated.P("    String normalizedNamespace = normalizeToolSegment(namespace);")
	generated.P("    String normalizedMethodName = normalizeToolSegment(methodName);")
	generated.P("    if (normalizedNamespace.isEmpty()) {")
	generated.P("      return normalizedMethodName;")
	generated.P("    }")
	generated.P("    if (normalizedMethodName.isEmpty()) {")
	generated.P("      return normalizedNamespace;")
	generated.P("    }")
	generated.P("    return normalizedNamespace + \"_\" + normalizedMethodName;")
	generated.P("  }")
}

func collectJavaDescriptorAccessors(file protoreflect.FileDescriptor, currentPackage string) ([]javaDescriptorAccessor, error) {
	seen := map[string]bool{}
	var accessors []javaDescriptorAccessor
	var visit func(protoreflect.FileDescriptor) error
	visit = func(current protoreflect.FileDescriptor) error {
		if current == nil {
			return nil
		}
		if seen[current.Path()] {
			return nil
		}
		seen[current.Path()] = true

		if current.Path() == file.Path() || shouldIncludeJavaTypeRegistryFile(current) {
			resolved, err := resolveJVMDescriptorFilePackage(current)
			if err != nil {
				return err
			}
			importPath := ""
			if resolved.Package != currentPackage {
				importPath = resolved.Package + "." + resolved.OuterClassName
			}
			accessors = append(accessors, javaDescriptorAccessor{
				ImportPath: importPath,
				Expr:       resolved.OuterClassName + ".getDescriptor()",
			})
		}

		for i := 0; i < current.Imports().Len(); i++ {
			if err := visit(current.Imports().Get(i)); err != nil {
				return err
			}
		}
		return nil
	}
	if err := visit(file); err != nil {
		return nil, err
	}
	sort.Slice(accessors, func(i, j int) bool {
		if accessors[i].ImportPath == accessors[j].ImportPath {
			return accessors[i].Expr < accessors[j].Expr
		}
		return accessors[i].ImportPath < accessors[j].ImportPath
	})
	return accessors, nil
}

func shouldIncludeJavaTypeRegistryFile(file protoreflect.FileDescriptor) bool {
	if file == nil {
		return false
	}
	protoPath := file.Path()
	return !strings.HasPrefix(protoPath, "google/protobuf/") && !strings.HasPrefix(protoPath, "mcp/options/")
}

func validateJavaMetadata(model JVMFileModel) error {
	for _, service := range model.Services {
		for _, icon := range service.Icons {
			if err := validateJavaIconTheme(icon); err != nil {
				return err
			}
		}
		for _, method := range service.Methods {
			for _, icon := range method.Icons {
				if err := validateJavaIconTheme(icon); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func validateJavaIconTheme(icon *mcpoptionsv1.Icon) error {
	switch icon.GetTheme() {
	case "", "light", "dark":
		return nil
	default:
		return fmt.Errorf("unsupported Java icon theme %q", icon.GetTheme())
	}
}

func javaAnnotations(ann *mcpoptionsv1.ToolAnnotations) string {
	if ann == nil {
		return "null"
	}

	return strings.Join([]string{
		"toolAnnotationsMapOrNull(",
		javaNullableString(ann.Title), ", ",
		javaBoolLiteralOrNull(ann.ReadOnlyHint, ann.ReadOnlyHint), ", ",
		javaOptionalBoolLiteral(ann.DestructiveHint), ", ",
		javaBoolLiteralOrNull(ann.IdempotentHint, ann.IdempotentHint), ", ",
		javaOptionalBoolLiteral(ann.OpenWorldHint),
		")",
	}, "")
}

func javaIcons(icons []*mcpoptionsv1.Icon) (string, error) {
	if len(icons) == 0 {
		return "List.of()", nil
	}

	items := make([]string, 0, len(icons))
	for _, icon := range icons {
		if err := validateJavaIconTheme(icon); err != nil {
			return "", err
		}
		items = append(items, fmt.Sprintf(
			"iconMap(%s, %s, %s, %s)",
			quote(icon.GetSrc()),
			javaNullableString(icon.GetMimeType()),
			javaStringListLiteral(icon.GetSizes()),
			javaNullableString(icon.GetTheme()),
		))
	}
	return "List.of(" + strings.Join(items, ", ") + ")", nil
}

func javaTaskSupport(taskSupport mcpoptionsv1.TaskSupport) string {
	switch taskSupport {
	case mcpoptionsv1.TaskSupport_TASK_SUPPORT_OPTIONAL:
		return `toolExecutionMapOrNull("optional")`
	case mcpoptionsv1.TaskSupport_TASK_SUPPORT_REQUIRED:
		return `toolExecutionMapOrNull("required")`
	default:
		return `toolExecutionMapOrNull(null)`
	}
}

func javaNullableString(value string) string {
	if value == "" {
		return "null"
	}
	return quote(value)
}

func javaOptionalBoolLiteral(value *bool) string {
	if value == nil {
		return "null"
	}
	if *value {
		return "Boolean.TRUE"
	}
	return "Boolean.FALSE"
}

func javaBoolLiteralOrNull(include bool, value bool) string {
	if !include {
		return "null"
	}
	if value {
		return "Boolean.TRUE"
	}
	return "Boolean.FALSE"
}

func javaStringListLiteral(values []string) string {
	if len(values) == 0 {
		return "List.of()"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, quote(value))
	}
	return "List.of(" + strings.Join(quoted, ", ") + ")"
}

func javaImportPackage(importPath string) string {
	idx := strings.LastIndex(importPath, ".")
	if idx <= 0 {
		return ""
	}
	return importPath[:idx]
}

func javaSidecarOutputPath(generatedFilenamePrefix string) string {
	return path.Join(path.Dir(generatedFilenamePrefix), javaSidecarClassName(generatedFilenamePrefix)+".java")
}

func javaSidecarClassName(generatedFilenamePrefix string) string {
	base := path.Base(generatedFilenamePrefix)
	var b strings.Builder
	nextUpper := true
	for _, r := range base {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			nextUpper = true
			continue
		}
		if b.Len() == 0 && unicode.IsDigit(r) {
			b.WriteString("Proto")
		}
		if nextUpper {
			b.WriteRune(unicode.ToUpper(r))
			nextUpper = false
			continue
		}
		b.WriteRune(r)
	}
	if b.Len() == 0 {
		b.WriteString("Proto")
	}
	b.WriteString("Mcp")
	return b.String()
}
