# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal/testproto/config/v1/server_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'internal/testproto/config/v1/server_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mcp.options.v1 import options_pb2 as mcp_dot_options_dot_v1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0internal/testproto/config/v1/server_config.proto\x12\x1cinternal.testproto.config.v1\x1a\x1cmcp/options/v1/options.proto\"*\n\x12\x43heckAccessRequest\x12\x14\n\x05label\x18\x01 \x01(\tR\x05label\"/\n\x13\x43heckAccessResponse\x12\x18\n\x07\x61llowed\x18\x01 \x01(\x08R\x07\x61llowed2\xbe\x01\n\tSecureAPI\x12\xa2\x01\n\x0b\x43heckAccess\x12\x30.internal.testproto.config.v1.CheckAccessRequest\x1a\x31.internal.testproto.config.v1.CheckAccessResponse\".\xd2\xb7,*\n\x0c\x63heck_access\x12\x0c\x41\x63\x63\x65ss checkr\x0creports:read\x1a\x0c\xca\xb7,\x08\n\x06secureB\x8c\x02ZJgithub.com/easyp-tech/protoc-gen-mcp/internal/testproto/config/v1;configv1\x92\xb8,\xbb\x01\n\x0esecure-example\x12\x06v2.0.0\"\xa0\x01\n\x1bhttps://mcp.example.com/mcp\x12\x18https://auth.example.com\x1a\x0creports:read\"\x18https://auth.example.com*\"https://auth.example.com/keys.json2\x1bhttps://mcp.example.com/mcpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal.testproto.config.v1.server_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/easyp-tech/protoc-gen-mcp/internal/testproto/config/v1;configv1\222\270,\273\001\n\016secure-example\022\006v2.0.0\"\240\001\n\033https://mcp.example.com/mcp\022\030https://auth.example.com\032\014reports:read\"\030https://auth.example.com*\"https://auth.example.com/keys.json2\033https://mcp.example.com/mcp'
  _globals['_SECUREAPI']._loaded_options = None
  _globals['_SECUREAPI']._serialized_options = b'\312\267,\010\n\006secure'
  _globals['_SECUREAPI'].methods_by_name['CheckAccess']._loaded_options = None
  _globals['_SECUREAPI'].methods_by_name['CheckAccess']._serialized_options = b'\322\267,*\n\014check_access\022\014Access checkr\014reports:read'
  _globals['_CHECKACCESSREQUEST']._serialized_start=112
  _globals['_CHECKACCESSREQUEST']._serialized_end=154
  _globals['_CHECKACCESSRESPONSE']._serialized_start=156
  _globals['_CHECKACCESSRESPONSE']._serialized_end=203
  _globals['_SECUREAPI']._serialized_start=206
  _globals['_SECUREAPI']._serialized_end=396
# @@protoc_insertion_point(module_scope)
