// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.15.2-bufbuild-protocompile-easyp-rc1
// source: 4_crm_system/proto/crm.proto

package crmv1

import (
	_ "github.com/easyp-tech/protoc-gen-mcp/mcp/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file__4_crm_system_proto_crm_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	RequiredTags  []string               `protobuf:"bytes,2,rep,name=required_tags,json=requiredTags,proto3" json:"required_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file__4_crm_system_proto_crm_proto_rawDescGZIP(), []int{1}
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetRequiredTags() []string {
	if x != nil {
		return x.RequiredTags
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file__4_crm_system_proto_crm_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file__4_crm_system_proto_crm_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file__4_crm_system_proto_crm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file__4_crm_system_proto_crm_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File__4_crm_system_proto_crm_proto protoreflect.FileDescriptor

const file__4_crm_system_proto_crm_proto_rawDesc = "" +
	"\n" +
	"\x1c4_crm_system/proto/crm.proto\x12\n" +
	"crm.api.v1\x1a\x1cmcp/options/v1/options.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\x04User\x128\n" +
	"\x02id\x18\x01 \x01(\tB(ڷ,$\n" +
	"\x1fUnique identifier for the user.\xc0\x02\x01R\x02id\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06ڷ,\x02`\x02R\x04name\x12S\n" +
	"\x04tags\x18\x03 \x03(\tB?ڷ,;\n" +
	"\x1aTags assigned to the user.\x1a\x17*\x15\n" +
	"\t\n" +
	"\apremium\n" +
	"\b\n" +
	"\x06active\xf0\x01\x01\x80\x02\x01R\x04tags\x12H\n" +
	"\rregistered_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\aڷ,\x03\xc0\x02\x01R\fregisteredAt\"\xc1\x01\n" +
	"\x10ListUsersRequest\x12V\n" +
	"\x05limit\x18\x01 \x01(\x05B@ڷ,<\n" +
	"\"Maximum number of users to return.\"\x028\n" +
	"\xa1\x01\x00\x00\x00\x00\x00\x00\xf0?\xa9\x01\x00\x00\x00\x00\x00\x00Y@R\x05limit\x12U\n" +
	"\rrequired_tags\x18\x02 \x03(\tB0ڷ,,\n" +
	"*Filter users who must have ALL these tags.R\frequiredTags\";\n" +
	"\x11ListUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.crm.api.v1.UserR\x05users\"\xee\x01\n" +
	"\x11UpdateUserRequest\x12R\n" +
	"\x04user\x18\x01 \x01(\v2\x10.crm.api.v1.UserB,ڷ,(\n" +
	"&The user object containing new values.R\x04user\x12\x84\x01\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskBGڷ,C\n" +
	"4The list of fields to update (e.g., 'name', 'tags').\x1a\v\n" +
	"\tname,tagsR\n" +
	"updateMask\":\n" +
	"\x12UpdateUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.crm.api.v1.UserR\x04user2\xc3\x03\n" +
	"\bUsersAPI\x12}\n" +
	"\tListUsers\x12\x1c.crm.api.v1.ListUsersRequest\x1a\x1d.crm.api.v1.ListUsersResponse\"3ҷ,/\x1a)List users matching the selected filters.R\x02\b\x01\x12\xc5\x01\n" +
	"\n" +
	"UpdateUser\x12\x1d.crm.api.v1.UpdateUserRequest\x1a\x1e.crm.api.v1.UpdateUserResponse\"xҷ,t\x1a>Perform a partial update of a user profile using a field mask.Z2\n" +
	"!https://example.com/edit-icon.svg\x12\rimage/svg+xml\x1apʷ,l\n" +
	"\x03crm\x126Enterprise Customer Relationship Management (CRM) API.\x1a-\n" +
	" https://example.com/crm-icon.png\x12\timage/pngBHZFgithub.com/easyp-tech/protoc-gen-mcp/examples/4_crm_system/proto;crmv1b\x06proto3"

var (
	file__4_crm_system_proto_crm_proto_rawDescOnce sync.Once
	file__4_crm_system_proto_crm_proto_rawDescData []byte
)

func file__4_crm_system_proto_crm_proto_rawDescGZIP() []byte {
	file__4_crm_system_proto_crm_proto_rawDescOnce.Do(func() {
		file__4_crm_system_proto_crm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__4_crm_system_proto_crm_proto_rawDesc), len(file__4_crm_system_proto_crm_proto_rawDesc)))
	})
	return file__4_crm_system_proto_crm_proto_rawDescData
}

var file__4_crm_system_proto_crm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file__4_crm_system_proto_crm_proto_goTypes = []any{
	(*User)(nil),                  // 0: crm.api.v1.User
	(*ListUsersRequest)(nil),      // 1: crm.api.v1.ListUsersRequest
	(*ListUsersResponse)(nil),     // 2: crm.api.v1.ListUsersResponse
	(*UpdateUserRequest)(nil),     // 3: crm.api.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),    // 4: crm.api.v1.UpdateUserResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 6: google.protobuf.FieldMask
}
var file__4_crm_system_proto_crm_proto_depIdxs = []int32{
	5, // 0: crm.api.v1.User.registered_at:type_name -> google.protobuf.Timestamp
	0, // 1: crm.api.v1.ListUsersResponse.users:type_name -> crm.api.v1.User
	0, // 2: crm.api.v1.UpdateUserRequest.user:type_name -> crm.api.v1.User
	6, // 3: crm.api.v1.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	0, // 4: crm.api.v1.UpdateUserResponse.user:type_name -> crm.api.v1.User
	1, // 5: crm.api.v1.UsersAPI.ListUsers:input_type -> crm.api.v1.ListUsersRequest
	3, // 6: crm.api.v1.UsersAPI.UpdateUser:input_type -> crm.api.v1.UpdateUserRequest
	2, // 7: crm.api.v1.UsersAPI.ListUsers:output_type -> crm.api.v1.ListUsersResponse
	4, // 8: crm.api.v1.UsersAPI.UpdateUser:output_type -> crm.api.v1.UpdateUserResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file__4_crm_system_proto_crm_proto_init() }
func file__4_crm_system_proto_crm_proto_init() {
	if File__4_crm_system_proto_crm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__4_crm_system_proto_crm_proto_rawDesc), len(file__4_crm_system_proto_crm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__4_crm_system_proto_crm_proto_goTypes,
		DependencyIndexes: file__4_crm_system_proto_crm_proto_depIdxs,
		MessageInfos:      file__4_crm_system_proto_crm_proto_msgTypes,
	}.Build()
	File__4_crm_system_proto_crm_proto = out.File
	file__4_crm_system_proto_crm_proto_goTypes = nil
	file__4_crm_system_proto_crm_proto_depIdxs = nil
}
