# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: 3_file_manager/proto/filemanager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    '3_file_manager/proto/filemanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mcp.options.v1 import options_pb2 as mcp_dot_options_dot_v1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&3_file_manager/proto/filemanager.proto\x12\x12\x66ilemanager.api.v1\x1a\x1cmcp/options/v1/options.proto\"\x90\x01\n\x0fReadFileRequest\x12}\n\x08\x66ilename\x18\x01 \x01(\tBa\xda\xb7,]\nDThe name of the file to read. Must not contain paths or directories.R\x13^[a-zA-Z0-9_\\-\\.]+$`\x01R\x08\x66ilename\",\n\x10ReadFileResponse\x12\x18\n\x07\x63ontent\x18\x01 \x01(\tR\x07\x63ontent\"\x94\x01\n\x11\x44\x65leteFileRequest\x12\x7f\n\x08\x66ilename\x18\x01 \x01(\tBc\xda\xb7,_\nFThe name of the file to delete. Must not contain paths or directories.R\x13^[a-zA-Z0-9_\\-\\.]+$`\x01R\x08\x66ilename\".\n\x12\x44\x65leteFileResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success2\xe0\x02\n\x0e\x46ileManagerAPI\x12\x7f\n\x08ReadFile\x12#.filemanager.api.v1.ReadFileRequest\x1a$.filemanager.api.v1.ReadFileResponse\"(\xd2\xb7,$\x1a\x1cReads the content of a file.R\x04\x08\x01\x18\x01\x12\x82\x01\n\nDeleteFile\x12%.filemanager.api.v1.DeleteFileRequest\x1a&.filemanager.api.v1.DeleteFileResponse\"%\xd2\xb7,!\x1a\x1bPermanently deletes a file.R\x02\x10\x01\x1aH\xca\xb7,D\n\x05\x66iles\x12;A secure file management service for temporary directories.BRZPgithub.com/easyp-tech/protoc-gen-mcp/examples/3_file_manager/proto;filemanagerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '3_file_manager.proto.filemanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/easyp-tech/protoc-gen-mcp/examples/3_file_manager/proto;filemanagerv1'
  _globals['_READFILEREQUEST'].fields_by_name['filename']._loaded_options = None
  _globals['_READFILEREQUEST'].fields_by_name['filename']._serialized_options = b'\332\267,]\nDThe name of the file to read. Must not contain paths or directories.R\023^[a-zA-Z0-9_\\-\\.]+$`\001'
  _globals['_DELETEFILEREQUEST'].fields_by_name['filename']._loaded_options = None
  _globals['_DELETEFILEREQUEST'].fields_by_name['filename']._serialized_options = b'\332\267,_\nFThe name of the file to delete. Must not contain paths or directories.R\023^[a-zA-Z0-9_\\-\\.]+$`\001'
  _globals['_FILEMANAGERAPI']._loaded_options = None
  _globals['_FILEMANAGERAPI']._serialized_options = b'\312\267,D\n\005files\022;A secure file management service for temporary directories.'
  _globals['_FILEMANAGERAPI'].methods_by_name['ReadFile']._loaded_options = None
  _globals['_FILEMANAGERAPI'].methods_by_name['ReadFile']._serialized_options = b'\322\267,$\032\034Reads the content of a file.R\004\010\001\030\001'
  _globals['_FILEMANAGERAPI'].methods_by_name['DeleteFile']._loaded_options = None
  _globals['_FILEMANAGERAPI'].methods_by_name['DeleteFile']._serialized_options = b'\322\267,!\032\033Permanently deletes a file.R\002\020\001'
  _globals['_READFILEREQUEST']._serialized_start=93
  _globals['_READFILEREQUEST']._serialized_end=237
  _globals['_READFILERESPONSE']._serialized_start=239
  _globals['_READFILERESPONSE']._serialized_end=283
  _globals['_DELETEFILEREQUEST']._serialized_start=286
  _globals['_DELETEFILEREQUEST']._serialized_end=434
  _globals['_DELETEFILERESPONSE']._serialized_start=436
  _globals['_DELETEFILERESPONSE']._serialized_end=482
  _globals['_FILEMANAGERAPI']._serialized_start=485
  _globals['_FILEMANAGERAPI']._serialized_end=837
# @@protoc_insertion_point(module_scope)
