// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.15.2-bufbuild-protocompile-easyp-rc1
// source: examples/11_protobuf_first_mcp/proto/showcase.proto

package showcasev1

import (
	_ "github.com/easyp-tech/protoc-gen-mcp/mcp/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetOverviewRequest identifies the requested report topic.
type GetOverviewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic that should appear in the overview.
	Topic         string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewRequest) Reset() {
	*x = GetOverviewRequest{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewRequest) ProtoMessage() {}

func (x *GetOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewRequest) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{0}
}

func (x *GetOverviewRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// GetOverviewResponse returns a structured report summary.
type GetOverviewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes the queried topic.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Human-readable summary of demonstration state.
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Number of reports published during the current process.
	ReportCount   int32 `protobuf:"varint,3,opt,name=report_count,json=reportCount,proto3" json:"report_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewResponse) Reset() {
	*x = GetOverviewResponse{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewResponse) ProtoMessage() {}

func (x *GetOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetOverviewResponse) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{1}
}

func (x *GetOverviewResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetOverviewResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GetOverviewResponse) GetReportCount() int32 {
	if x != nil {
		return x.ReportCount
	}
	return 0
}

// PublishReportRequest contains the report data.
type PublishReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Title of the new report.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Plain-text report body.
	Body          string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReportRequest) Reset() {
	*x = PublishReportRequest{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReportRequest) ProtoMessage() {}

func (x *PublishReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReportRequest.ProtoReflect.Descriptor instead.
func (*PublishReportRequest) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{2}
}

func (x *PublishReportRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishReportRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// PublishReportResponse confirms the new report.
type PublishReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier created by the demonstration handler.
	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// Status of the operation.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReportResponse) Reset() {
	*x = PublishReportResponse{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReportResponse) ProtoMessage() {}

func (x *PublishReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReportResponse.ProtoReflect.Descriptor instead.
func (*PublishReportResponse) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{3}
}

func (x *PublishReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *PublishReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GuidancePrompt illustrates typed protobuf-backed prompts.
type GuidancePrompt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Focus topic for the generated prompt.
	Topic         string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuidancePrompt) Reset() {
	*x = GuidancePrompt{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuidancePrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuidancePrompt) ProtoMessage() {}

func (x *GuidancePrompt) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuidancePrompt.ProtoReflect.Descriptor instead.
func (*GuidancePrompt) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{4}
}

func (x *GuidancePrompt) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// ServerStatus illustrates a dynamic ProtoJSON MCP resource.
type ServerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the in-memory server is available.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Number of reports published in this process.
	ReportCount   int32 `protobuf:"varint,2,opt,name=report_count,json=reportCount,proto3" json:"report_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ServerStatus) GetReportCount() int32 {
	if x != nil {
		return x.ReportCount
	}
	return 0
}

// NoteText illustrates a dynamic text/plain resource URI template.
type NoteText struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text returned without a JSON envelope.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteText) Reset() {
	*x = NoteText{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteText) ProtoMessage() {}

func (x *NoteText) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteText.ProtoReflect.Descriptor instead.
func (*NoteText) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{6}
}

func (x *NoteText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// BinaryAttachment illustrates the MCP binary blob wire representation.
type BinaryAttachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw bytes of the example attachment.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryAttachment) Reset() {
	*x = BinaryAttachment{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryAttachment) ProtoMessage() {}

func (x *BinaryAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryAttachment.ProtoReflect.Descriptor instead.
func (*BinaryAttachment) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{7}
}

func (x *BinaryAttachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// EmbeddedSkill is a real SKILL.md automatically embedded by the generator.
type EmbeddedSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddedSkill) Reset() {
	*x = EmbeddedSkill{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedSkill) ProtoMessage() {}

func (x *EmbeddedSkill) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedSkill.ProtoReflect.Descriptor instead.
func (*EmbeddedSkill) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{8}
}

// Dashboard is a self-contained HTML UI asset embedded by the generator.
type Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dashboard) Reset() {
	*x = Dashboard{}
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dashboard) ProtoMessage() {}

func (x *Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dashboard.ProtoReflect.Descriptor instead.
func (*Dashboard) Descriptor() ([]byte, []int) {
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP(), []int{9}
}

var File_examples_11_protobuf_first_mcp_proto_showcase_proto protoreflect.FileDescriptor

const file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDesc = "" +
	"\n" +
	"3examples/11_protobuf_first_mcp/proto/showcase.proto\x12\vshowcase.v1\x1a\x1cmcp/options/v1/options.proto\"*\n" +
	"\x12GetOverviewRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"h\n" +
	"\x13GetOverviewResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12!\n" +
	"\freport_count\x18\x03 \x01(\x05R\vreportCount\"@\n" +
	"\x14PublishReportRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"L\n" +
	"\x15PublishReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"u\n" +
	"\x0eGuidancePrompt\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic:M\x82\xb8,I\n" +
	"\x0eshowcase_guide\x12\x0eShowcase guide\x1a'Suggest how to explore this MCP server.\"\xa2\x01\n" +
	"\fServerStatus\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12!\n" +
	"\freport_count\x18\x02 \x01(\x05R\vreportCount:Y\x8a\xb8,U\n" +
	"\x11showcase://status\x1a\rserver_status\"\x1fVolatile server status in JSON.*\x10application/json\"w\n" +
	"\bNoteText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text:W\x8a\xb8,S\x12\x15showcase://notes/{id}\x1a\tnote_text\"\x1dRead a named plain-text note.*\n" +
	"text/plainB\x04text\"\xa6\x01\n" +
	"\x10BinaryAttachment\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data:~\x8a\xb8,z\n" +
	"\x15showcase://attachment\x1a\x11binary_attachment\".Small binary attachment served as an MCP blob.*\x18application/octet-streamB\x04data\"\x8e\x01\n" +
	"\rEmbeddedSkill:}\x8a\xb8,y\n" +
	"\x13showcase://SKILL.md\x1a\x0eshowcase_skill\"2Instructions exposed as Markdown rather than JSON.*\rtext/markdownJ\x0fassets/SKILL.md\"\xce\x01\n" +
	"\tDashboard:\xc0\x01\x8a\xb8,\xbb\x01\n" +
	"\x17ui://showcase/dashboard\x1a\x12showcase_dashboard\"\x1eStatic MCP Apps HTML resource.*\x19text/html;profile=mcp-appJ\x15assets/dashboard.htmlR:\n" +
	"2\n" +
	"\x17https://api.example.com\x12\x17https://cdn.example.com\x12\x02 \x01 \x012\xea\x03\n" +
	"\vShowcaseAPI\x12\xdc\x01\n" +
	"\vGetOverview\x12\x1f.showcase.v1.GetOverviewRequest\x1a .showcase.v1.GetOverviewResponse\"\x89\x01ҷ,\x84\x01\n" +
	"\fget_overview\x12\fGet overview\x1a;Return a report summary and link to its MCP Apps dashboard.R\x02\b\x01j%\n" +
	"\x17ui://showcase/dashboard\x12\x05model\x12\x03app\x12\xbf\x01\n" +
	"\rPublishReport\x12!.showcase.v1.PublishReportRequest\x1a\".showcase.v1.PublishReportResponse\"gҷ,c\n" +
	"\x0epublish_report\x12\x0ePublish report\x1a1Create a demonstration report in volatile memory.r\x0eshowcase:write\x1a:ʷ,6\n" +
	"\bshowcase\x12*Inspect and publish demonstration reports.B\xb2\x02\x92\xb8,\xd7\x01\n" +
	"\x17protobuf-first-showcase\x12\x06v1.0.0\"\xb3\x01\n" +
	"\x1bhttps://mcp.example.com/mcp\x12\x18https://auth.example.com\x1a\rshowcase:read\"\x18https://auth.example.com*.https://auth.example.com/.well-known/jwks.json2\x1bhttps://mcp.example.com/mcp:\x04/mcpZTgithub.com/easyp-tech/protoc-gen-mcp/examples/11_protobuf_first_mcp/proto;showcasev1b\x06proto3"

var (
	file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescOnce sync.Once
	file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescData []byte
)

func file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescGZIP() []byte {
	file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescOnce.Do(func() {
		file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDesc), len(file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDesc)))
	})
	return file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDescData
}

var file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_examples_11_protobuf_first_mcp_proto_showcase_proto_goTypes = []any{
	(*GetOverviewRequest)(nil),    // 0: showcase.v1.GetOverviewRequest
	(*GetOverviewResponse)(nil),   // 1: showcase.v1.GetOverviewResponse
	(*PublishReportRequest)(nil),  // 2: showcase.v1.PublishReportRequest
	(*PublishReportResponse)(nil), // 3: showcase.v1.PublishReportResponse
	(*GuidancePrompt)(nil),        // 4: showcase.v1.GuidancePrompt
	(*ServerStatus)(nil),          // 5: showcase.v1.ServerStatus
	(*NoteText)(nil),              // 6: showcase.v1.NoteText
	(*BinaryAttachment)(nil),      // 7: showcase.v1.BinaryAttachment
	(*EmbeddedSkill)(nil),         // 8: showcase.v1.EmbeddedSkill
	(*Dashboard)(nil),             // 9: showcase.v1.Dashboard
}
var file_examples_11_protobuf_first_mcp_proto_showcase_proto_depIdxs = []int32{
	0, // 0: showcase.v1.ShowcaseAPI.GetOverview:input_type -> showcase.v1.GetOverviewRequest
	2, // 1: showcase.v1.ShowcaseAPI.PublishReport:input_type -> showcase.v1.PublishReportRequest
	1, // 2: showcase.v1.ShowcaseAPI.GetOverview:output_type -> showcase.v1.GetOverviewResponse
	3, // 3: showcase.v1.ShowcaseAPI.PublishReport:output_type -> showcase.v1.PublishReportResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_11_protobuf_first_mcp_proto_showcase_proto_init() }
func file_examples_11_protobuf_first_mcp_proto_showcase_proto_init() {
	if File_examples_11_protobuf_first_mcp_proto_showcase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDesc), len(file_examples_11_protobuf_first_mcp_proto_showcase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_11_protobuf_first_mcp_proto_showcase_proto_goTypes,
		DependencyIndexes: file_examples_11_protobuf_first_mcp_proto_showcase_proto_depIdxs,
		MessageInfos:      file_examples_11_protobuf_first_mcp_proto_showcase_proto_msgTypes,
	}.Build()
	File_examples_11_protobuf_first_mcp_proto_showcase_proto = out.File
	file_examples_11_protobuf_first_mcp_proto_showcase_proto_goTypes = nil
	file_examples_11_protobuf_first_mcp_proto_showcase_proto_depIdxs = nil
}
