// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: internal/testproto/resources/v1/resources.proto

package resourcesv1

import (
	context "context"
	embed "embed"
	errors "errors"
	fmt "fmt"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	auth "github.com/modelcontextprotocol/go-sdk/auth"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	proto "google.golang.org/protobuf/proto"
	http "net/http"
)

//go:embed testdata/report.html
var File_internal_testproto_resources_v1_resources_proto_mcpAssets embed.FS

// File_internal_testproto_resources_v1_resources_protoResourceHandler defines handlers for MCP resources in internal/testproto/resources/v1/resources.proto.
type File_internal_testproto_resources_v1_resources_protoResourceHandler interface {
	ReadServerStatus(ctx context.Context) (*ServerStatus, error)
	ListUserProfiles(ctx context.Context) ([]mcp.Resource, error)
	ReadUserProfile(ctx context.Context, user_id string) (*UserProfile, error)
	ListDocuments(ctx context.Context) ([]mcp.Resource, error)
	ReadDocument(ctx context.Context, project_id string, document_id string) (*Document, error)
	ReadSkillDocument(ctx context.Context) (*SkillDocument, error)
	ListPlainTexts(ctx context.Context) ([]mcp.Resource, error)
	ReadPlainText(ctx context.Context, name string) (*PlainText, error)
	ReadRawBinary(ctx context.Context) (*RawBinary, error)
}

// RegisterFile_internal_testproto_resources_v1_resources_protoResources registers generated MCP resources for File_internal_testproto_resources_v1_resources_proto.
func RegisterFile_internal_testproto_resources_v1_resources_protoResources(ctx context.Context, server *mcp.Server, impl File_internal_testproto_resources_v1_resources_protoResourceHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterFile_internal_testproto_resources_v1_resources_protoResources: impl is nil")
	}
	resolvedOpts := mcpruntime.ResolveOptions("", opts)
	{
		name := "server_status"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		annotations := &mcp.Annotations{
			Audience: []mcp.Role{
				"user",
				"assistant",
			},
		}
		annotations.Priority = 0.8
		server.AddResource(&mcp.Resource{
			Name:        name,
			URI:         "server://status",
			Description: "Current server status and health information",
			MIMEType:    "application/json",
			Annotations: annotations,
		}, func(ctx context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
			result, err := impl.ReadServerStatus(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("server://status", "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcp.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "user_profile"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		instances, err := impl.ListUserProfiles(ctx)
		if err != nil {
			return fmt.Errorf("RegisterFile_internal_testproto_resources_v1_resources_protoResources: listing user_profile: %w", err)
		}
		readHandler := func(ctx context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
			params, err := mcpruntime.ExtractURIParams(req.Params.URI, "users://{user_id}/profile")
			if err != nil {
				return nil, err
			}
			user_id := params["user_id"]
			result, err := impl.ReadUserProfile(ctx, user_id)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent(req.Params.URI, "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcp.ReadResourceResult{Contents: contents}, nil
		}
		for i := range instances {
			server.AddResource(&instances[i], readHandler)
		}
		server.AddResourceTemplate(&mcp.ResourceTemplate{
			Name:        name,
			URITemplate: "users://{user_id}/profile",
			Description: "User profile information",
			MIMEType:    "application/json",
		}, readHandler)
	}

	{
		name := "document"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		annotations := &mcp.Annotations{}
		annotations.Priority = 0.5
		instances, err := impl.ListDocuments(ctx)
		if err != nil {
			return fmt.Errorf("RegisterFile_internal_testproto_resources_v1_resources_protoResources: listing document: %w", err)
		}
		readHandler := func(ctx context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
			params, err := mcpruntime.ExtractURIParams(req.Params.URI, "projects://{project_id}/documents/{document_id}")
			if err != nil {
				return nil, err
			}
			project_id := params["project_id"]
			document_id := params["document_id"]
			result, err := impl.ReadDocument(ctx, project_id, document_id)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent(req.Params.URI, "application/json", result)
			if err != nil {
				return nil, err
			}
			return &mcp.ReadResourceResult{Contents: contents}, nil
		}
		for i := range instances {
			server.AddResource(&instances[i], readHandler)
		}
		server.AddResourceTemplate(&mcp.ResourceTemplate{
			Name:        name,
			URITemplate: "projects://{project_id}/documents/{document_id}",
			Description: "Project document",
			MIMEType:    "application/json",
			Annotations: annotations,
		}, readHandler)
	}

	{
		name := "skill_document"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		server.AddResource(&mcp.Resource{
			Name:        name,
			URI:         "skill://example/SKILL.md",
			Description: "Instructions for the example MCP skill",
			MIMEType:    "text/markdown",
		}, func(ctx context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
			result, err := impl.ReadSkillDocument(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("skill://example/SKILL.md", "text/markdown", result, "markdown")
			if err != nil {
				return nil, err
			}
			return &mcp.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "plain_text"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		instances, err := impl.ListPlainTexts(ctx)
		if err != nil {
			return fmt.Errorf("RegisterFile_internal_testproto_resources_v1_resources_protoResources: listing plain_text: %w", err)
		}
		readHandler := func(ctx context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
			params, err := mcpruntime.ExtractURIParams(req.Params.URI, "docs://example/{name}")
			if err != nil {
				return nil, err
			}
			name := params["name"]
			result, err := impl.ReadPlainText(ctx, name)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent(req.Params.URI, "text/plain", result, "body")
			if err != nil {
				return nil, err
			}
			return &mcp.ReadResourceResult{Contents: contents}, nil
		}
		for i := range instances {
			server.AddResource(&instances[i], readHandler)
		}
		server.AddResourceTemplate(&mcp.ResourceTemplate{
			Name:        name,
			URITemplate: "docs://example/{name}",
			Description: "PlainText demonstrates parameterized text resources.",
			MIMEType:    "text/plain",
		}, readHandler)
	}

	{
		name := "raw_binary"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		server.AddResource(&mcp.Resource{
			Name:        name,
			URI:         "blob://example/attachment",
			Description: "RawBinary demonstrates an MCP blob using a bytes content field.",
			MIMEType:    "application/octet-stream",
		}, func(ctx context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
			result, err := impl.ReadRawBinary(ctx)
			if err != nil {
				return nil, err
			}
			contents, err := mcpruntime.MarshalResourceContent("blob://example/attachment", "application/octet-stream", result, "data")
			if err != nil {
				return nil, err
			}
			return &mcp.ReadResourceResult{Contents: contents}, nil
		})
	}

	{
		name := "report_ui"
		if resolvedOpts.Namespace != "" {
			name = resolvedOpts.Namespace + "_" + name
		}
		if err := mcpruntime.RegisterEmbeddedResource(server, File_internal_testproto_resources_v1_resources_proto_mcpAssets, "testdata/report.html", &mcp.Resource{
			Name:        name,
			URI:         "ui://example/report",
			Description: "AppPage is an MCP Apps HTML resource generated from a protobuf message.",
			MIMEType:    "text/html;profile=mcp-app",
			Meta:        mcpruntime.AppResourceMetadata(mcpruntime.AppResourceConfig{CSP: mcpruntime.AppResourceCSP{ConnectDomains: []string{"https://api.example.com"}, ResourceDomains: []string{"https://cdn.example.com"}, FrameDomains: []string{}, BaseURIDomains: []string{}}, Permissions: mcpruntime.AppResourcePermissions{Camera: false, Microphone: false, Geolocation: false, ClipboardWrite: true}, PrefersBorder: proto.Bool(true)}),
		}); err != nil {
			return err
		}
	}

	return nil
}

// File_internal_testproto_resources_v1_resources_protoMCPHandlers supplies business handlers for the generated file.
type File_internal_testproto_resources_v1_resources_protoMCPHandlers struct {
	Resources File_internal_testproto_resources_v1_resources_protoResourceHandler
}

// NewFile_internal_testproto_resources_v1_resources_protoMCPServer constructs and populates an official MCP SDK server.
func NewFile_internal_testproto_resources_v1_resources_protoMCPServer(ctx context.Context, handlers File_internal_testproto_resources_v1_resources_protoMCPHandlers) (*mcp.Server, error) {
	server, err := mcpruntime.NewConfiguredServer("resource-fixture-server", "v1.0.0", true)
	if err != nil {
		return nil, err
	}
	if err := RegisterFile_internal_testproto_resources_v1_resources_protoResources(ctx, server, handlers.Resources); err != nil {
		return nil, err
	}
	return server, nil
}

// NewFile_internal_testproto_resources_v1_resources_protoMCPHTTPHandler applies protobuf OAuth policy to SDK Streamable HTTP.
func NewFile_internal_testproto_resources_v1_resources_protoMCPHTTPHandler(server *mcp.Server, verifier auth.TokenVerifier) (http.Handler, error) {
	return mcpruntime.NewConfiguredHTTPHandler(server, nil, verifier)
}
