// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.15.2-bufbuild-protocompile-easyp-rc1
// source: internal/testproto/example/v1/example.proto

package examplev1

import (
	_ "github.com/easyp-tech/protoc-gen-mcp/mcp/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportStatus describes the report state.
type ReportStatus int32

const (
	// REPORT_STATUS_NONE is the default enum value.
	ReportStatus_REPORT_STATUS_NONE ReportStatus = 0
	// REPORT_STATUS_OK indicates a successful report.
	ReportStatus_REPORT_STATUS_OK ReportStatus = 1
	// REPORT_STATUS_FAILED indicates a failed report.
	ReportStatus_REPORT_STATUS_FAILED ReportStatus = 2
)

// Enum value maps for ReportStatus.
var (
	ReportStatus_name = map[int32]string{
		0: "REPORT_STATUS_NONE",
		1: "REPORT_STATUS_OK",
		2: "REPORT_STATUS_FAILED",
	}
	ReportStatus_value = map[string]int32{
		"REPORT_STATUS_NONE":   0,
		"REPORT_STATUS_OK":     1,
		"REPORT_STATUS_FAILED": 2,
	}
)

func (x ReportStatus) Enum() *ReportStatus {
	p := new(ReportStatus)
	*p = x
	return p
}

func (x ReportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_testproto_example_v1_example_proto_enumTypes[0].Descriptor()
}

func (ReportStatus) Type() protoreflect.EnumType {
	return &file_internal_testproto_example_v1_example_proto_enumTypes[0]
}

func (x ReportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatus.Descriptor instead.
func (ReportStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{0}
}

// CreateReportRequest describes a report generation request.
type CreateReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// city is the city name.
	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// count is the number of requested items.
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// details contains nested report options.
	Details *ReportDetails `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// units overrides the default units.
	Units *string `protobuf:"bytes,4,opt,name=units,proto3,oneof" json:"units,omitempty"`
	// labels adds additional labels.
	Labels        []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReportRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateReportRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateReportRequest) GetDetails() *ReportDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CreateReportRequest) GetUnits() string {
	if x != nil && x.Units != nil {
		return *x.Units
	}
	return ""
}

func (x *CreateReportRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// CreateReportResponse describes a report generation result.
type CreateReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report_id is the generated report identifier.
	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// total_count is returned as a ProtoJSON string.
	TotalCount int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// status is the final report status.
	Status ReportStatus `protobuf:"varint,3,opt,name=status,proto3,enum=internal.testproto.example.v1.ReportStatus" json:"status,omitempty"`
	// details echoes the nested options.
	Details *ReportDetails `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	// warnings contains optional warning messages.
	Warnings      []string `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportResponse) Reset() {
	*x = CreateReportResponse{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportResponse) ProtoMessage() {}

func (x *CreateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportResponse.ProtoReflect.Descriptor instead.
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *CreateReportResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CreateReportResponse) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_NONE
}

func (x *CreateReportResponse) GetDetails() *ReportDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CreateReportResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// HiddenThingRequest is used by the hidden RPC.
type HiddenThingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the hidden request payload.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiddenThingRequest) Reset() {
	*x = HiddenThingRequest{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddenThingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenThingRequest) ProtoMessage() {}

func (x *HiddenThingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenThingRequest.ProtoReflect.Descriptor instead.
func (*HiddenThingRequest) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{2}
}

func (x *HiddenThingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// HiddenThingResponse is used by the hidden RPC.
type HiddenThingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiddenThingResponse) Reset() {
	*x = HiddenThingResponse{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddenThingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenThingResponse) ProtoMessage() {}

func (x *HiddenThingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenThingResponse.ProtoReflect.Descriptor instead.
func (*HiddenThingResponse) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{3}
}

// PingRequest is used by the health-check RPC.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{4}
}

// PingResponse is used by the health-check RPC.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ack confirms the health-check call.
	Ack           *emptypb.Empty `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetAck() *emptypb.Empty {
	if x != nil {
		return x.Ack
	}
	return nil
}

// DescribeAdvancedShapesRequest exercises supported advanced protobuf shapes.
type DescribeAdvancedShapesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels stores arbitrary string metadata.
	Labels map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// quantities demonstrates numeric map keys encoded as JSON object keys.
	Quantities map[int32]string `protobuf:"bytes,2,rep,name=quantities,proto3" json:"quantities,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// toggles demonstrates bool map keys encoded as JSON object keys.
	Toggles map[bool]string `protobuf:"bytes,3,rep,name=toggles,proto3" json:"toggles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// limits demonstrates unsigned numeric map keys encoded as JSON object keys.
	Limits map[uint64]string `protobuf:"bytes,14,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// observed_at is represented as an RFC 3339 timestamp string.
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3,oneof" json:"observed_at,omitempty"`
	// ttl is represented as a protobuf duration string.
	Ttl *durationpb.Duration `protobuf:"bytes,5,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`
	// payload accepts arbitrary JSON objects.
	Payload *structpb.Struct `protobuf:"bytes,6,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	// items accepts arbitrary JSON arrays.
	Items *structpb.ListValue `protobuf:"bytes,7,opt,name=items,proto3,oneof" json:"items,omitempty"`
	// dynamic accepts arbitrary JSON values.
	Dynamic *structpb.Value `protobuf:"bytes,8,opt,name=dynamic,proto3,oneof" json:"dynamic,omitempty"`
	// note exercises `StringValue` wrapper support.
	Note *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=note,proto3,oneof" json:"note,omitempty"`
	// total exercises Int64Value wrapper support.
	Total *wrapperspb.Int64Value `protobuf:"bytes,10,opt,name=total,proto3,oneof" json:"total,omitempty"`
	// enabled exercises BoolValue wrapper support.
	Enabled *wrapperspb.BoolValue `protobuf:"bytes,11,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	// ratio exercises ProtoJSON float special values.
	Ratio *wrapperspb.DoubleValue `protobuf:"bytes,12,opt,name=ratio,proto3,oneof" json:"ratio,omitempty"`
	// mask exercises FieldMask string support.
	Mask *fieldmaskpb.FieldMask `protobuf:"bytes,13,opt,name=mask,proto3,oneof" json:"mask,omitempty"`
	// blob exercises BytesValue wrapper support.
	Blob *wrapperspb.BytesValue `protobuf:"bytes,15,opt,name=blob,proto3,oneof" json:"blob,omitempty"`
	// small_total exercises Int32Value wrapper support.
	SmallTotal *wrapperspb.Int32Value `protobuf:"bytes,16,opt,name=small_total,json=smallTotal,proto3,oneof" json:"small_total,omitempty"`
	// uint_total exercises UInt32Value wrapper support.
	UintTotal *wrapperspb.UInt32Value `protobuf:"bytes,17,opt,name=uint_total,json=uintTotal,proto3,oneof" json:"uint_total,omitempty"`
	// huge_total exercises UInt64Value wrapper support.
	HugeTotal *wrapperspb.UInt64Value `protobuf:"bytes,18,opt,name=huge_total,json=hugeTotal,proto3,oneof" json:"huge_total,omitempty"`
	// weight exercises FloatValue wrapper support.
	Weight *wrapperspb.FloatValue `protobuf:"bytes,19,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	// raw_ratio exercises raw double ProtoJSON float support.
	RawRatio *float64 `protobuf:"fixed64,20,opt,name=raw_ratio,json=rawRatio,proto3,oneof" json:"raw_ratio,omitempty"`
	// tree exercises recursive message schemas.
	Tree *RecursiveNode `protobuf:"bytes,24,opt,name=tree,proto3,oneof" json:"tree,omitempty"`
	// detail_any exercises Any with a regular embedded message payload.
	// Example: {"@type":"type.googleapis.com/internal.testproto.example.v1.ReportDetails","label":"from-any"}
	DetailAny *anypb.Any `protobuf:"bytes,25,opt,name=detail_any,json=detailAny,proto3,oneof" json:"detail_any,omitempty"`
	// duration_any exercises Any with a well-known embedded payload.
	// Example: {"@type":"type.googleapis.com/google.protobuf.Duration","value":"3600s"}
	DurationAny *anypb.Any `protobuf:"bytes,26,opt,name=duration_any,json=durationAny,proto3,oneof" json:"duration_any,omitempty"`
	// selector exercises top-level oneof support.
	//
	// Types that are valid to be assigned to Selector:
	//
	//	*DescribeAdvancedShapesRequest_CityAlias
	//	*DescribeAdvancedShapesRequest_CityId
	//	*DescribeAdvancedShapesRequest_CityDetails
	Selector      isDescribeAdvancedShapesRequest_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeAdvancedShapesRequest) Reset() {
	*x = DescribeAdvancedShapesRequest{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeAdvancedShapesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeAdvancedShapesRequest) ProtoMessage() {}

func (x *DescribeAdvancedShapesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeAdvancedShapesRequest.ProtoReflect.Descriptor instead.
func (*DescribeAdvancedShapesRequest) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeAdvancedShapesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetQuantities() map[int32]string {
	if x != nil {
		return x.Quantities
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetToggles() map[bool]string {
	if x != nil {
		return x.Toggles
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetLimits() map[uint64]string {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetItems() *structpb.ListValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetDynamic() *structpb.Value {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetNote() *wrapperspb.StringValue {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetTotal() *wrapperspb.Int64Value {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetRatio() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Ratio
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetBlob() *wrapperspb.BytesValue {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetSmallTotal() *wrapperspb.Int32Value {
	if x != nil {
		return x.SmallTotal
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetUintTotal() *wrapperspb.UInt32Value {
	if x != nil {
		return x.UintTotal
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetHugeTotal() *wrapperspb.UInt64Value {
	if x != nil {
		return x.HugeTotal
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetWeight() *wrapperspb.FloatValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetRawRatio() float64 {
	if x != nil && x.RawRatio != nil {
		return *x.RawRatio
	}
	return 0
}

func (x *DescribeAdvancedShapesRequest) GetTree() *RecursiveNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetDetailAny() *anypb.Any {
	if x != nil {
		return x.DetailAny
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetDurationAny() *anypb.Any {
	if x != nil {
		return x.DurationAny
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetSelector() isDescribeAdvancedShapesRequest_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *DescribeAdvancedShapesRequest) GetCityAlias() string {
	if x != nil {
		if x, ok := x.Selector.(*DescribeAdvancedShapesRequest_CityAlias); ok {
			return x.CityAlias
		}
	}
	return ""
}

func (x *DescribeAdvancedShapesRequest) GetCityId() int64 {
	if x != nil {
		if x, ok := x.Selector.(*DescribeAdvancedShapesRequest_CityId); ok {
			return x.CityId
		}
	}
	return 0
}

func (x *DescribeAdvancedShapesRequest) GetCityDetails() *ReportDetails {
	if x != nil {
		if x, ok := x.Selector.(*DescribeAdvancedShapesRequest_CityDetails); ok {
			return x.CityDetails
		}
	}
	return nil
}

type isDescribeAdvancedShapesRequest_Selector interface {
	isDescribeAdvancedShapesRequest_Selector()
}

type DescribeAdvancedShapesRequest_CityAlias struct {
	// city_alias exercises string oneof members.
	CityAlias string `protobuf:"bytes,21,opt,name=city_alias,json=cityAlias,proto3,oneof"`
}

type DescribeAdvancedShapesRequest_CityId struct {
	// city_id exercises int64 oneof members with ProtoJSON string encoding.
	CityId int64 `protobuf:"varint,22,opt,name=city_id,json=cityId,proto3,oneof"`
}

type DescribeAdvancedShapesRequest_CityDetails struct {
	// city_details exercises message oneof members.
	CityDetails *ReportDetails `protobuf:"bytes,23,opt,name=city_details,json=cityDetails,proto3,oneof"`
}

func (*DescribeAdvancedShapesRequest_CityAlias) isDescribeAdvancedShapesRequest_Selector() {}

func (*DescribeAdvancedShapesRequest_CityId) isDescribeAdvancedShapesRequest_Selector() {}

func (*DescribeAdvancedShapesRequest_CityDetails) isDescribeAdvancedShapesRequest_Selector() {}

// DescribeAdvancedShapesResponse echoes supported advanced protobuf shapes.
type DescribeAdvancedShapesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels stores arbitrary string metadata.
	Labels map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// quantities demonstrates numeric map keys encoded as JSON object keys.
	Quantities map[int32]string `protobuf:"bytes,2,rep,name=quantities,proto3" json:"quantities,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// toggles demonstrates bool map keys encoded as JSON object keys.
	Toggles map[bool]string `protobuf:"bytes,3,rep,name=toggles,proto3" json:"toggles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// limits demonstrates unsigned numeric map keys encoded as JSON object keys.
	Limits map[uint64]string `protobuf:"bytes,14,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// observed_at is represented as an RFC 3339 timestamp string.
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3,oneof" json:"observed_at,omitempty"`
	// ttl is represented as a protobuf duration string.
	Ttl *durationpb.Duration `protobuf:"bytes,5,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`
	// payload accepts arbitrary JSON objects.
	Payload *structpb.Struct `protobuf:"bytes,6,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	// items accepts arbitrary JSON arrays.
	Items *structpb.ListValue `protobuf:"bytes,7,opt,name=items,proto3,oneof" json:"items,omitempty"`
	// dynamic accepts arbitrary JSON values.
	Dynamic *structpb.Value `protobuf:"bytes,8,opt,name=dynamic,proto3,oneof" json:"dynamic,omitempty"`
	// note exercises `StringValue` wrapper support.
	Note *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=note,proto3,oneof" json:"note,omitempty"`
	// total exercises Int64Value wrapper support.
	Total *wrapperspb.Int64Value `protobuf:"bytes,10,opt,name=total,proto3,oneof" json:"total,omitempty"`
	// enabled exercises BoolValue wrapper support.
	Enabled *wrapperspb.BoolValue `protobuf:"bytes,11,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	// ratio exercises ProtoJSON float special values.
	Ratio *wrapperspb.DoubleValue `protobuf:"bytes,12,opt,name=ratio,proto3,oneof" json:"ratio,omitempty"`
	// mask exercises FieldMask string support.
	Mask *fieldmaskpb.FieldMask `protobuf:"bytes,13,opt,name=mask,proto3,oneof" json:"mask,omitempty"`
	// blob exercises BytesValue wrapper support.
	Blob *wrapperspb.BytesValue `protobuf:"bytes,15,opt,name=blob,proto3,oneof" json:"blob,omitempty"`
	// small_total exercises Int32Value wrapper support.
	SmallTotal *wrapperspb.Int32Value `protobuf:"bytes,16,opt,name=small_total,json=smallTotal,proto3,oneof" json:"small_total,omitempty"`
	// uint_total exercises UInt32Value wrapper support.
	UintTotal *wrapperspb.UInt32Value `protobuf:"bytes,17,opt,name=uint_total,json=uintTotal,proto3,oneof" json:"uint_total,omitempty"`
	// huge_total exercises UInt64Value wrapper support.
	HugeTotal *wrapperspb.UInt64Value `protobuf:"bytes,18,opt,name=huge_total,json=hugeTotal,proto3,oneof" json:"huge_total,omitempty"`
	// weight exercises FloatValue wrapper support.
	Weight *wrapperspb.FloatValue `protobuf:"bytes,19,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	// raw_ratio exercises raw double ProtoJSON float support.
	RawRatio *float64 `protobuf:"fixed64,20,opt,name=raw_ratio,json=rawRatio,proto3,oneof" json:"raw_ratio,omitempty"`
	// tree exercises recursive message schemas.
	Tree *RecursiveNode `protobuf:"bytes,24,opt,name=tree,proto3,oneof" json:"tree,omitempty"`
	// detail_any exercises Any with a regular embedded message payload.
	// Example: {"@type":"type.googleapis.com/internal.testproto.example.v1.ReportDetails","label":"from-any"}
	DetailAny *anypb.Any `protobuf:"bytes,25,opt,name=detail_any,json=detailAny,proto3,oneof" json:"detail_any,omitempty"`
	// duration_any exercises Any with a well-known embedded payload.
	// Example: {"@type":"type.googleapis.com/google.protobuf.Duration","value":"3600s"}
	DurationAny *anypb.Any `protobuf:"bytes,26,opt,name=duration_any,json=durationAny,proto3,oneof" json:"duration_any,omitempty"`
	// selector exercises top-level oneof support.
	//
	// Types that are valid to be assigned to Selector:
	//
	//	*DescribeAdvancedShapesResponse_CityAlias
	//	*DescribeAdvancedShapesResponse_CityId
	//	*DescribeAdvancedShapesResponse_CityDetails
	Selector      isDescribeAdvancedShapesResponse_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeAdvancedShapesResponse) Reset() {
	*x = DescribeAdvancedShapesResponse{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeAdvancedShapesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeAdvancedShapesResponse) ProtoMessage() {}

func (x *DescribeAdvancedShapesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeAdvancedShapesResponse.ProtoReflect.Descriptor instead.
func (*DescribeAdvancedShapesResponse) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeAdvancedShapesResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetQuantities() map[int32]string {
	if x != nil {
		return x.Quantities
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetToggles() map[bool]string {
	if x != nil {
		return x.Toggles
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetLimits() map[uint64]string {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetItems() *structpb.ListValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetDynamic() *structpb.Value {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetNote() *wrapperspb.StringValue {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetTotal() *wrapperspb.Int64Value {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetRatio() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Ratio
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetBlob() *wrapperspb.BytesValue {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetSmallTotal() *wrapperspb.Int32Value {
	if x != nil {
		return x.SmallTotal
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetUintTotal() *wrapperspb.UInt32Value {
	if x != nil {
		return x.UintTotal
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetHugeTotal() *wrapperspb.UInt64Value {
	if x != nil {
		return x.HugeTotal
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetWeight() *wrapperspb.FloatValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetRawRatio() float64 {
	if x != nil && x.RawRatio != nil {
		return *x.RawRatio
	}
	return 0
}

func (x *DescribeAdvancedShapesResponse) GetTree() *RecursiveNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetDetailAny() *anypb.Any {
	if x != nil {
		return x.DetailAny
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetDurationAny() *anypb.Any {
	if x != nil {
		return x.DurationAny
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetSelector() isDescribeAdvancedShapesResponse_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *DescribeAdvancedShapesResponse) GetCityAlias() string {
	if x != nil {
		if x, ok := x.Selector.(*DescribeAdvancedShapesResponse_CityAlias); ok {
			return x.CityAlias
		}
	}
	return ""
}

func (x *DescribeAdvancedShapesResponse) GetCityId() int64 {
	if x != nil {
		if x, ok := x.Selector.(*DescribeAdvancedShapesResponse_CityId); ok {
			return x.CityId
		}
	}
	return 0
}

func (x *DescribeAdvancedShapesResponse) GetCityDetails() *ReportDetails {
	if x != nil {
		if x, ok := x.Selector.(*DescribeAdvancedShapesResponse_CityDetails); ok {
			return x.CityDetails
		}
	}
	return nil
}

type isDescribeAdvancedShapesResponse_Selector interface {
	isDescribeAdvancedShapesResponse_Selector()
}

type DescribeAdvancedShapesResponse_CityAlias struct {
	// city_alias exercises string oneof members.
	CityAlias string `protobuf:"bytes,21,opt,name=city_alias,json=cityAlias,proto3,oneof"`
}

type DescribeAdvancedShapesResponse_CityId struct {
	// city_id exercises int64 oneof members with ProtoJSON string encoding.
	CityId int64 `protobuf:"varint,22,opt,name=city_id,json=cityId,proto3,oneof"`
}

type DescribeAdvancedShapesResponse_CityDetails struct {
	// city_details exercises message oneof members.
	CityDetails *ReportDetails `protobuf:"bytes,23,opt,name=city_details,json=cityDetails,proto3,oneof"`
}

func (*DescribeAdvancedShapesResponse_CityAlias) isDescribeAdvancedShapesResponse_Selector() {}

func (*DescribeAdvancedShapesResponse_CityId) isDescribeAdvancedShapesResponse_Selector() {}

func (*DescribeAdvancedShapesResponse_CityDetails) isDescribeAdvancedShapesResponse_Selector() {}

// DescribeScalarShapesRequest exercises plain protobuf scalar kinds.
type DescribeScalarShapesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bool_flag exercises the plain bool kind.
	BoolFlag bool `protobuf:"varint,1,opt,name=bool_flag,json=boolFlag,proto3" json:"bool_flag,omitempty"`
	// text_value exercises the plain string kind.
	TextValue string `protobuf:"bytes,2,opt,name=text_value,json=textValue,proto3" json:"text_value,omitempty"`
	// bytes_value exercises the plain bytes kind.
	BytesValue []byte `protobuf:"bytes,3,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	// int32_value exercises the plain int32 kind.
	Int32Value int32 `protobuf:"varint,4,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	// sint32_value exercises the plain sint32 kind.
	Sint32Value int32 `protobuf:"zigzag32,5,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	// sfixed32_value exercises the plain sfixed32 kind.
	Sfixed32Value int32 `protobuf:"fixed32,6,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	// uint32_value exercises the plain uint32 kind.
	Uint32Value uint32 `protobuf:"varint,7,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	// fixed32_value exercises the plain fixed32 kind.
	Fixed32Value uint32 `protobuf:"fixed32,8,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	// int64_value exercises the plain int64 kind.
	Int64Value int64 `protobuf:"varint,9,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	// sint64_value exercises the plain sint64 kind.
	Sint64Value int64 `protobuf:"zigzag64,10,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	// sfixed64_value exercises the plain sfixed64 kind.
	Sfixed64Value int64 `protobuf:"fixed64,11,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	// uint64_value exercises the plain uint64 kind.
	Uint64Value uint64 `protobuf:"varint,12,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	// fixed64_value exercises the plain fixed64 kind.
	Fixed64Value uint64 `protobuf:"fixed64,13,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	// float_value exercises the plain float kind.
	FloatValue float32 `protobuf:"fixed32,14,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	// double_value exercises the plain double kind.
	DoubleValue float64 `protobuf:"fixed64,15,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	// status exercises plain enum handling.
	Status ReportStatus `protobuf:"varint,16,opt,name=status,proto3,enum=internal.testproto.example.v1.ReportStatus" json:"status,omitempty"`
	// details exercises plain nested message handling.
	Details *ReportDetails `protobuf:"bytes,17,opt,name=details,proto3" json:"details,omitempty"`
	// samples exercises repeated plain scalar handling.
	Samples []int32 `protobuf:"varint,18,rep,packed,name=samples,proto3" json:"samples,omitempty"`
	// optional_bool_flag exercises proto3 optional bool.
	OptionalBoolFlag *bool `protobuf:"varint,19,opt,name=optional_bool_flag,json=optionalBoolFlag,proto3,oneof" json:"optional_bool_flag,omitempty"`
	// optional_text_value exercises proto3 optional string.
	OptionalTextValue *string `protobuf:"bytes,20,opt,name=optional_text_value,json=optionalTextValue,proto3,oneof" json:"optional_text_value,omitempty"`
	// optional_bytes_value exercises proto3 optional bytes.
	OptionalBytesValue []byte `protobuf:"bytes,21,opt,name=optional_bytes_value,json=optionalBytesValue,proto3,oneof" json:"optional_bytes_value,omitempty"`
	// optional_int32_value exercises proto3 optional int32.
	OptionalInt32Value *int32 `protobuf:"varint,22,opt,name=optional_int32_value,json=optionalInt32Value,proto3,oneof" json:"optional_int32_value,omitempty"`
	// optional_sint32_value exercises proto3 optional sint32.
	OptionalSint32Value *int32 `protobuf:"zigzag32,23,opt,name=optional_sint32_value,json=optionalSint32Value,proto3,oneof" json:"optional_sint32_value,omitempty"`
	// optional_sfixed32_value exercises proto3 optional sfixed32.
	OptionalSfixed32Value *int32 `protobuf:"fixed32,24,opt,name=optional_sfixed32_value,json=optionalSfixed32Value,proto3,oneof" json:"optional_sfixed32_value,omitempty"`
	// optional_uint32_value exercises proto3 optional uint32.
	OptionalUint32Value *uint32 `protobuf:"varint,25,opt,name=optional_uint32_value,json=optionalUint32Value,proto3,oneof" json:"optional_uint32_value,omitempty"`
	// optional_fixed32_value exercises proto3 optional fixed32.
	OptionalFixed32Value *uint32 `protobuf:"fixed32,26,opt,name=optional_fixed32_value,json=optionalFixed32Value,proto3,oneof" json:"optional_fixed32_value,omitempty"`
	// optional_int64_value exercises proto3 optional int64.
	OptionalInt64Value *int64 `protobuf:"varint,27,opt,name=optional_int64_value,json=optionalInt64Value,proto3,oneof" json:"optional_int64_value,omitempty"`
	// optional_sint64_value exercises proto3 optional sint64.
	OptionalSint64Value *int64 `protobuf:"zigzag64,28,opt,name=optional_sint64_value,json=optionalSint64Value,proto3,oneof" json:"optional_sint64_value,omitempty"`
	// optional_sfixed64_value exercises proto3 optional sfixed64.
	OptionalSfixed64Value *int64 `protobuf:"fixed64,29,opt,name=optional_sfixed64_value,json=optionalSfixed64Value,proto3,oneof" json:"optional_sfixed64_value,omitempty"`
	// optional_uint64_value exercises proto3 optional uint64.
	OptionalUint64Value *uint64 `protobuf:"varint,30,opt,name=optional_uint64_value,json=optionalUint64Value,proto3,oneof" json:"optional_uint64_value,omitempty"`
	// optional_fixed64_value exercises proto3 optional fixed64.
	OptionalFixed64Value *uint64 `protobuf:"fixed64,31,opt,name=optional_fixed64_value,json=optionalFixed64Value,proto3,oneof" json:"optional_fixed64_value,omitempty"`
	// optional_float_value exercises proto3 optional float.
	OptionalFloatValue *float32 `protobuf:"fixed32,32,opt,name=optional_float_value,json=optionalFloatValue,proto3,oneof" json:"optional_float_value,omitempty"`
	// optional_double_value exercises proto3 optional double.
	OptionalDoubleValue *float64 `protobuf:"fixed64,33,opt,name=optional_double_value,json=optionalDoubleValue,proto3,oneof" json:"optional_double_value,omitempty"`
	// optional_status exercises proto3 optional enum.
	OptionalStatus *ReportStatus `protobuf:"varint,34,opt,name=optional_status,json=optionalStatus,proto3,enum=internal.testproto.example.v1.ReportStatus,oneof" json:"optional_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeScalarShapesRequest) Reset() {
	*x = DescribeScalarShapesRequest{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeScalarShapesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeScalarShapesRequest) ProtoMessage() {}

func (x *DescribeScalarShapesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeScalarShapesRequest.ProtoReflect.Descriptor instead.
func (*DescribeScalarShapesRequest) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{8}
}

func (x *DescribeScalarShapesRequest) GetBoolFlag() bool {
	if x != nil {
		return x.BoolFlag
	}
	return false
}

func (x *DescribeScalarShapesRequest) GetTextValue() string {
	if x != nil {
		return x.TextValue
	}
	return ""
}

func (x *DescribeScalarShapesRequest) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *DescribeScalarShapesRequest) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_NONE
}

func (x *DescribeScalarShapesRequest) GetDetails() *ReportDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *DescribeScalarShapesRequest) GetSamples() []int32 {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *DescribeScalarShapesRequest) GetOptionalBoolFlag() bool {
	if x != nil && x.OptionalBoolFlag != nil {
		return *x.OptionalBoolFlag
	}
	return false
}

func (x *DescribeScalarShapesRequest) GetOptionalTextValue() string {
	if x != nil && x.OptionalTextValue != nil {
		return *x.OptionalTextValue
	}
	return ""
}

func (x *DescribeScalarShapesRequest) GetOptionalBytesValue() []byte {
	if x != nil {
		return x.OptionalBytesValue
	}
	return nil
}

func (x *DescribeScalarShapesRequest) GetOptionalInt32Value() int32 {
	if x != nil && x.OptionalInt32Value != nil {
		return *x.OptionalInt32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalSint32Value() int32 {
	if x != nil && x.OptionalSint32Value != nil {
		return *x.OptionalSint32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalSfixed32Value() int32 {
	if x != nil && x.OptionalSfixed32Value != nil {
		return *x.OptionalSfixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalUint32Value() uint32 {
	if x != nil && x.OptionalUint32Value != nil {
		return *x.OptionalUint32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalFixed32Value() uint32 {
	if x != nil && x.OptionalFixed32Value != nil {
		return *x.OptionalFixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalInt64Value() int64 {
	if x != nil && x.OptionalInt64Value != nil {
		return *x.OptionalInt64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalSint64Value() int64 {
	if x != nil && x.OptionalSint64Value != nil {
		return *x.OptionalSint64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalSfixed64Value() int64 {
	if x != nil && x.OptionalSfixed64Value != nil {
		return *x.OptionalSfixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalUint64Value() uint64 {
	if x != nil && x.OptionalUint64Value != nil {
		return *x.OptionalUint64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalFixed64Value() uint64 {
	if x != nil && x.OptionalFixed64Value != nil {
		return *x.OptionalFixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalFloatValue() float32 {
	if x != nil && x.OptionalFloatValue != nil {
		return *x.OptionalFloatValue
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalDoubleValue() float64 {
	if x != nil && x.OptionalDoubleValue != nil {
		return *x.OptionalDoubleValue
	}
	return 0
}

func (x *DescribeScalarShapesRequest) GetOptionalStatus() ReportStatus {
	if x != nil && x.OptionalStatus != nil {
		return *x.OptionalStatus
	}
	return ReportStatus_REPORT_STATUS_NONE
}

// DescribeScalarShapesResponse echoes plain protobuf scalar kinds.
type DescribeScalarShapesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bool_flag echoes the plain bool kind.
	BoolFlag bool `protobuf:"varint,1,opt,name=bool_flag,json=boolFlag,proto3" json:"bool_flag,omitempty"`
	// text_value echoes the plain string kind.
	TextValue string `protobuf:"bytes,2,opt,name=text_value,json=textValue,proto3" json:"text_value,omitempty"`
	// bytes_value echoes the plain bytes kind.
	BytesValue []byte `protobuf:"bytes,3,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	// int32_value echoes the plain int32 kind.
	Int32Value int32 `protobuf:"varint,4,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	// sint32_value echoes the plain sint32 kind.
	Sint32Value int32 `protobuf:"zigzag32,5,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	// sfixed32_value echoes the plain sfixed32 kind.
	Sfixed32Value int32 `protobuf:"fixed32,6,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	// uint32_value echoes the plain uint32 kind.
	Uint32Value uint32 `protobuf:"varint,7,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	// fixed32_value echoes the plain fixed32 kind.
	Fixed32Value uint32 `protobuf:"fixed32,8,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	// int64_value echoes the plain int64 kind.
	Int64Value int64 `protobuf:"varint,9,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	// sint64_value echoes the plain sint64 kind.
	Sint64Value int64 `protobuf:"zigzag64,10,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	// sfixed64_value echoes the plain sfixed64 kind.
	Sfixed64Value int64 `protobuf:"fixed64,11,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	// uint64_value echoes the plain uint64 kind.
	Uint64Value uint64 `protobuf:"varint,12,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	// fixed64_value echoes the plain fixed64 kind.
	Fixed64Value uint64 `protobuf:"fixed64,13,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	// float_value echoes the plain float kind.
	FloatValue float32 `protobuf:"fixed32,14,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	// double_value echoes the plain double kind.
	DoubleValue float64 `protobuf:"fixed64,15,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	// status echoes plain enum handling.
	Status ReportStatus `protobuf:"varint,16,opt,name=status,proto3,enum=internal.testproto.example.v1.ReportStatus" json:"status,omitempty"`
	// details echoes plain nested message handling.
	Details *ReportDetails `protobuf:"bytes,17,opt,name=details,proto3" json:"details,omitempty"`
	// samples echoes repeated plain scalar handling.
	Samples []int32 `protobuf:"varint,18,rep,packed,name=samples,proto3" json:"samples,omitempty"`
	// optional_bool_flag echoes proto3 optional bool.
	OptionalBoolFlag *bool `protobuf:"varint,19,opt,name=optional_bool_flag,json=optionalBoolFlag,proto3,oneof" json:"optional_bool_flag,omitempty"`
	// optional_text_value echoes proto3 optional string.
	OptionalTextValue *string `protobuf:"bytes,20,opt,name=optional_text_value,json=optionalTextValue,proto3,oneof" json:"optional_text_value,omitempty"`
	// optional_bytes_value echoes proto3 optional bytes.
	OptionalBytesValue []byte `protobuf:"bytes,21,opt,name=optional_bytes_value,json=optionalBytesValue,proto3,oneof" json:"optional_bytes_value,omitempty"`
	// optional_int32_value echoes proto3 optional int32.
	OptionalInt32Value *int32 `protobuf:"varint,22,opt,name=optional_int32_value,json=optionalInt32Value,proto3,oneof" json:"optional_int32_value,omitempty"`
	// optional_sint32_value echoes proto3 optional sint32.
	OptionalSint32Value *int32 `protobuf:"zigzag32,23,opt,name=optional_sint32_value,json=optionalSint32Value,proto3,oneof" json:"optional_sint32_value,omitempty"`
	// optional_sfixed32_value echoes proto3 optional sfixed32.
	OptionalSfixed32Value *int32 `protobuf:"fixed32,24,opt,name=optional_sfixed32_value,json=optionalSfixed32Value,proto3,oneof" json:"optional_sfixed32_value,omitempty"`
	// optional_uint32_value echoes proto3 optional uint32.
	OptionalUint32Value *uint32 `protobuf:"varint,25,opt,name=optional_uint32_value,json=optionalUint32Value,proto3,oneof" json:"optional_uint32_value,omitempty"`
	// optional_fixed32_value echoes proto3 optional fixed32.
	OptionalFixed32Value *uint32 `protobuf:"fixed32,26,opt,name=optional_fixed32_value,json=optionalFixed32Value,proto3,oneof" json:"optional_fixed32_value,omitempty"`
	// optional_int64_value echoes proto3 optional int64.
	OptionalInt64Value *int64 `protobuf:"varint,27,opt,name=optional_int64_value,json=optionalInt64Value,proto3,oneof" json:"optional_int64_value,omitempty"`
	// optional_sint64_value echoes proto3 optional sint64.
	OptionalSint64Value *int64 `protobuf:"zigzag64,28,opt,name=optional_sint64_value,json=optionalSint64Value,proto3,oneof" json:"optional_sint64_value,omitempty"`
	// optional_sfixed64_value echoes proto3 optional sfixed64.
	OptionalSfixed64Value *int64 `protobuf:"fixed64,29,opt,name=optional_sfixed64_value,json=optionalSfixed64Value,proto3,oneof" json:"optional_sfixed64_value,omitempty"`
	// optional_uint64_value echoes proto3 optional uint64.
	OptionalUint64Value *uint64 `protobuf:"varint,30,opt,name=optional_uint64_value,json=optionalUint64Value,proto3,oneof" json:"optional_uint64_value,omitempty"`
	// optional_fixed64_value echoes proto3 optional fixed64.
	OptionalFixed64Value *uint64 `protobuf:"fixed64,31,opt,name=optional_fixed64_value,json=optionalFixed64Value,proto3,oneof" json:"optional_fixed64_value,omitempty"`
	// optional_float_value echoes proto3 optional float.
	OptionalFloatValue *float32 `protobuf:"fixed32,32,opt,name=optional_float_value,json=optionalFloatValue,proto3,oneof" json:"optional_float_value,omitempty"`
	// optional_double_value echoes proto3 optional double.
	OptionalDoubleValue *float64 `protobuf:"fixed64,33,opt,name=optional_double_value,json=optionalDoubleValue,proto3,oneof" json:"optional_double_value,omitempty"`
	// optional_status echoes proto3 optional enum.
	OptionalStatus *ReportStatus `protobuf:"varint,34,opt,name=optional_status,json=optionalStatus,proto3,enum=internal.testproto.example.v1.ReportStatus,oneof" json:"optional_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeScalarShapesResponse) Reset() {
	*x = DescribeScalarShapesResponse{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeScalarShapesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeScalarShapesResponse) ProtoMessage() {}

func (x *DescribeScalarShapesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeScalarShapesResponse.ProtoReflect.Descriptor instead.
func (*DescribeScalarShapesResponse) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{9}
}

func (x *DescribeScalarShapesResponse) GetBoolFlag() bool {
	if x != nil {
		return x.BoolFlag
	}
	return false
}

func (x *DescribeScalarShapesResponse) GetTextValue() string {
	if x != nil {
		return x.TextValue
	}
	return ""
}

func (x *DescribeScalarShapesResponse) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *DescribeScalarShapesResponse) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_NONE
}

func (x *DescribeScalarShapesResponse) GetDetails() *ReportDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *DescribeScalarShapesResponse) GetSamples() []int32 {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *DescribeScalarShapesResponse) GetOptionalBoolFlag() bool {
	if x != nil && x.OptionalBoolFlag != nil {
		return *x.OptionalBoolFlag
	}
	return false
}

func (x *DescribeScalarShapesResponse) GetOptionalTextValue() string {
	if x != nil && x.OptionalTextValue != nil {
		return *x.OptionalTextValue
	}
	return ""
}

func (x *DescribeScalarShapesResponse) GetOptionalBytesValue() []byte {
	if x != nil {
		return x.OptionalBytesValue
	}
	return nil
}

func (x *DescribeScalarShapesResponse) GetOptionalInt32Value() int32 {
	if x != nil && x.OptionalInt32Value != nil {
		return *x.OptionalInt32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalSint32Value() int32 {
	if x != nil && x.OptionalSint32Value != nil {
		return *x.OptionalSint32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalSfixed32Value() int32 {
	if x != nil && x.OptionalSfixed32Value != nil {
		return *x.OptionalSfixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalUint32Value() uint32 {
	if x != nil && x.OptionalUint32Value != nil {
		return *x.OptionalUint32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalFixed32Value() uint32 {
	if x != nil && x.OptionalFixed32Value != nil {
		return *x.OptionalFixed32Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalInt64Value() int64 {
	if x != nil && x.OptionalInt64Value != nil {
		return *x.OptionalInt64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalSint64Value() int64 {
	if x != nil && x.OptionalSint64Value != nil {
		return *x.OptionalSint64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalSfixed64Value() int64 {
	if x != nil && x.OptionalSfixed64Value != nil {
		return *x.OptionalSfixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalUint64Value() uint64 {
	if x != nil && x.OptionalUint64Value != nil {
		return *x.OptionalUint64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalFixed64Value() uint64 {
	if x != nil && x.OptionalFixed64Value != nil {
		return *x.OptionalFixed64Value
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalFloatValue() float32 {
	if x != nil && x.OptionalFloatValue != nil {
		return *x.OptionalFloatValue
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalDoubleValue() float64 {
	if x != nil && x.OptionalDoubleValue != nil {
		return *x.OptionalDoubleValue
	}
	return 0
}

func (x *DescribeScalarShapesResponse) GetOptionalStatus() ReportStatus {
	if x != nil && x.OptionalStatus != nil {
		return *x.OptionalStatus
	}
	return ReportStatus_REPORT_STATUS_NONE
}

// ReportDetails contains nested report options.
type ReportDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is an arbitrary label.
	Label         string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDetails) Reset() {
	*x = ReportDetails{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDetails) ProtoMessage() {}

func (x *ReportDetails) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDetails.ProtoReflect.Descriptor instead.
func (*ReportDetails) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{10}
}

func (x *ReportDetails) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// RecursiveNode exercises recursive message schemas.
type RecursiveNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the current node.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// child points at the next recursive node.
	Child *RecursiveNode `protobuf:"bytes,2,opt,name=child,proto3,oneof" json:"child,omitempty"`
	// children holds repeated recursive nodes.
	Children      []*RecursiveNode `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecursiveNode) Reset() {
	*x = RecursiveNode{}
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveNode) ProtoMessage() {}

func (x *RecursiveNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_example_v1_example_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveNode.ProtoReflect.Descriptor instead.
func (*RecursiveNode) Descriptor() ([]byte, []int) {
	return file_internal_testproto_example_v1_example_proto_rawDescGZIP(), []int{11}
}

func (x *RecursiveNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecursiveNode) GetChild() *RecursiveNode {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *RecursiveNode) GetChildren() []*RecursiveNode {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_internal_testproto_example_v1_example_proto protoreflect.FileDescriptor

const file_internal_testproto_example_v1_example_proto_rawDesc = "" +
	"\n" +
	"+internal/testproto/example/v1/example.proto\x12\x1dinternal.testproto.example.v1\x1a\x1cmcp/options/v1/options.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa9\x02\n" +
	"\x13CreateReportRequest\x12C\n" +
	"\x04city\x18\x01 \x01(\tB/ڷ,+\n" +
	"\n" +
	"City name.\x1a\a\n" +
	"\x05Paris\x1a\b\n" +
	"\x06LondonR\x06^[A-Z]`\x01hdR\x04city\x129\n" +
	"\x05count\x18\x02 \x01(\x05B#ڷ,\x1f\"\t\x11\x00\x00\x00\x00\x00\x00$@\xa1\x01\x00\x00\x00\x00\x00\x00\xf0?\xa9\x01\x00\x00\x00\x00\x00@\x8f@R\x05count\x12F\n" +
	"\adetails\x18\x03 \x01(\v2,.internal.testproto.example.v1.ReportDetailsR\adetails\x12\x19\n" +
	"\x05units\x18\x04 \x01(\tH\x00R\x05units\x88\x01\x01\x12%\n" +
	"\x06labels\x18\x05 \x03(\tB\rڷ,\t\xf0\x01\x01\xf8\x012\x80\x02\x01R\x06labelsB\b\n" +
	"\x06_units\"\xfd\x01\n" +
	"\x14CreateReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12C\n" +
	"\x06status\x18\x03 \x01(\x0e2+.internal.testproto.example.v1.ReportStatusR\x06status\x12F\n" +
	"\adetails\x18\x04 \x01(\v2,.internal.testproto.example.v1.ReportDetailsR\adetails\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"(\n" +
	"\x12HiddenThingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13HiddenThingResponse\"\r\n" +
	"\vPingRequest\"8\n" +
	"\fPingResponse\x12(\n" +
	"\x03ack\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x03ack\"\xf1\x10\n" +
	"\x1dDescribeAdvancedShapesRequest\x12`\n" +
	"\x06labels\x18\x01 \x03(\v2H.internal.testproto.example.v1.DescribeAdvancedShapesRequest.LabelsEntryR\x06labels\x12l\n" +
	"\n" +
	"quantities\x18\x02 \x03(\v2L.internal.testproto.example.v1.DescribeAdvancedShapesRequest.QuantitiesEntryR\n" +
	"quantities\x12c\n" +
	"\atoggles\x18\x03 \x03(\v2I.internal.testproto.example.v1.DescribeAdvancedShapesRequest.TogglesEntryR\atoggles\x12`\n" +
	"\x06limits\x18\x0e \x03(\v2H.internal.testproto.example.v1.DescribeAdvancedShapesRequest.LimitsEntryR\x06limits\x12@\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"observedAt\x88\x01\x01\x120\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x02R\x03ttl\x88\x01\x01\x126\n" +
	"\apayload\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x03R\apayload\x88\x01\x01\x125\n" +
	"\x05items\x18\a \x01(\v2\x1a.google.protobuf.ListValueH\x04R\x05items\x88\x01\x01\x125\n" +
	"\adynamic\x18\b \x01(\v2\x16.google.protobuf.ValueH\x05R\adynamic\x88\x01\x01\x125\n" +
	"\x04note\x18\t \x01(\v2\x1c.google.protobuf.StringValueH\x06R\x04note\x88\x01\x01\x126\n" +
	"\x05total\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int64ValueH\aR\x05total\x88\x01\x01\x129\n" +
	"\aenabled\x18\v \x01(\v2\x1a.google.protobuf.BoolValueH\bR\aenabled\x88\x01\x01\x127\n" +
	"\x05ratio\x18\f \x01(\v2\x1c.google.protobuf.DoubleValueH\tR\x05ratio\x88\x01\x01\x123\n" +
	"\x04mask\x18\r \x01(\v2\x1a.google.protobuf.FieldMaskH\n" +
	"R\x04mask\x88\x01\x01\x124\n" +
	"\x04blob\x18\x0f \x01(\v2\x1b.google.protobuf.BytesValueH\vR\x04blob\x88\x01\x01\x12A\n" +
	"\vsmall_total\x18\x10 \x01(\v2\x1b.google.protobuf.Int32ValueH\fR\n" +
	"smallTotal\x88\x01\x01\x12@\n" +
	"\n" +
	"uint_total\x18\x11 \x01(\v2\x1c.google.protobuf.UInt32ValueH\rR\tuintTotal\x88\x01\x01\x12@\n" +
	"\n" +
	"huge_total\x18\x12 \x01(\v2\x1c.google.protobuf.UInt64ValueH\x0eR\thugeTotal\x88\x01\x01\x128\n" +
	"\x06weight\x18\x13 \x01(\v2\x1b.google.protobuf.FloatValueH\x0fR\x06weight\x88\x01\x01\x12 \n" +
	"\traw_ratio\x18\x14 \x01(\x01H\x10R\brawRatio\x88\x01\x01\x12E\n" +
	"\x04tree\x18\x18 \x01(\v2,.internal.testproto.example.v1.RecursiveNodeH\x11R\x04tree\x88\x01\x01\x128\n" +
	"\n" +
	"detail_any\x18\x19 \x01(\v2\x14.google.protobuf.AnyH\x12R\tdetailAny\x88\x01\x01\x12<\n" +
	"\fduration_any\x18\x1a \x01(\v2\x14.google.protobuf.AnyH\x13R\vdurationAny\x88\x01\x01\x12\x1f\n" +
	"\n" +
	"city_alias\x18\x15 \x01(\tH\x00R\tcityAlias\x12\x19\n" +
	"\acity_id\x18\x16 \x01(\x03H\x00R\x06cityId\x12Q\n" +
	"\fcity_details\x18\x17 \x01(\v2,.internal.testproto.example.v1.ReportDetailsH\x00R\vcityDetails\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fQuantitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fTogglesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\bselectorB\x0e\n" +
	"\f_observed_atB\x06\n" +
	"\x04_ttlB\n" +
	"\n" +
	"\b_payloadB\b\n" +
	"\x06_itemsB\n" +
	"\n" +
	"\b_dynamicB\a\n" +
	"\x05_noteB\b\n" +
	"\x06_totalB\n" +
	"\n" +
	"\b_enabledB\b\n" +
	"\x06_ratioB\a\n" +
	"\x05_maskB\a\n" +
	"\x05_blobB\x0e\n" +
	"\f_small_totalB\r\n" +
	"\v_uint_totalB\r\n" +
	"\v_huge_totalB\t\n" +
	"\a_weightB\f\n" +
	"\n" +
	"_raw_ratioB\a\n" +
	"\x05_treeB\r\n" +
	"\v_detail_anyB\x0f\n" +
	"\r_duration_any\"\xf6\x10\n" +
	"\x1eDescribeAdvancedShapesResponse\x12a\n" +
	"\x06labels\x18\x01 \x03(\v2I.internal.testproto.example.v1.DescribeAdvancedShapesResponse.LabelsEntryR\x06labels\x12m\n" +
	"\n" +
	"quantities\x18\x02 \x03(\v2M.internal.testproto.example.v1.DescribeAdvancedShapesResponse.QuantitiesEntryR\n" +
	"quantities\x12d\n" +
	"\atoggles\x18\x03 \x03(\v2J.internal.testproto.example.v1.DescribeAdvancedShapesResponse.TogglesEntryR\atoggles\x12a\n" +
	"\x06limits\x18\x0e \x03(\v2I.internal.testproto.example.v1.DescribeAdvancedShapesResponse.LimitsEntryR\x06limits\x12@\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"observedAt\x88\x01\x01\x120\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x02R\x03ttl\x88\x01\x01\x126\n" +
	"\apayload\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x03R\apayload\x88\x01\x01\x125\n" +
	"\x05items\x18\a \x01(\v2\x1a.google.protobuf.ListValueH\x04R\x05items\x88\x01\x01\x125\n" +
	"\adynamic\x18\b \x01(\v2\x16.google.protobuf.ValueH\x05R\adynamic\x88\x01\x01\x125\n" +
	"\x04note\x18\t \x01(\v2\x1c.google.protobuf.StringValueH\x06R\x04note\x88\x01\x01\x126\n" +
	"\x05total\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int64ValueH\aR\x05total\x88\x01\x01\x129\n" +
	"\aenabled\x18\v \x01(\v2\x1a.google.protobuf.BoolValueH\bR\aenabled\x88\x01\x01\x127\n" +
	"\x05ratio\x18\f \x01(\v2\x1c.google.protobuf.DoubleValueH\tR\x05ratio\x88\x01\x01\x123\n" +
	"\x04mask\x18\r \x01(\v2\x1a.google.protobuf.FieldMaskH\n" +
	"R\x04mask\x88\x01\x01\x124\n" +
	"\x04blob\x18\x0f \x01(\v2\x1b.google.protobuf.BytesValueH\vR\x04blob\x88\x01\x01\x12A\n" +
	"\vsmall_total\x18\x10 \x01(\v2\x1b.google.protobuf.Int32ValueH\fR\n" +
	"smallTotal\x88\x01\x01\x12@\n" +
	"\n" +
	"uint_total\x18\x11 \x01(\v2\x1c.google.protobuf.UInt32ValueH\rR\tuintTotal\x88\x01\x01\x12@\n" +
	"\n" +
	"huge_total\x18\x12 \x01(\v2\x1c.google.protobuf.UInt64ValueH\x0eR\thugeTotal\x88\x01\x01\x128\n" +
	"\x06weight\x18\x13 \x01(\v2\x1b.google.protobuf.FloatValueH\x0fR\x06weight\x88\x01\x01\x12 \n" +
	"\traw_ratio\x18\x14 \x01(\x01H\x10R\brawRatio\x88\x01\x01\x12E\n" +
	"\x04tree\x18\x18 \x01(\v2,.internal.testproto.example.v1.RecursiveNodeH\x11R\x04tree\x88\x01\x01\x128\n" +
	"\n" +
	"detail_any\x18\x19 \x01(\v2\x14.google.protobuf.AnyH\x12R\tdetailAny\x88\x01\x01\x12<\n" +
	"\fduration_any\x18\x1a \x01(\v2\x14.google.protobuf.AnyH\x13R\vdurationAny\x88\x01\x01\x12\x1f\n" +
	"\n" +
	"city_alias\x18\x15 \x01(\tH\x00R\tcityAlias\x12\x19\n" +
	"\acity_id\x18\x16 \x01(\x03H\x00R\x06cityId\x12Q\n" +
	"\fcity_details\x18\x17 \x01(\v2,.internal.testproto.example.v1.ReportDetailsH\x00R\vcityDetails\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fQuantitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fTogglesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\bselectorB\x0e\n" +
	"\f_observed_atB\x06\n" +
	"\x04_ttlB\n" +
	"\n" +
	"\b_payloadB\b\n" +
	"\x06_itemsB\n" +
	"\n" +
	"\b_dynamicB\a\n" +
	"\x05_noteB\b\n" +
	"\x06_totalB\n" +
	"\n" +
	"\b_enabledB\b\n" +
	"\x06_ratioB\a\n" +
	"\x05_maskB\a\n" +
	"\x05_blobB\x0e\n" +
	"\f_small_totalB\r\n" +
	"\v_uint_totalB\r\n" +
	"\v_huge_totalB\t\n" +
	"\a_weightB\f\n" +
	"\n" +
	"_raw_ratioB\a\n" +
	"\x05_treeB\r\n" +
	"\v_detail_anyB\x0f\n" +
	"\r_duration_any\"\x8e\x10\n" +
	"\x1bDescribeScalarShapesRequest\x12\x1b\n" +
	"\tbool_flag\x18\x01 \x01(\bR\bboolFlag\x12\x1d\n" +
	"\n" +
	"text_value\x18\x02 \x01(\tR\ttextValue\x12\x1f\n" +
	"\vbytes_value\x18\x03 \x01(\fR\n" +
	"bytesValue\x12\x1f\n" +
	"\vint32_value\x18\x04 \x01(\x05R\n" +
	"int32Value\x12!\n" +
	"\fsint32_value\x18\x05 \x01(\x11R\vsint32Value\x12%\n" +
	"\x0esfixed32_value\x18\x06 \x01(\x0fR\rsfixed32Value\x12!\n" +
	"\fuint32_value\x18\a \x01(\rR\vuint32Value\x12#\n" +
	"\rfixed32_value\x18\b \x01(\aR\ffixed32Value\x12\x1f\n" +
	"\vint64_value\x18\t \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fsint64_value\x18\n" +
	" \x01(\x12R\vsint64Value\x12%\n" +
	"\x0esfixed64_value\x18\v \x01(\x10R\rsfixed64Value\x12!\n" +
	"\fuint64_value\x18\f \x01(\x04R\vuint64Value\x12#\n" +
	"\rfixed64_value\x18\r \x01(\x06R\ffixed64Value\x12\x1f\n" +
	"\vfloat_value\x18\x0e \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\x0f \x01(\x01R\vdoubleValue\x12C\n" +
	"\x06status\x18\x10 \x01(\x0e2+.internal.testproto.example.v1.ReportStatusR\x06status\x12F\n" +
	"\adetails\x18\x11 \x01(\v2,.internal.testproto.example.v1.ReportDetailsR\adetails\x12\x18\n" +
	"\asamples\x18\x12 \x03(\x05R\asamples\x121\n" +
	"\x12optional_bool_flag\x18\x13 \x01(\bH\x00R\x10optionalBoolFlag\x88\x01\x01\x123\n" +
	"\x13optional_text_value\x18\x14 \x01(\tH\x01R\x11optionalTextValue\x88\x01\x01\x125\n" +
	"\x14optional_bytes_value\x18\x15 \x01(\fH\x02R\x12optionalBytesValue\x88\x01\x01\x125\n" +
	"\x14optional_int32_value\x18\x16 \x01(\x05H\x03R\x12optionalInt32Value\x88\x01\x01\x127\n" +
	"\x15optional_sint32_value\x18\x17 \x01(\x11H\x04R\x13optionalSint32Value\x88\x01\x01\x12;\n" +
	"\x17optional_sfixed32_value\x18\x18 \x01(\x0fH\x05R\x15optionalSfixed32Value\x88\x01\x01\x127\n" +
	"\x15optional_uint32_value\x18\x19 \x01(\rH\x06R\x13optionalUint32Value\x88\x01\x01\x129\n" +
	"\x16optional_fixed32_value\x18\x1a \x01(\aH\aR\x14optionalFixed32Value\x88\x01\x01\x125\n" +
	"\x14optional_int64_value\x18\x1b \x01(\x03H\bR\x12optionalInt64Value\x88\x01\x01\x127\n" +
	"\x15optional_sint64_value\x18\x1c \x01(\x12H\tR\x13optionalSint64Value\x88\x01\x01\x12;\n" +
	"\x17optional_sfixed64_value\x18\x1d \x01(\x10H\n" +
	"R\x15optionalSfixed64Value\x88\x01\x01\x127\n" +
	"\x15optional_uint64_value\x18\x1e \x01(\x04H\vR\x13optionalUint64Value\x88\x01\x01\x129\n" +
	"\x16optional_fixed64_value\x18\x1f \x01(\x06H\fR\x14optionalFixed64Value\x88\x01\x01\x125\n" +
	"\x14optional_float_value\x18  \x01(\x02H\rR\x12optionalFloatValue\x88\x01\x01\x127\n" +
	"\x15optional_double_value\x18! \x01(\x01H\x0eR\x13optionalDoubleValue\x88\x01\x01\x12Y\n" +
	"\x0foptional_status\x18\" \x01(\x0e2+.internal.testproto.example.v1.ReportStatusH\x0fR\x0eoptionalStatus\x88\x01\x01B\x15\n" +
	"\x13_optional_bool_flagB\x16\n" +
	"\x14_optional_text_valueB\x17\n" +
	"\x15_optional_bytes_valueB\x17\n" +
	"\x15_optional_int32_valueB\x18\n" +
	"\x16_optional_sint32_valueB\x1a\n" +
	"\x18_optional_sfixed32_valueB\x18\n" +
	"\x16_optional_uint32_valueB\x19\n" +
	"\x17_optional_fixed32_valueB\x17\n" +
	"\x15_optional_int64_valueB\x18\n" +
	"\x16_optional_sint64_valueB\x1a\n" +
	"\x18_optional_sfixed64_valueB\x18\n" +
	"\x16_optional_uint64_valueB\x19\n" +
	"\x17_optional_fixed64_valueB\x17\n" +
	"\x15_optional_float_valueB\x18\n" +
	"\x16_optional_double_valueB\x12\n" +
	"\x10_optional_status\"\x8f\x10\n" +
	"\x1cDescribeScalarShapesResponse\x12\x1b\n" +
	"\tbool_flag\x18\x01 \x01(\bR\bboolFlag\x12\x1d\n" +
	"\n" +
	"text_value\x18\x02 \x01(\tR\ttextValue\x12\x1f\n" +
	"\vbytes_value\x18\x03 \x01(\fR\n" +
	"bytesValue\x12\x1f\n" +
	"\vint32_value\x18\x04 \x01(\x05R\n" +
	"int32Value\x12!\n" +
	"\fsint32_value\x18\x05 \x01(\x11R\vsint32Value\x12%\n" +
	"\x0esfixed32_value\x18\x06 \x01(\x0fR\rsfixed32Value\x12!\n" +
	"\fuint32_value\x18\a \x01(\rR\vuint32Value\x12#\n" +
	"\rfixed32_value\x18\b \x01(\aR\ffixed32Value\x12\x1f\n" +
	"\vint64_value\x18\t \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fsint64_value\x18\n" +
	" \x01(\x12R\vsint64Value\x12%\n" +
	"\x0esfixed64_value\x18\v \x01(\x10R\rsfixed64Value\x12!\n" +
	"\fuint64_value\x18\f \x01(\x04R\vuint64Value\x12#\n" +
	"\rfixed64_value\x18\r \x01(\x06R\ffixed64Value\x12\x1f\n" +
	"\vfloat_value\x18\x0e \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\x0f \x01(\x01R\vdoubleValue\x12C\n" +
	"\x06status\x18\x10 \x01(\x0e2+.internal.testproto.example.v1.ReportStatusR\x06status\x12F\n" +
	"\adetails\x18\x11 \x01(\v2,.internal.testproto.example.v1.ReportDetailsR\adetails\x12\x18\n" +
	"\asamples\x18\x12 \x03(\x05R\asamples\x121\n" +
	"\x12optional_bool_flag\x18\x13 \x01(\bH\x00R\x10optionalBoolFlag\x88\x01\x01\x123\n" +
	"\x13optional_text_value\x18\x14 \x01(\tH\x01R\x11optionalTextValue\x88\x01\x01\x125\n" +
	"\x14optional_bytes_value\x18\x15 \x01(\fH\x02R\x12optionalBytesValue\x88\x01\x01\x125\n" +
	"\x14optional_int32_value\x18\x16 \x01(\x05H\x03R\x12optionalInt32Value\x88\x01\x01\x127\n" +
	"\x15optional_sint32_value\x18\x17 \x01(\x11H\x04R\x13optionalSint32Value\x88\x01\x01\x12;\n" +
	"\x17optional_sfixed32_value\x18\x18 \x01(\x0fH\x05R\x15optionalSfixed32Value\x88\x01\x01\x127\n" +
	"\x15optional_uint32_value\x18\x19 \x01(\rH\x06R\x13optionalUint32Value\x88\x01\x01\x129\n" +
	"\x16optional_fixed32_value\x18\x1a \x01(\aH\aR\x14optionalFixed32Value\x88\x01\x01\x125\n" +
	"\x14optional_int64_value\x18\x1b \x01(\x03H\bR\x12optionalInt64Value\x88\x01\x01\x127\n" +
	"\x15optional_sint64_value\x18\x1c \x01(\x12H\tR\x13optionalSint64Value\x88\x01\x01\x12;\n" +
	"\x17optional_sfixed64_value\x18\x1d \x01(\x10H\n" +
	"R\x15optionalSfixed64Value\x88\x01\x01\x127\n" +
	"\x15optional_uint64_value\x18\x1e \x01(\x04H\vR\x13optionalUint64Value\x88\x01\x01\x129\n" +
	"\x16optional_fixed64_value\x18\x1f \x01(\x06H\fR\x14optionalFixed64Value\x88\x01\x01\x125\n" +
	"\x14optional_float_value\x18  \x01(\x02H\rR\x12optionalFloatValue\x88\x01\x01\x127\n" +
	"\x15optional_double_value\x18! \x01(\x01H\x0eR\x13optionalDoubleValue\x88\x01\x01\x12Y\n" +
	"\x0foptional_status\x18\" \x01(\x0e2+.internal.testproto.example.v1.ReportStatusH\x0fR\x0eoptionalStatus\x88\x01\x01B\x15\n" +
	"\x13_optional_bool_flagB\x16\n" +
	"\x14_optional_text_valueB\x17\n" +
	"\x15_optional_bytes_valueB\x17\n" +
	"\x15_optional_int32_valueB\x18\n" +
	"\x16_optional_sint32_valueB\x1a\n" +
	"\x18_optional_sfixed32_valueB\x18\n" +
	"\x16_optional_uint32_valueB\x19\n" +
	"\x17_optional_fixed32_valueB\x17\n" +
	"\x15_optional_int64_valueB\x18\n" +
	"\x16_optional_sint64_valueB\x1a\n" +
	"\x18_optional_sfixed64_valueB\x18\n" +
	"\x16_optional_uint64_valueB\x19\n" +
	"\x17_optional_fixed64_valueB\x17\n" +
	"\x15_optional_float_valueB\x18\n" +
	"\x16_optional_double_valueB\x12\n" +
	"\x10_optional_status\"a\n" +
	"\rReportDetails\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label::\xe2\xb7,6\n" +
	"\x0eReport Details\x12$Nested report configuration options.\"\xc0\x01\n" +
	"\rRecursiveNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12G\n" +
	"\x05child\x18\x02 \x01(\v2,.internal.testproto.example.v1.RecursiveNodeH\x00R\x05child\x88\x01\x01\x12H\n" +
	"\bchildren\x18\x03 \x03(\v2,.internal.testproto.example.v1.RecursiveNodeR\bchildrenB\b\n" +
	"\x06_child*\xd8\x01\n" +
	"\fReportStatus\x12\x1e\n" +
	"\x12REPORT_STATUS_NONE\x10\x00\x1a\x06\xf2\xb7,\x02\x10\x01\x12:\n" +
	"\x10REPORT_STATUS_OK\x10\x01\x1a$\xf2\xb7, \n" +
	"\x1eReport completed successfully.\x129\n" +
	"\x14REPORT_STATUS_FAILED\x10\x02\x1a\x1f\xf2\xb7,\x1b\n" +
	"\x19Report generation failed.\x1a1\xea\xb7,-\n" +
	"\rReport Status\x12\x1cCurrent state of the report.2\xfc\x06\n" +
	"\n" +
	"ExampleAPI\x12\xa9\x01\n" +
	"\fCreateReport\x122.internal.testproto.example.v1.CreateReportRequest\x1a3.internal.testproto.example.v1.CreateReportResponse\"0ҷ,,\x12\rCreate report\x1a\x1bCreate a report for a city.\x12{\n" +
	"\x04Ping\x12*.internal.testproto.example.v1.PingRequest\x1a+.internal.testproto.example.v1.PingResponse\"\x1aҷ,\x16\n" +
	"\x06Health\x12\fHealth check\x12\xe3\x01\n" +
	"\x16DescribeAdvancedShapes\x12<.internal.testproto.example.v1.DescribeAdvancedShapesRequest\x1a=.internal.testproto.example.v1.DescribeAdvancedShapesResponse\"Lҷ,H\x12\x18Describe advanced shapes\x1a,Exercise maps and well-known protobuf types.\x12\xd4\x01\n" +
	"\x14DescribeScalarShapes\x12:.internal.testproto.example.v1.DescribeScalarShapesRequest\x1a;.internal.testproto.example.v1.DescribeScalarShapesResponse\"Cҷ,?\x12\x16Describe scalar shapes\x1a%Exercise plain protobuf scalar kinds.\x12y\n" +
	"\vHiddenThing\x121.internal.testproto.example.v1.HiddenThingRequest\x1a2.internal.testproto.example.v1.HiddenThingResponse\"\x03\x88\x02\x01\x1a\rʷ,\t\n" +
	"\aexampleBNZLgithub.com/easyp-tech/protoc-gen-mcp/internal/testproto/example/v1;examplev1b\x06proto3"

var (
	file_internal_testproto_example_v1_example_proto_rawDescOnce sync.Once
	file_internal_testproto_example_v1_example_proto_rawDescData []byte
)

func file_internal_testproto_example_v1_example_proto_rawDescGZIP() []byte {
	file_internal_testproto_example_v1_example_proto_rawDescOnce.Do(func() {
		file_internal_testproto_example_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testproto_example_v1_example_proto_rawDesc), len(file_internal_testproto_example_v1_example_proto_rawDesc)))
	})
	return file_internal_testproto_example_v1_example_proto_rawDescData
}

var file_internal_testproto_example_v1_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_testproto_example_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_testproto_example_v1_example_proto_goTypes = []any{
	(ReportStatus)(0),                      // 0: internal.testproto.example.v1.ReportStatus
	(*CreateReportRequest)(nil),            // 1: internal.testproto.example.v1.CreateReportRequest
	(*CreateReportResponse)(nil),           // 2: internal.testproto.example.v1.CreateReportResponse
	(*HiddenThingRequest)(nil),             // 3: internal.testproto.example.v1.HiddenThingRequest
	(*HiddenThingResponse)(nil),            // 4: internal.testproto.example.v1.HiddenThingResponse
	(*PingRequest)(nil),                    // 5: internal.testproto.example.v1.PingRequest
	(*PingResponse)(nil),                   // 6: internal.testproto.example.v1.PingResponse
	(*DescribeAdvancedShapesRequest)(nil),  // 7: internal.testproto.example.v1.DescribeAdvancedShapesRequest
	(*DescribeAdvancedShapesResponse)(nil), // 8: internal.testproto.example.v1.DescribeAdvancedShapesResponse
	(*DescribeScalarShapesRequest)(nil),    // 9: internal.testproto.example.v1.DescribeScalarShapesRequest
	(*DescribeScalarShapesResponse)(nil),   // 10: internal.testproto.example.v1.DescribeScalarShapesResponse
	(*ReportDetails)(nil),                  // 11: internal.testproto.example.v1.ReportDetails
	(*RecursiveNode)(nil),                  // 12: internal.testproto.example.v1.RecursiveNode
	nil,                                    // 13: internal.testproto.example.v1.DescribeAdvancedShapesRequest.LabelsEntry
	nil,                                    // 14: internal.testproto.example.v1.DescribeAdvancedShapesRequest.QuantitiesEntry
	nil,                                    // 15: internal.testproto.example.v1.DescribeAdvancedShapesRequest.TogglesEntry
	nil,                                    // 16: internal.testproto.example.v1.DescribeAdvancedShapesRequest.LimitsEntry
	nil,                                    // 17: internal.testproto.example.v1.DescribeAdvancedShapesResponse.LabelsEntry
	nil,                                    // 18: internal.testproto.example.v1.DescribeAdvancedShapesResponse.QuantitiesEntry
	nil,                                    // 19: internal.testproto.example.v1.DescribeAdvancedShapesResponse.TogglesEntry
	nil,                                    // 20: internal.testproto.example.v1.DescribeAdvancedShapesResponse.LimitsEntry
	(*emptypb.Empty)(nil),                  // 21: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),          // 22: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),            // 23: google.protobuf.Duration
	(*structpb.Struct)(nil),                // 24: google.protobuf.Struct
	(*structpb.ListValue)(nil),             // 25: google.protobuf.ListValue
	(*structpb.Value)(nil),                 // 26: google.protobuf.Value
	(*wrapperspb.StringValue)(nil),         // 27: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),          // 28: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),           // 29: google.protobuf.BoolValue
	(*wrapperspb.DoubleValue)(nil),         // 30: google.protobuf.DoubleValue
	(*fieldmaskpb.FieldMask)(nil),          // 31: google.protobuf.FieldMask
	(*wrapperspb.BytesValue)(nil),          // 32: google.protobuf.BytesValue
	(*wrapperspb.Int32Value)(nil),          // 33: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil),         // 34: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil),         // 35: google.protobuf.UInt64Value
	(*wrapperspb.FloatValue)(nil),          // 36: google.protobuf.FloatValue
	(*anypb.Any)(nil),                      // 37: google.protobuf.Any
}
var file_internal_testproto_example_v1_example_proto_depIdxs = []int32{
	11, // 0: internal.testproto.example.v1.CreateReportRequest.details:type_name -> internal.testproto.example.v1.ReportDetails
	0,  // 1: internal.testproto.example.v1.CreateReportResponse.status:type_name -> internal.testproto.example.v1.ReportStatus
	11, // 2: internal.testproto.example.v1.CreateReportResponse.details:type_name -> internal.testproto.example.v1.ReportDetails
	21, // 3: internal.testproto.example.v1.PingResponse.ack:type_name -> google.protobuf.Empty
	13, // 4: internal.testproto.example.v1.DescribeAdvancedShapesRequest.labels:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesRequest.LabelsEntry
	14, // 5: internal.testproto.example.v1.DescribeAdvancedShapesRequest.quantities:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesRequest.QuantitiesEntry
	15, // 6: internal.testproto.example.v1.DescribeAdvancedShapesRequest.toggles:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesRequest.TogglesEntry
	16, // 7: internal.testproto.example.v1.DescribeAdvancedShapesRequest.limits:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesRequest.LimitsEntry
	22, // 8: internal.testproto.example.v1.DescribeAdvancedShapesRequest.observed_at:type_name -> google.protobuf.Timestamp
	23, // 9: internal.testproto.example.v1.DescribeAdvancedShapesRequest.ttl:type_name -> google.protobuf.Duration
	24, // 10: internal.testproto.example.v1.DescribeAdvancedShapesRequest.payload:type_name -> google.protobuf.Struct
	25, // 11: internal.testproto.example.v1.DescribeAdvancedShapesRequest.items:type_name -> google.protobuf.ListValue
	26, // 12: internal.testproto.example.v1.DescribeAdvancedShapesRequest.dynamic:type_name -> google.protobuf.Value
	27, // 13: internal.testproto.example.v1.DescribeAdvancedShapesRequest.note:type_name -> google.protobuf.StringValue
	28, // 14: internal.testproto.example.v1.DescribeAdvancedShapesRequest.total:type_name -> google.protobuf.Int64Value
	29, // 15: internal.testproto.example.v1.DescribeAdvancedShapesRequest.enabled:type_name -> google.protobuf.BoolValue
	30, // 16: internal.testproto.example.v1.DescribeAdvancedShapesRequest.ratio:type_name -> google.protobuf.DoubleValue
	31, // 17: internal.testproto.example.v1.DescribeAdvancedShapesRequest.mask:type_name -> google.protobuf.FieldMask
	32, // 18: internal.testproto.example.v1.DescribeAdvancedShapesRequest.blob:type_name -> google.protobuf.BytesValue
	33, // 19: internal.testproto.example.v1.DescribeAdvancedShapesRequest.small_total:type_name -> google.protobuf.Int32Value
	34, // 20: internal.testproto.example.v1.DescribeAdvancedShapesRequest.uint_total:type_name -> google.protobuf.UInt32Value
	35, // 21: internal.testproto.example.v1.DescribeAdvancedShapesRequest.huge_total:type_name -> google.protobuf.UInt64Value
	36, // 22: internal.testproto.example.v1.DescribeAdvancedShapesRequest.weight:type_name -> google.protobuf.FloatValue
	12, // 23: internal.testproto.example.v1.DescribeAdvancedShapesRequest.tree:type_name -> internal.testproto.example.v1.RecursiveNode
	37, // 24: internal.testproto.example.v1.DescribeAdvancedShapesRequest.detail_any:type_name -> google.protobuf.Any
	37, // 25: internal.testproto.example.v1.DescribeAdvancedShapesRequest.duration_any:type_name -> google.protobuf.Any
	11, // 26: internal.testproto.example.v1.DescribeAdvancedShapesRequest.city_details:type_name -> internal.testproto.example.v1.ReportDetails
	17, // 27: internal.testproto.example.v1.DescribeAdvancedShapesResponse.labels:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesResponse.LabelsEntry
	18, // 28: internal.testproto.example.v1.DescribeAdvancedShapesResponse.quantities:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesResponse.QuantitiesEntry
	19, // 29: internal.testproto.example.v1.DescribeAdvancedShapesResponse.toggles:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesResponse.TogglesEntry
	20, // 30: internal.testproto.example.v1.DescribeAdvancedShapesResponse.limits:type_name -> internal.testproto.example.v1.DescribeAdvancedShapesResponse.LimitsEntry
	22, // 31: internal.testproto.example.v1.DescribeAdvancedShapesResponse.observed_at:type_name -> google.protobuf.Timestamp
	23, // 32: internal.testproto.example.v1.DescribeAdvancedShapesResponse.ttl:type_name -> google.protobuf.Duration
	24, // 33: internal.testproto.example.v1.DescribeAdvancedShapesResponse.payload:type_name -> google.protobuf.Struct
	25, // 34: internal.testproto.example.v1.DescribeAdvancedShapesResponse.items:type_name -> google.protobuf.ListValue
	26, // 35: internal.testproto.example.v1.DescribeAdvancedShapesResponse.dynamic:type_name -> google.protobuf.Value
	27, // 36: internal.testproto.example.v1.DescribeAdvancedShapesResponse.note:type_name -> google.protobuf.StringValue
	28, // 37: internal.testproto.example.v1.DescribeAdvancedShapesResponse.total:type_name -> google.protobuf.Int64Value
	29, // 38: internal.testproto.example.v1.DescribeAdvancedShapesResponse.enabled:type_name -> google.protobuf.BoolValue
	30, // 39: internal.testproto.example.v1.DescribeAdvancedShapesResponse.ratio:type_name -> google.protobuf.DoubleValue
	31, // 40: internal.testproto.example.v1.DescribeAdvancedShapesResponse.mask:type_name -> google.protobuf.FieldMask
	32, // 41: internal.testproto.example.v1.DescribeAdvancedShapesResponse.blob:type_name -> google.protobuf.BytesValue
	33, // 42: internal.testproto.example.v1.DescribeAdvancedShapesResponse.small_total:type_name -> google.protobuf.Int32Value
	34, // 43: internal.testproto.example.v1.DescribeAdvancedShapesResponse.uint_total:type_name -> google.protobuf.UInt32Value
	35, // 44: internal.testproto.example.v1.DescribeAdvancedShapesResponse.huge_total:type_name -> google.protobuf.UInt64Value
	36, // 45: internal.testproto.example.v1.DescribeAdvancedShapesResponse.weight:type_name -> google.protobuf.FloatValue
	12, // 46: internal.testproto.example.v1.DescribeAdvancedShapesResponse.tree:type_name -> internal.testproto.example.v1.RecursiveNode
	37, // 47: internal.testproto.example.v1.DescribeAdvancedShapesResponse.detail_any:type_name -> google.protobuf.Any
	37, // 48: internal.testproto.example.v1.DescribeAdvancedShapesResponse.duration_any:type_name -> google.protobuf.Any
	11, // 49: internal.testproto.example.v1.DescribeAdvancedShapesResponse.city_details:type_name -> internal.testproto.example.v1.ReportDetails
	0,  // 50: internal.testproto.example.v1.DescribeScalarShapesRequest.status:type_name -> internal.testproto.example.v1.ReportStatus
	11, // 51: internal.testproto.example.v1.DescribeScalarShapesRequest.details:type_name -> internal.testproto.example.v1.ReportDetails
	0,  // 52: internal.testproto.example.v1.DescribeScalarShapesRequest.optional_status:type_name -> internal.testproto.example.v1.ReportStatus
	0,  // 53: internal.testproto.example.v1.DescribeScalarShapesResponse.status:type_name -> internal.testproto.example.v1.ReportStatus
	11, // 54: internal.testproto.example.v1.DescribeScalarShapesResponse.details:type_name -> internal.testproto.example.v1.ReportDetails
	0,  // 55: internal.testproto.example.v1.DescribeScalarShapesResponse.optional_status:type_name -> internal.testproto.example.v1.ReportStatus
	12, // 56: internal.testproto.example.v1.RecursiveNode.child:type_name -> internal.testproto.example.v1.RecursiveNode
	12, // 57: internal.testproto.example.v1.RecursiveNode.children:type_name -> internal.testproto.example.v1.RecursiveNode
	1,  // 58: internal.testproto.example.v1.ExampleAPI.CreateReport:input_type -> internal.testproto.example.v1.CreateReportRequest
	5,  // 59: internal.testproto.example.v1.ExampleAPI.Ping:input_type -> internal.testproto.example.v1.PingRequest
	7,  // 60: internal.testproto.example.v1.ExampleAPI.DescribeAdvancedShapes:input_type -> internal.testproto.example.v1.DescribeAdvancedShapesRequest
	9,  // 61: internal.testproto.example.v1.ExampleAPI.DescribeScalarShapes:input_type -> internal.testproto.example.v1.DescribeScalarShapesRequest
	3,  // 62: internal.testproto.example.v1.ExampleAPI.HiddenThing:input_type -> internal.testproto.example.v1.HiddenThingRequest
	2,  // 63: internal.testproto.example.v1.ExampleAPI.CreateReport:output_type -> internal.testproto.example.v1.CreateReportResponse
	6,  // 64: internal.testproto.example.v1.ExampleAPI.Ping:output_type -> internal.testproto.example.v1.PingResponse
	8,  // 65: internal.testproto.example.v1.ExampleAPI.DescribeAdvancedShapes:output_type -> internal.testproto.example.v1.DescribeAdvancedShapesResponse
	10, // 66: internal.testproto.example.v1.ExampleAPI.DescribeScalarShapes:output_type -> internal.testproto.example.v1.DescribeScalarShapesResponse
	4,  // 67: internal.testproto.example.v1.ExampleAPI.HiddenThing:output_type -> internal.testproto.example.v1.HiddenThingResponse
	63, // [63:68] is the sub-list for method output_type
	58, // [58:63] is the sub-list for method input_type
	58, // [58:58] is the sub-list for extension type_name
	58, // [58:58] is the sub-list for extension extendee
	0,  // [0:58] is the sub-list for field type_name
}

func init() { file_internal_testproto_example_v1_example_proto_init() }
func file_internal_testproto_example_v1_example_proto_init() {
	if File_internal_testproto_example_v1_example_proto != nil {
		return
	}
	file_internal_testproto_example_v1_example_proto_msgTypes[0].OneofWrappers = []any{}
	file_internal_testproto_example_v1_example_proto_msgTypes[6].OneofWrappers = []any{
		(*DescribeAdvancedShapesRequest_CityAlias)(nil),
		(*DescribeAdvancedShapesRequest_CityId)(nil),
		(*DescribeAdvancedShapesRequest_CityDetails)(nil),
	}
	file_internal_testproto_example_v1_example_proto_msgTypes[7].OneofWrappers = []any{
		(*DescribeAdvancedShapesResponse_CityAlias)(nil),
		(*DescribeAdvancedShapesResponse_CityId)(nil),
		(*DescribeAdvancedShapesResponse_CityDetails)(nil),
	}
	file_internal_testproto_example_v1_example_proto_msgTypes[8].OneofWrappers = []any{}
	file_internal_testproto_example_v1_example_proto_msgTypes[9].OneofWrappers = []any{}
	file_internal_testproto_example_v1_example_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testproto_example_v1_example_proto_rawDesc), len(file_internal_testproto_example_v1_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_testproto_example_v1_example_proto_goTypes,
		DependencyIndexes: file_internal_testproto_example_v1_example_proto_depIdxs,
		EnumInfos:         file_internal_testproto_example_v1_example_proto_enumTypes,
		MessageInfos:      file_internal_testproto_example_v1_example_proto_msgTypes,
	}.Build()
	File_internal_testproto_example_v1_example_proto = out.File
	file_internal_testproto_example_v1_example_proto_goTypes = nil
	file_internal_testproto_example_v1_example_proto_depIdxs = nil
}
