// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v0.14.1-v0.15.2-bufbuild-protocompile-easyp-rc1
// source: api/mcp/options/v1/options.proto

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceOptions defines MCP metadata for a protobuf service.
type ServiceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace is prepended to generated tool names with an underscore.
	// Dots and repeated underscores are normalized to a single underscore.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// description overrides the service description inferred from proto comments.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_api_mcp_options_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_mcp_options_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_api_mcp_options_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceOptions) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// MethodOptions defines MCP metadata for a protobuf RPC method.
type MethodOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name overrides the generated tool name segment for the RPC method.
	// Dots and repeated underscores are normalized to a single underscore.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// title sets the MCP tool title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// description overrides the RPC description inferred from proto comments.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// hidden disables tool generation for the RPC method.
	Hidden bool `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// disabled disables tool generation for the RPC method.
	Disabled bool `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// examples adds JSON Schema examples for the generated tool.
	Examples      []string `protobuf:"bytes,6,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_api_mcp_options_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_mcp_options_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_api_mcp_options_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MethodOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MethodOptions) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *MethodOptions) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *MethodOptions) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

// FieldOptions defines MCP metadata for a protobuf field.
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// required forces a field to be required in generated JSON Schema.
	Required *bool `protobuf:"varint,1,opt,name=required,proto3,oneof" json:"required,omitempty"`
	// optional forces a field to be optional in generated JSON Schema.
	Optional *bool `protobuf:"varint,2,opt,name=optional,proto3,oneof" json:"optional,omitempty"`
	// description overrides the field description inferred from proto comments.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// examples adds JSON Schema examples for the generated field schema.
	Examples      []string `protobuf:"bytes,4,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_api_mcp_options_v1_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_mcp_options_v1_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_api_mcp_options_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *FieldOptions) GetOptional() bool {
	if x != nil && x.Optional != nil {
		return *x.Optional
	}
	return false
}

func (x *FieldOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldOptions) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

var file_api_mcp_options_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         91001,
		Name:          "api.mcp.options.v1.service",
		Tag:           "bytes,91001,opt,name=service",
		Filename:      "api/mcp/options/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         91002,
		Name:          "api.mcp.options.v1.method",
		Tag:           "bytes,91002,opt,name=method",
		Filename:      "api/mcp/options/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         91003,
		Name:          "api.mcp.options.v1.field",
		Tag:           "bytes,91003,opt,name=field",
		Filename:      "api/mcp/options/v1/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// service stores MCP metadata for a protobuf service.
	//
	// optional api.mcp.options.v1.ServiceOptions service = 91001;
	E_Service = &file_api_mcp_options_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// method stores MCP metadata for a protobuf RPC method.
	//
	// optional api.mcp.options.v1.MethodOptions method = 91002;
	E_Method = &file_api_mcp_options_v1_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// field stores MCP metadata for a protobuf field.
	//
	// optional api.mcp.options.v1.FieldOptions field = 91003;
	E_Field = &file_api_mcp_options_v1_options_proto_extTypes[2]
)

var File_api_mcp_options_v1_options_proto protoreflect.FileDescriptor

const file_api_mcp_options_v1_options_proto_rawDesc = "" +
	"\n" +
	" api/mcp/options/v1/options.proto\x12\x12api.mcp.options.v1\x1a google/protobuf/descriptor.proto\"P\n" +
	"\x0eServiceOptions\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xab\x01\n" +
	"\rMethodOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\x12\x1a\n" +
	"\bexamples\x18\x06 \x03(\tR\bexamples\"\xa8\x01\n" +
	"\fFieldOptions\x12\x1f\n" +
	"\brequired\x18\x01 \x01(\bH\x00R\brequired\x88\x01\x01\x12\x1f\n" +
	"\boptional\x18\x02 \x01(\bH\x01R\boptional\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x04 \x03(\tR\bexamplesB\v\n" +
	"\t_requiredB\v\n" +
	"\t_optional:_\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xf9\xc6\x05 \x01(\v2\".api.mcp.options.v1.ServiceOptionsR\aservice:[\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xfa\xc6\x05 \x01(\v2!.api.mcp.options.v1.MethodOptionsR\x06method:W\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xfb\xc6\x05 \x01(\v2 .api.mcp.options.v1.FieldOptionsR\x05fieldBCZAgithub.com/easyp-tech/protoc-gen-mcp/api/mcp/options/v1;optionsv1b\x06proto3"

var (
	file_api_mcp_options_v1_options_proto_rawDescOnce sync.Once
	file_api_mcp_options_v1_options_proto_rawDescData []byte
)

func file_api_mcp_options_v1_options_proto_rawDescGZIP() []byte {
	file_api_mcp_options_v1_options_proto_rawDescOnce.Do(func() {
		file_api_mcp_options_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mcp_options_v1_options_proto_rawDesc), len(file_api_mcp_options_v1_options_proto_rawDesc)))
	})
	return file_api_mcp_options_v1_options_proto_rawDescData
}

var file_api_mcp_options_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_mcp_options_v1_options_proto_goTypes = []any{
	(*ServiceOptions)(nil),              // 0: api.mcp.options.v1.ServiceOptions
	(*MethodOptions)(nil),               // 1: api.mcp.options.v1.MethodOptions
	(*FieldOptions)(nil),                // 2: api.mcp.options.v1.FieldOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 4: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),   // 5: google.protobuf.FieldOptions
}
var file_api_mcp_options_v1_options_proto_depIdxs = []int32{
	3, // 0: api.mcp.options.v1.service:extendee -> google.protobuf.ServiceOptions
	4, // 1: api.mcp.options.v1.method:extendee -> google.protobuf.MethodOptions
	5, // 2: api.mcp.options.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 3: api.mcp.options.v1.service:type_name -> api.mcp.options.v1.ServiceOptions
	1, // 4: api.mcp.options.v1.method:type_name -> api.mcp.options.v1.MethodOptions
	2, // 5: api.mcp.options.v1.field:type_name -> api.mcp.options.v1.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_mcp_options_v1_options_proto_init() }
func file_api_mcp_options_v1_options_proto_init() {
	if File_api_mcp_options_v1_options_proto != nil {
		return
	}
	file_api_mcp_options_v1_options_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mcp_options_v1_options_proto_rawDesc), len(file_api_mcp_options_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_api_mcp_options_v1_options_proto_goTypes,
		DependencyIndexes: file_api_mcp_options_v1_options_proto_depIdxs,
		MessageInfos:      file_api_mcp_options_v1_options_proto_msgTypes,
		ExtensionInfos:    file_api_mcp_options_v1_options_proto_extTypes,
	}.Build()
	File_api_mcp_options_v1_options_proto = out.File
	file_api_mcp_options_v1_options_proto_goTypes = nil
	file_api_mcp_options_v1_options_proto_depIdxs = nil
}
